### ISSUE TITLE
sqlp - add ability to use `STDIN` as table name instead of just `_t_1` when piping in a CSV

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#1026]
How do I reference columns from a CSV which does not have a header?

I can reference stdin if used within a pipe as `_t_1` would it no better to have a specific name (as well, perhaps) ie something like `STDIN` to make code easier to read?

**Comment by jqnatividad** [comment]
Hi @ondohotola ,
The sqlparser crate that polars uses enforces the SQL92 standard, which requires column names.

To make it more convenient to add "generic column names" to a CSV with no headers,  I just added an "_all_generic" special parameter to the `rename` command.

As for stdin, I'll take that into consideration for the next release.

**Comment by jqnatividad** [comment]
Turns out `sqlp` already does this... :)

https://github.com/jqnatividad/qsv/commit/64c85ae627b9e7e2b1b14ff51cc18cca164f9e6a
