### ISSUE TITLE
v0.106.0 - the `linux-musl` binary does not seem to work (but v0.105.1 works)

### ISSUE THREAD

**Issue by ramkumarkb** [jqnatividad/qsv#1044]
**Describe the bug**
First of all, thanks for the amazing `qsv` project ! 
I am testing `qsv` in RHEL8 machine with `linux-musl` distribution - `v0.106.0` does not seem to work but `v0.105.1` works.

**To Reproduce**
v0.106.0 - 
`./qsv --help` => Nothing in the output (just hangs with no error message)

v0.105.1 - 
`./qsv --help` = > 
```
Usage:
    qsvlite <command> [<args>...]
    qsvlite [options]

Options:
    --list               List all commands available.
    --envlist            List all qsv-relevant environment variables.
    -u, --update         Update qsv to the latest release from GitHub.
    -U, --updatenow      Update qsv to the latest release from GitHub without confirming.
    -h, --help           Display this message
    <command> -h         Display the command help message
    -v, --version        Print version info, mem allocator, features installed, 
                         max_jobs, num_cpus, build info then exit

* sponsored by datHere - Data Infrastructure Engineering
```

**Expected behavior**
Not sure why the version `0.106.0` does not work and there is no error message also.

**Comment by jqnatividad** [comment]
I don't have RHEL 8 to reproduce this, but you may want to try using qsv_glibc-2.31 in the x86_64_unknown_linux_gnu zip.  It is linked against glibc 2.31 (as opposed to glibc 2.35 in the regular qsv binary) which should work in RHEL 9 which has glibc 2.34.

**Comment by ramkumarkb** [comment]
@jqnatividad  - Thank you for the reply. RHEL8 comes with glibc-2.28. 
```
[user@host] ~/qsv_poc]$ rpm -q glibc
glibc-2.28-211.el8.x86_64
```

So `v0.106.0` & `v0.105.1` were pre-built with very different versions of the build tool-chain?

**Comment by jqnatividad** [comment]
@ramkumarkb it could be because I enabled the `magic` feature for musl in the `0.106.0` release.

https://github.com/jqnatividad/qsv/blob/525feb713da928918959f7324878891d2ba1f17d/.github/workflows/publish.yml#L44-L53

`magic` is used by the `sniff` command to detect a file's mime type.

Perhaps, that's what causing the problem?

Have you tried compiling from source on RHEL 8?

**Comment by jqnatividad** [comment]
@ramkumarkb , can you confirm if you're still having issues with `0.107.0`?

**Comment by ramkumarkb** [comment]
@jqnatividad - Thank you for the reply. Yes, I can conform that I still face issues with `0.107.0`. 

Unfortunately, I do not have `rust` toolchain in teh RHEL8. However, I can try to build `GCC` & `GLIBC` to a higher version in a separate dir (the versions used by default in RHEL9) and then use the `LD_LIBRARY_PATH` approach with the latest version of `qsv` ?

**Comment by jqnatividad** [comment]
@ramkumarkb , can you try now with 0.108.0?

**Comment by ramkumarkb** [comment]
@jqnatividad  - Yes `0.108.0` works ! 
Thank you very much for updates. What changed in the build tool-chain?

**Comment by jqnatividad** [comment]
Good to know...

I think removing libmagic did it...

https://github.com/jqnatividad/qsv/blob/master/.github/workflows/publish.yml
