### ISSUE TITLE
`sqlp`: add ability to handle different decimal operators

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1050]
@jqnatividad I'm adding a problem, that I'm able to manage using duckdb.

In Italy, the floating separator is `,` and not the `.` If I use qsv to import OpenCoesione data, all the numeric fields are mapped as string (because we have the `,`).

In duckdb I solve using `decimal_separator=','`  parameter.
If there is something similar in polar, it would be very useful to have it also in qsv.

![image](https://github.com/jqnatividad/qsv/assets/30607/f057f6c8-5043-4db1-b11c-5efbce9f84aa)

_Originally posted by @aborruso in https://github.com/jqnatividad/qsv/issues/1047#issuecomment-1592735038_

**Comment by jqnatividad** [comment]
Unfortunately @aborruso , at the moment, this is not available in the current version of Polars.

There's an open issue for it though - 
https://github.com/pola-rs/polars/issues/6698

In the meantime, you can use `apply operations thousands` in your pipeline to convert the comma decimal separator to the dot decimal separator, before passing it to `sqlp`, and then convert it back later again with the `apply operations thousands` command.

**Comment by aborruso** [comment]
Thank you very much

**Comment by jqnatividad** [comment]
This is still open on polars repo...

**Comment by jqnatividad** [comment]
This remains an open issue in Polars...

**Comment by jqnatividad** [comment]
Glad to report that decimal operators are now supported in Polars main!
https://github.com/pola-rs/polars/pull/15774

Hopefully, it finds its way into polars-sql...

**Comment by jqnatividad** [comment]
With the `--decimal-comma` option, you can now read input data with floats using comma as a decimal separator instead of period.

Bear in mind that you'll need to specify an alternate delimiter as well (not the default comma delimiter)

**Comment by aborruso** [comment]
Thank you very much
