### ISSUE TITLE
separator between (column) name and field in flatten

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#1054]
I occasionally would like to import a flattened CSV into [typst](https://github.com/typst/typst/),  and would therefor like to process the names and content from each line. 

It would be helpful to have an option to generate CSV so I can process the result of flatten easily (without having to rename the (column) names.

For the (current) record separator I can easily use ',' (comma) so it would not break anything in a pipe, and fixlengths will of course work in a file.

ie something like

```bash
| qsv luau map A,B '{"["..col[1].."]","["..col[2].."]"}'|qsv select A,B|awk '{print $0 ","}'
```

ie

```csv
one word, 1
2, two words
```

would become

```csv
[one word], [1],
[2], [two words],
```

which is what a `typst` table needs (incl trailing comma).

**Comment by jqnatividad** [comment]
To clarify @ondohotola ,

Will adding a `--field-separator <arg>` option to `flatten` meet your requirements?

```
 -f, --field-separator <arg>  A string of characters to write between a column name and its value
                                               for each record.
```

**Comment by ondohotola** [comment]
definitively

**Comment by jqnatividad** [comment]
Done.  Please let me know how it works for you and then close this issue if it works as expected.

**Comment by ondohotola** [comment]
thanks, am in transit, so either tonight or tomorrow

**Comment by ondohotola** [comment]
```
cargo install qsv --locked --features feature_capable
```

doesn't pick it up yet, so will try again tomorrow

**Comment by jqnatividad** [comment]
0.108.0 is out @ondohotola . Please let me know how `flatten --field-separator` works for you.

**Comment by ondohotola** [comment]
Sorry, I was in transit.

It works very nicely, thank you very much, but requires a pipe to 

```
qsv input --trim-headers --trim-fields
```

**Comment by jqnatividad** [comment]
Composability was one of qsv's main goals.

So long as the task can be composed on the command line fairly easily, with qsv and other CLI tools, it should be good to go.

Perhaps, you can add a recipe to the Wiki so other folks who want to do something similar can quickly find it?

**Comment by ondohotola** [comment]
I am playing with [typst](https://github.com/typst/typst/) as I may have advised before which has a very nice CSV import (into table(x)) mode. There it is not even required as [typst](https://github.com/typst/typst/) takes care of whitespace.

And indeed putting another call into the pipeline fixes is no effort at all, however, I felt I'd let you know.

I may have actually time for things like WikI come next year (impending retirement from practice)

I will have time for this come October (when I retire) :-)-O

Thank you again.
