### ISSUE TITLE
All calls of qsv (even trivial ones like `--help` or `--list`) are heavyweight.

### ISSUE THREAD

**Issue by vi** [jqnatividad/qsv#1063]
**Describe the bug**

Any invocation of `qsv 0.107.0-mimalloc-apply;fetch;foreach;generate;magic-0.13.0;self_update-12-12;50.07 ... prebuilt` is heavyweight.

**To Reproduce**

1. Try both `qsv` and `xsv` tools to do something simple, using just a couple of rows
2. Compare performance

```
$ printf 'a\nb\nc\n' | time xsv cat rows
a
b
c
0.00user 0.00system 0:00.00elapsed 100%CPU (0avgtext+0avgdata 5460maxresident)k
0inputs+0outputs (0major+475minor)pagefaults 0swaps
```

```
$ printf 'a\nb\nc\n' | time ./qsv cat rows
a
b
c
0.20user 0.66system 0:00.48elapsed 179%CPU (0avgtext+0avgdata 64484maxresident)k
0inputs+0outputs (0major+963minor)pagefaults 0swaps
```

Half a second just to start qsv, 11 times the memory.

**Expected behavior**

`qsv` is not much slower than `xsv` for operations implemented in both tools.

**Screenshots/Backtrace/Sample Data**

```
$ strace -fc ./qsv_nightly_musl-1.1.24 --version
(13 threads get started)
qsv 0.107.0-mimalloc-apply;fetch;foreach;generate;polars;self_update-12-12;50.07 GiB-17.77 GiB-46.29 GiB-62.58 GiB (x86_64-unknown-linux-musl compiled with Rust 1.70.0) prebuilt-nightly-older
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ------------------
 30.93    2.483401        5099       487       110 futex
 14.51    1.165402          52     22256      9906 open
 13.48    1.082563          47     22842         1 read
 10.36    0.832227          44     18882           lseek
  6.81    0.546608          43     12586           fcntl
  6.53    0.524465          47     10929     10457 readlink
  6.34    0.509098          45     11302           fstat
  5.73    0.459880          37     12427           close
  2.20    0.177010          39      4536         1 stat
  1.09    0.087197          58      1491           getdents64
  1.06    0.084902          36      2298           sched_yield
...
```

There is heavy interthread synchronisation, filesystem usage, network usage (why?). `/var/run/nscd/socket` is accessed multiple times. It scans `/sys/class/hwmon/`, `/sys/class/net/` and `/proc/*/{cmdline,environ,task/,io,stat}`, `/sys/block/`, `/etc/group` for some reason.

Somebody could think there is some malware involved.

"lite" or "dp" editions are not immune to the slow startup. Old version (`qsv 0.76.3-mimalloc-apply;fetch;foreach;generate;self_update-12-12 (x86_64-unknown-linux-musl compiled with Rust 1.65) prebuilt`) was relatively fast to start.

**Desktop (please complete the following information):**
 - OS: Linux Debian Bookworm
 - qsv Version: 0.107.0 from Github Releases.

P.S. Strangest syscall:

`mkdir(".", 0777)                        = -1 EEXIST (File exists)`

Why?

**Comment by ondohotola** [comment]
run this with hyperfine and 3 warmup runs on real life data.

Once QSV is in the cache that should reduce, never mind that I don’t really notice the difference in 0.00 and 0.5 seconds.

**Comment by jqnatividad** [comment]
Thanks @vi for this thorough investigation, as one of qsv's main goals is blazing-fast performance.  Great find on sysinfo::System::new_all() unnecessarily spawning all that activity!

And yeah, most of my benchmarking is not that rigorous as it's already exponentially faster than the ol' Python-based stuff I was using before.

When I first forked xsv, I was hoping to to convert the benchmark scripts to hyperfine (#98) and I would have caught this performance regression if that was in place.

Hopefully, I'll get around to it (or perhaps, somebody can take it on 😉 )
