### ISSUE TITLE
sqlp queries do not recognize snappy files

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#1076]
Given `t.csv` looking like

```
a,b,c
1,2,3
4,5,6
7,8,9
```
`qsv sqlp -Q t.csv "select * from t"` returns the expected

```
a,b,c
1,2,3
4,5,6
7,8,9
```

however, after snapping it with `qsv compress t.csv > t.csv.sz`

`qsv sqlp t.csv.cz "select * from t"` returns

```
Failed to execute query: select * from t: relation 't' was not found
```
`qsv stats t.csv.sz` for example  does return the expected 

```
field,type,sum,min,max,range,min_length,max_length,mean,stddev,variance,nullcount,sparsity
a,Integer,12,1,7,6,1,1,4,2.4495,6,0,0
b,Integer,15,2,8,6,1,1,5,2.4495,6,0,0
c,Integer,18,3,9,6,1,1,6,2.4495,6,0,0
```

As do most other commands I have tested.

in my view `sqlp` should also notice snapped files and uncompress them on the fly.

**Comment by jqnatividad** [comment]
@ondohotola , thanks for the report.

This was my intent with the `process_input` helper fn - to support snappy files for sqlp.

https://github.com/jqnatividad/qsv/blob/8ddb2d6e52b566c5b4b39ecafede61301fb5c1d7/src/util.rs#L1397-L1459

I'll investigate why its not behaving as expected.

**Comment by ondohotola** [comment]
Great, I'll wait for `qsv -U` to pull the next version and revert.
