### ISSUE TITLE
Create duckdb-backed `sql` command

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1078]
Now that `sqlp` is stable, we can close #828 and just add this issue for a duck-db backed `sql` command.

In that way, users can opt to use the SQL engine of their choice for their workload - with the `polars` feature, using `sqlp` and its Polars SQL dialect; with the `to` feature,  using DuckDB SQL (consider adding another feature to enable duckdb, instead of overloading `to`).

Similar to qsv having `join` and `joinp` commands, we can have two similar sql commands.

**Comment by derekmahar** [comment]
By its own [admission](https://docs.pola.rs/user-guide/sql/intro/#compatibility), [Polars SQL](https://docs.pola.rs/user-guide/sql/intro/) doesn't support the "full SQL language".  DuckDB supports far more SQL syntax than does Polars.

**Comment by jqnatividad** [comment]
Thanks @derekmahar , will reconsider this after the next Polars release where they're releasing a lot of SQL functionality.

BTW, the info on that page where they list Polars SQL's shortcomings is outdated - it supports table aliasing (which qsv uses with its _t_N aliases, but you can also specify your own traditional SQL aliases) and Meta queries (we even have a test EXPLAIN in `sqlp`'s CI tests).

**Comment by derekmahar** [comment]
Thank you.  I'll keep an eye on both Polars SQL and DuckDB.    Both projects are moving fast!

**Comment by jqnatividad** [comment]
Hi @derekmahar ,
Just incorporated Polars 0.37.0 and it adds a ton of SQL features.

https://github.com/pola-rs/polars/compare/rs-0.36.2...main

https://github.com/jqnatividad/qsv/blob/master/tests/test_sqlp.rs

BTW, it'd be great if you can share what you're using qsv for.  No need to go into details if you're not at liberty to disclose, just general overview would be awesome!

As I see you as a power user, I'm keen to learn a little bit more about your use cases - https://github.com/jqnatividad/qsv/discussions/1529

**Comment by derekmahar** [comment]
> Hi @derekmahar , Just incorporated Polars 0.37.0 and it adds a ton of SQL features.
> 
> [pola-rs/polars@rs-0.36.2...main](https://github.com/pola-rs/polars/compare/rs-0.36.2...main)
> 
> https://github.com/jqnatividad/qsv/blob/master/tests/test_sqlp.rs

I'm pleased that Polars 0.37.0 introduces many new SQL features, but I confess that I find difficult using these two sources to compare Polars' SQL features with those not only of its predecessor 0.36.2, but even more so with DuckDB.  I would likely find it easier to compare the SQL features of these two projects using a summary of their SQL features or their SQL documentation, when more current.

> BTW, it'd be great if you can share what you're using qsv for. No need to go into details if you're not at liberty to disclose, just general overview would be awesome!
> 
> As I see you as a power user, I'm keen to learn a little bit more about your use cases - #1529

I've been reluctant to share my qsv use cases because I'm not actually a qsv power user.  However, I did share a few of my [experiences](https://github.com/jqnatividad/qsv/discussions/1529#discussioncomment-8290639) using qsv.

**Comment by ondohotola** [comment]
I am wondering whether you should not actually revisit adding a `to duckdb` anyway, as it could be as simple as

`CREATE TABLE namaf as FROM 'namaf.csv';`

and there are a few things that I am eagerly awaiting the polars crate maintainers to implement :-)-O
