### ISSUE TITLE
`describegpt`: allow user to pass OpenAI api key on the CLI as well

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1083]
see the `luau --ckan-token` option for a reference implementation.

**Comment by rzmk** [comment]
@jqnatividad Should the `--key` be prioritized first or the `OPENAI_API_KEY` environment variable?

**Comment by jqnatividad** [comment]
The convention in qsv is outlined here - https://github.com/jqnatividad/qsv/blob/master/docs/ENVIRONMENT_VARIABLES.md#env-file-support

Just follow how it was implemented in `luau` for `--ckan-token` and it will behave as expected.

Also, change the envvar name to `QSV_OPENAI_API_KEY` and document it in the ENVIRONMENT_VARIABLES md file.

Let's keep the QSV_ prefix to avoid namespace collisions, and so that it's automatically listed when calling `qsv --envlist`
