### ISSUE TITLE
`describegpt`: add a --prompt-file option

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1085]
The prompt file is a json file specifying the dictionary prompt, description prompt and the tags prompt to use.

If specified, it will load the prompts from the json file instead of using the default prompts.

**Comment by rzmk** [comment]
@jqnatividad Is there a default format that's expected for the prompt file? For example:

```json
{
    "dictionary_prompt": "...",
    "description_prompt": "...",
    "tags_prompt": "..."
}
```

We can then check if the `--prompt-file` option and relevant inference option(s) are used are used, and if they exist in the file to run them.

Also should we specify that prompt file format anywhere?

**Comment by jqnatividad** [comment]
@rzmk , add some metadata attributes:

```json
{
  "name": "...",
  "description": "...",
  "author": "...",
  "version": "...",
  "tokens": 10,
  "dictionary_prompt": "...",
  "description_prompt": "..",
  "tags_promt": "..."
}
```

the tokens attribute will be used unless `--max-tokens` option is set explicitly when invoking describegpt.

As for specifying the `--prompt-file` format. document it in the `docs` directory, similar to how `fetch` has its own markdown file there.

**Comment by rzmk** [comment]
@jqnatividad How should we identify where to input the stats, frequency, and json_add string within these prompts?
