### ISSUE TITLE
insertion point for fixlengths

### ISSUE THREAD

**Issue by ggrothendieck** [jqnatividad/qsv#1089]
One reason to need fixlengths is that there are multiple subfields for one field without quoting it.  If that field is the last then fixlengths can be used but not if it is the second last, say.  What would be nice is if the position of the insertion point for the extra commas could be specified.  For example -1 would mean the extra comma(s) would be inserted at the last comma.  If there were no commas then the commas are still added at the end.

Here is an example of sample input taken from https://stackoverflow.com/questions/76423878/reading-a-csv-file-into-r-which-contains-comma-separated-values-in-single-obser/76427295#76427295  (There is also an awk program at that link which handles this particular example if you need additional clarification.)
```
 clothes,colours,size 
 shirt,blue,green,grey,small
 shirt,yellow,black,small
 shorts,blue,medium
 shorts,black,large
```

The corresponding output would be
```
clothes,colour1,colour2,colour3,size
shirt,blue,green,grey,small
shirt,yellow,black,,small
shorts,blue,,,medium
shorts,black,,,large
```

although I think it would be sufficient if it did not deal with the header since that can always be skipped by whatever program is reading it in.

**Comment by jqnatividad** [comment]
Thanks for this detailed request @ggrothendieck .

Will investigate it further and add it to the backlog.

**Comment by aborruso** [comment]
@ggrothendieck you could map every row as it was an array: the first element is `clothes`, the last is `size` and everything else is `color`. I'm not able to build a `qsv` solution, but using [Miller](https://miller.readthedocs.io/en/latest/installing-miller/) and starting from

```
clothes,colours,size
shirt,blue,green,grey,small
shirt,yellow,black,small
shorts,blue,medium
shorts,black,large
```

you could run

```
<input.csv tail -n +2 | mlr --n2c put '$array=(splita($1,","));$clothes=$array[1];$size=$array[-1];$color=$array[2:-2]' \
then cut -f clothes,color,size \
then flatten -f color \
then unsparsify
```

to get

```
clothes,size,color.1,color.2,color.3
shirt,small,blue,green,grey
shirt,small,yellow,black,
shorts,medium,blue,,
shorts,large,black,,
```

**Comment by jqnatividad** [comment]
@ggrothendieck I added an `--insert` option.

Please let me know how it works for you.

**Comment by jqnatividad** [comment]
Hi @ggrothendieck , 0.113.0 has been released with `fixlengths --insert` option as requested.

https://github.com/jqnatividad/qsv/releases/tag/0.113.0

Closing this for now. 

Please feel free to open a new issue if `fixlengths --insert` is not working as expected.
