### ISSUE TITLE
`describegpt`: Improve `describegpt` JSON output format for redirection

### ISSUE THREAD

**Issue by rzmk** [jqnatividad/qsv#1106]
## Is your feature request related to a problem? Please describe

Currently, when using the `--json` option in `describegpt` to generate JSON output, the resulting output mixes status messages with JSON snippets. This makes the output invalid JSON and hinders its usability when redirecting it to a file. To enhance the composability of `describegpt`, it would be beneficial if the output could be redirected to a file as valid JSON.

## Describe the solution you'd like

To address this issue, I suggest adjusting `describegpt` so that when the output is redirected to a file, it resolves to valid JSON. One possible approach is to replace all instances of `println!` with `eprintln!` for status messages. By using `eprintln!`, which writes to stderr, the status messages will remain separate from the JSON output.

## Additional Context

Resolving this issue can improve the usability and composability of `describegpt` by allowing users to seamlessly redirect the JSON output to a file without encountering invalid JSON due to mixed status messages.

**Comment by rzmk** [comment]
@jqnatividad In the case that the output isn't valid JSON (i.e. the completion begins with "Here is the output: {...}", etc.), what should occur?

**Comment by jqnatividad** [comment]
@rzmk , I would just separate status messages like that from the structured json output, i.e.:

```rust
eprintln!("Here is the output:");
println!("{JSON SNIPPET}");
```

**Comment by rzmk** [comment]
@jqnatividad where should the json file be specified for output?

**Comment by rzmk** [comment]
@jqnatividad I'm getting double quotes `"` surrounding the JSON output, including when outputting to the file and on print. Any pointers on how I can remove this?

**Comment by jqnatividad** [comment]
@rzmk you may want to create a struct and populate it, and then use serde_json serialization to create valid JSON.

You can check how I used a struct in the `excel` command for `SheetMetadata` to produce either a CSV, a JSON file, or a prettified JSON file leveraging serde serialization/deserialization.
