### ISSUE TITLE
problem with "join --left-semi"

### ISSUE THREAD

**Issue by alperyilmaz** [jqnatividad/qsv#1150]
The test which is located here:
https://github.com/jqnatividad/qsv/blob/3e76676e9f5159a029ac4fb1e3d031857acd4834/tests/test_join.rs#L149C1-L157C1

should have printed out as
```
city,state
Boston,MA
Boston,MA
Buffalo,NY
```

not only
```
city,state
Buffalo,NY
```

Because "Boston,MA" lines are actually match as shown in join result:
```
$ qsv join  city cities.csv city places.csv
city,state,city,place
Boston,MA,Boston,Logan Airport
Boston,MA,Boston,Boston Garden
Buffalo,NY,Buffalo,Ralph Wilson Stadium
```

Also, in theory, combination of results from `--left-semi` and `--left-anti` should give the *left* file. As of now, "Boston,MA" is in neither of results

```
$ qsv join --left-semi city cities.csv city places.csv
city,state
Buffalo,NY

$ qsv join --left-anti city cities.csv city places.csv
city,state
New York,NY
San Francisco,CA
```

PS: thanks for the this great tool and thanks for being such an active developer. Number of closed issues is 288 and active issue is 14.. Which is awesome..

**Comment by jqnatividad** [comment]
Thanks for the report @alperyilmaz ,

That's a bug and will queue it up in the backlog.

In the meantime, it'd be great if you can exercise the new `joinp` command - the Polars-powered join which should be faster and has more options - though it currently does'nt have case-insensitive joins and right outer joins.
