### ISSUE TITLE
Donation for qsv

### ISSUE THREAD

**Issue by WMACCESS** [jqnatividad/qsv#1162]
Dear Joel,

We would like to show our appreciation and support by making a small financial donation towards the further development and maintenance of `qsv`.
**Could you please provide us with your PayPal account email address or any other preferred payment method so that we can transfer the funds?**

We believe that open source software is essential for innovation, and we are committed to supporting projects like `qsv` that make a real difference in the world. 
You can read about our Open Source support initiative for this year in our GitHub Account (https://github.com/WMACCESS).

Thank you for your outstanding work on `qsv`, and we look forward to hearing from you soon.

Best regards,

The WMACCESS Team of CPB Software
Anna Valls Ferron

**Comment by jqnatividad** [comment]
Thank you for your offer and its much appreciated!

I'm humbled that you find qsv is worthy of your support, and I wish more organizations would follow your example and do the same.

The vibrant Internet that we now take for granted and is an essential part of modern life would not have been possible were it not for open source.

qsv itself owes stands on the shoulders of xsv, and the rich Rust open source ecosystem. 

We'll get back to you early next week.  Not just for your offer of financial support, but in connection with project we're involved in creating more sustainable open source ecosystems - https://civicdataecosystem.org/

**Comment by jqnatividad** [comment]
Thanks again @WMACCESS for your support!

Your [enlightened position on open source](https://github.com/WMACCESS#-our-position-on-open-source) and your [Call to Action](https://github.com/WMACCESS#-a-call-to-action) should be celebrated and more widely emulated!

After speaking last Friday, I'll close this issue but you can be sure we'll join you in spreading the message, hopefully, with the NSF's continued support with our https://civicdataecosystem.org project.

**Comment by jqnatividad** [comment]
Hi @WMACCESS Team!

Would you mind adding what you use qsv for here?

https://github.com/jqnatividad/qsv/discussions/1529

It'd be a great help for the project!  Feel free about writing about your support of open source projects too as we aim to make a blogpost detailing our plans for 2024 and calling out supporters like you!

Thanks in advance!
