### ISSUE TITLE
`qsv cat *.csv` retroactively add column(s) w/ empty rows

### ISSUE THREAD

**Issue by isaacadams** [jqnatividad/qsv#1165]
**Is your feature request related to a problem? Please describe.**

I need to concatenate hundreds of csv files together, and, some of the latest ones have extra column names.

When I run `qsv cat *.csv` I understandably get an error that the later csv file headers do not match the earlier ones.

**Describe the solution you'd like**

I'd like a command that compiles all the headers ahead of time (i.e. `qsv headers -j --intersect *.csv`) and then concatenates the csv files together, supplying empty values for the csv files that did not have the new columns in them.

**disclaimer**

Its entirely possible that there is a way to do what I am requesting with the available commands, but I am too dumb to figure it out. If thats the case, would anyone be so kind as to give me hint.

**Comment by isaacadams** [comment]
I rubber ducked myself... lol... found the option I needed smh

**Comment by isaacadams** [comment]
for the record, this was my solution

```bash
#!/bin/bash

# bash scripts/bundle.sh ./fixed "*.csv" > ./bundle.csv

DIR_FIXED=$1
GLOB=$2

mkdir -p $DIR_FIXED

# Step 1: collect the unique header names by parsing all the csv files
unique_headers_list=$(qsv headers -j --intersect $GLOB)
unique_headers_comma=$(qsv headers -j --intersect $GLOB | paste -sd ',')

# Step 2: For each CSV file, add missing headers with default values
FILES=($GLOB)
for file in "${FILES[@]}"; do
    # find the missing headers, if any
    MISSING_HEADERS=$(echo -e "$(qsv headers -j $file)\n$unique_headers_list" | sort | uniq -u | paste -sd ',')

    # add missing headers with default values and write to a temporary file
    # the order of headers cannot be assumed, they must be selected by name
    FILENAME=${file##*/}
    echo $MISSING_HEADERS | qsv cat columns -p $file - | qsv select "$unique_headers_comma" -o "$DIR_FIXED/$FILENAME"
done

# Step 3: Concatenate the CSV files into one final file
echo $(qsv cat rows $DIR_FIXED/*.csv)
```

**Comment by jqnatividad** [comment]
Great @isaacadams !

Do you mind adding your recipe to the [Cookbook](https://github.com/jqnatividad/qsv/wiki/Cookbook#cookbook)?

**Comment by isaacadams** [comment]
> Great @isaacadams !
> 
> Do you mind adding your recipe to the [Cookbook](https://github.com/jqnatividad/qsv/wiki/Cookbook#cookbook)?

I'd love to. I'll submit a PR later today.

**Comment by isaacadams** [comment]
@jqnatividad done: https://github.com/jqnatividad/qsv/wiki/Cookbook/ae3bc0e48597f5981c6cf0ecec84d34ce3b0f636

**Comment by jqnatividad** [comment]
Hi @isaacadams ,

We're currently cataloging how qsv is used in the wild.

Do you mind sharing yours here?

https://github.com/jqnatividad/qsv/discussions/1529

Thanks! We have big plans for qsv in 2024 and knowing how its used would be really helpful.
