### ISSUE TITLE
foreach removes '+' from command and '.' from columns in CSV

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#1171]
Given a file of domain names, something like

```bash
qsv foreach host 'echo dig +short {} a'
```
should result in 

`dig +short omadhina.co.NA a'

but results in

`dig short omadhina co NA a`

I can of course circumvent this but it looks like an issue to me :-)-O

**Comment by jqnatividad** [comment]
Hi @ondohotola ,
Thanks for the report. This is now fixed.

The reason for the bug was `foreach` was splitting the command argument tokens using regex `\w` which only matches only letters, digits and underscore, so it ignored '+' and '.'

**Comment by ondohotola** [comment]
Thanks
