### ISSUE TITLE
Documentation Typos in QSV

### ISSUE THREAD

**Issue by a5dur** [jqnatividad/qsv#1202]
#### Issue Description:
Came across some minor typos and grammatical errors in qsv documentation. Rest all, documentation is comprehensive and well-structured
#### Typos found 
- SECURITY.md
> line 12
- Describegpt.md
> line 39
- ENVIORNMENT_VARIABLES.md
> line 65
- PERFORMANCE.md
> line 83
- whirlwind_tour.md
> line 147
> line 218

**Comment by jqnatividad** [comment]
Thanks @a5dur for the report and fixing the typos!

Just merged #1203
