### ISSUE TITLE
BUG - UTF-8 Truncation in qsv input

### ISSUE THREAD

**Issue by EricSoroos** [jqnatividad/qsv#1234]
**Describe the bug**

In `qsv input <file> --output <outfile>` 

(https://github.com/jqnatividad/qsv/blob/master/src/cmd/input.rs#L12C1-L14C1)
```
Finally, non-UTF8 encoded files are transcoded to UTF-8 with this command, replacing all
invalid UTF-8 sequences with �.
```

This isn't quite true. Non UTF-8 files are forcibly interpreted as UTF-8, ignoring errors, without regard for the initial encoding.

For example, a UTF-16 file with initial BOM looks like this in a hex editor: (note -- portions of the line elided for privacy reasons)

```
00000000   FF FE 6E 00  6F 00 09 00  ...          ..n.o...
```

After a `qsv input` run:
```
00000000   EF BF BD EF  BF BD 6E 00  6F 00 09 00  ...          ......n.o...
```

This then errors out in datapusher-plus because there are null bytes in the utf-8 string. 

The correct utf-8 transcoding strips the BOM and converts the existing ascii range letters into the normal single byte characters:
```
00000000   6E 6F 09 72  ...                         no.r
```

This transcoding was done with 
```
iconv -f `uchardet file.csv` -t UTF-8 file.csv > out.csv
```

Similar issues occur with Window-1252 encoding, where anything that doesn't match a valid UTF-8 code point is stripped. (like euro symbols, character 0x80)

The core issue is https://github.com/jqnatividad/qsv/blob/master/src/cmd/input.rs#L158 and https://github.com/jqnatividad/qsv/blob/master/src/cmd/input.rs#L181 where it's using `string.from_utf8_lossy` without any recognition of the input string's encoding. 

There are a couple of steps to fix here:
* There is a rust crate to detect encodings from a stream (https://docs.rs/chardetng/latest/chardetng/struct.EncodingDetector.html)
* There would still need to be an transcoding step from that encoding. (https://docs.rs/encoding_rs/latest/encoding_rs/) looks roughly like what we'd need

I'm also patching around this in datapusher using the uchardet/iconv loop if it's not detected as UTF-8.

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04, macos
 - qsv Version: various, bug is in master.

**Comment by jqnatividad** [comment]
Thanks for the detailed report @EricSoroos .

Will dive into this to see if I can revisit the "auto-transcoding" functionality I ended up pulling out as it was causing problems.

Perhaps, by fine-tuning `input` and adding more explanatory usage text to use the purpose-built `iconv` to actually do the transcoding.

**Comment by EricSoroos** [comment]
I'm definitely not sure on the rust end, we're patching around it at the moment with `uchardet` for detection and `iconv` for the translation. 

My gut reaction on the rust side is that it's probably better to detect based on the stream, and then do the conversion as you're reading. I'm not sure if there's a good 'one place' to fix that in qsv or not, or if it would wind up scattered across the codebase. Character detection would at the very least require another read of the data, so I can see where you'd want to avoid that if possible.

**Comment by jqnatividad** [comment]
I'm thinking of extending `validate` to check if the file is UTF-8 encoded, and not burden the entire toolkit for utf-8 handling, as what I attempted to do last year.

Also, `sniff` already detects if a file is utf8-encoded.

I'll extend the `--no-infer` option so it also returns the encoding of the file along with its detected mime-type.

Good thing is, both `validate` and `sniff` are already in `qsvdp` - I'll be sure to add the encoding-handling in the CSV screening steps in DP+, with the option to auto-transcode with `iconv`.

**Comment by jqnatividad** [comment]
Hi @EricSoroos ,
`input` now has an `--encoding-errors` option that you use to better handle encoding issues.

`--encoding-errors` has three modes:
* `replace` - the default, with the current behavior of replacing invalid utf8 sequences with the replacement character
* `skip` - to replace the field value where the encoding error was encountered with the value `<SKIPPED>`
* `strict` - to immediately fail on any encoding error. There is now a dedicated encoding exit code if you want to trap it in your scripts (along with new exit codes for Network and OOM errors as well)
https://github.com/jqnatividad/qsv/blob/e3d51e54304602ed5bdc490b333a843639415676/src/clitypes.rs#L118-L126

And if you turn on debug logging (`export QSV_LOG_LEVEL=debug`), you can have a log of what rows/fields were replaced/skipped.

As for adding encoding detector in `sniff` - that will take a while and I'm adding it to the backlog.

**Comment by jqnatividad** [comment]
@EricSoroos , for excel exports, do you still have encoding problems using qsv's `excel` command?

Let me know, as I've been contributing to calamine of late and I'd rather have excel encoding issues handled by the calamine library, and fix it there if required.

see https://github.com/tafia/calamine/issues/326

**Comment by ondohotola** [comment]
Can you provide minimal working examples?

Ie the XLSX and CSV generated by Excel, with a screenshot of the export options.

**Comment by jqnatividad** [comment]
Last year, when I was trying to add streaming transcoding support to qsv using [`encoding_rs_io`](https://github.com/BurntSushi/encoding_rs_io), I didn't have any success adding non-UTF8 test files so I can add test cases in GitHub.  GitHub always changed the encoding to UTF-8.

Any hints on how to add non UTF-8 test files to GitHub would be great.

**Comment by EricSoroos** [comment]
Adding them in a zip file might work, otherwise it's probably git doing it. You might be able to add them with a `.bin` extension, or force git to add the file in binary mode.

**Comment by jqnatividad** [comment]
@EricSoroos closing this now that 0.113.0 has been released.

https://github.com/jqnatividad/qsv/releases/tag/0.113.0

`input` & `validate` now both properly detect and handle non-UTF8 encoded input.

After my failed attempt to do auto-transcoding last year, I think its best to leave that to purpose built tools like iconv and just leverage qsv's composability to depend on the input being transcoded to utf8 beforehand, and just warn if its not.
