### ISSUE TITLE
BUG: qsv diff fails for different delimiters for the left and right CSV files

### ISSUE THREAD

**Issue by a5dur** [jqnatividad/qsv#1258]
**Describe the bug**
qsv diff fails for different delimiters for the left and right CSV files when trying to perform a diff on CSV files with different delimiters.

**To Reproduce**
1. Use two csv files with different delimiters 
2. run qsv diff 

**Expected behavior**

Find the difference between two CSVs.

**Comment by jqnatividad** [comment]
Thanks for the report @a5dur .

For now, as a workaround, I'm thinking of just disabling the delimiter options as users can normalize their CSVs before diffing them.

The original contributor of the `diff` command's GitHub account - @janriemer  seems to be inactive.  Maybe you can report the problem to his gitlab repo where he maintains the css-diff crate this command uses?

https://gitlab.com/janriemer/csv-diff

**Comment by janriemer** [comment]
@a5dur @jqnatividad Thank you for tagging me here and reporting the bug. 👍 

I'll have a look tomorrow and hopefully get a fix out soon. I'll keep you updated here.

Happy that `qsv diff` is actively used! ❤️

**Comment by janriemer** [comment]
@jqnatividad Please assign me to this bug. Thank you.

**Comment by janriemer** [comment]
I can't reproduce the bug. [Neither in `csv-diff`](https://gitlab.com/janriemer/csv-diff/-/commit/0ac6ba724656dbcc620eefda3f8ec5d8064134d6), nor in `qsv diff` (#1297).

@a5dur What exact command are you executing?

Please try to specify the different delimiter in the command options. For example, if your right csv has a different delimiter than `,` (let's say, it is `;`), the command is as follows:

```bash
qsv diff left_csv.csv right_csv.csv --right-delimiter ";"
```

Can you please verify this. Thank you. :slightly_smiling_face:

**Comment by a5dur** [comment]
Hi @janriemer,

Thank you for looking into this🙌. After revisiting the problem, I discovered that it was related to the CSV files I was using for testing this command. Specifically, the delimiter I was using ` ' ` was employed without an escape sequence within one of the rows, and this caused the unexpected behavior. It turns out this occurred in a relatively large file, and I initially overlooked it.

The exact command I was initially executing was as follows:

`qsv diff 'left_csv.csv' 'right_csv.csv' --delimiter-left ; --delimiter-right '`

Upon resolving this, the `diff` operation works flawlessly🎉, producing the expected output without any discrepancies.

🙇🏻I'm sorry for any confusion this may have caused @janriemer @jqnatividad, and I'm glad we found out what was causing it.

**Comment by janriemer** [comment]
@a5dur No worries, you don't need to apologize. 🙂 

Thank you for the elaborate explanation and posting the original command you've executed.
I'm glad you've found the issue and `qsv diff` works well for you. Thank you for the positive feedback! ❤️ 

Also: we now have additional tests in `csv-diff` and `qsv diff` that verify the use with different delimiters, so this is a win for everyone! ✨

**Comment by jqnatividad** [comment]
Hi @janriemer ,
I went ahead and added examples to the usage text.  As it happens, we were talking to a user in Germany and he mentioned he attempted to use `diff` but wasn't sure he was using it correctly.

Hopefully, the examples and "ludicrous speed" description promotes increased usage of `diff`!

**Comment by janriemer** [comment]
@jqnatividad Nice, thank you! ❤️ 

This looks great and having concrete examples is very useful, indeed. 👍 

> and "ludicrous speed" description promotes increased usage of diff!

😄 I'm sure it will! 😉 

------------------------------------------
_Unfortunately, I didn't had time to further work on `diff`, due to other projects I'm currently focused on, but I'll get back to it in the near future._ 🤞

**Comment by ondohotola** [comment]
If it's a language issue he can get in touch with me as I am native
German speaker.

el [at] lisse dot NA
