### ISSUE TITLE
`benchmarks`: Create a new benchmark page now that the benchmark script has been updated

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1296]
As per the title above.

Especially now that the qsv web site is live (https://qsv.dathere.com).

**Comment by rzmk** [comment]
https://qsv.dathere.com/benchmarks

Based on [scripts/results/README.md](https://github.com/jqnatividad/qsv/blob/master/scripts/results/README.md) and [scripts/results/benchmark_results.csv](https://github.com/jqnatividad/qsv/blob/master/scripts/results/benchmark_results.csv).

**Comment by jqnatividad** [comment]
Hi @rzmk ,
First cut looks good!

Here are a few tweaks we should do though, if they're easily configurable with data tables:

- [ ] use [benchmark_results_display.csv](https://github.com/jqnatividad/qsv/blob/master/scripts/results/benchmark_results_display.csv) instead.
As the "_display" suffix suggest, its optimized for display - recs_per_sec follows mean; all floats are rounded to 3 decimal places.
This should get rid of the horizontal scrolling problem and make the benchmarks more readable.
- [ ] set the page size the current number of benchmarks we have - 112. If not possible, set it to 100.
- [ ] change the display format of recs_per_sec to comma-separate the value for readability
- [ ] add a link to the data below the data table right-justified
DATA:  [benchmarks_results.csv](https://github.com/jqnatividad/qsv/blob/master/scripts/results/benchmark_results.csv),[ latest_results.csv](https://github.com/jqnatividad/qsv/blob/master/scripts/results/latest_results.csv), [run_info_history.tsv](https://github.com/jqnatividad/qsv/blob/master/scripts/results/run_info_history.tsv) and [latest_run_info.tsv](https://github.com/jqnatividad/qsv/blob/master/scripts/results/latest_run_info.tsv) 
- [ ] also add a link to the benchmarks.sh shell script below the DATA:..., right-justified
Benchmarks generated using [benchmarks.sh](https://github.com/jqnatividad/qsv/blob/master/scripts/benchmarks.sh)

Thanks!

**Comment by rzmk** [comment]
@jqnatividad can you clarify the page size; do you mean display 112 rows per page?

**Comment by jqnatividad** [comment]
Yes @rzmk . 112 rows if possible, so each page should ideally show all the benchmarks from a run...
As benchmarks-results.csv is a historical archive, it will grow over time and the thinking here is that each page full is a run.

**Comment by rzmk** [comment]
@jqnatividad Okay, also do you still want the section to be right-justified?

![right-align](https://github.com/jqnatividad/qsv/assets/30333942/b043aaf3-c731-43fd-bf9b-3e949de7e8aa)

![left-align](https://github.com/jqnatividad/qsv/assets/30333942/736ff207-53b2-4e19-bea7-9ac8452b26fb)

If so then this issue should be complete.

**Comment by jqnatividad** [comment]
Yes @rzmk . This is largely complete - the minor thing I'd tweak is to make that "data footer" section shorter by not stacking the datasets on top of each other, but rather, next to each other as normal blue links, and removing the Benchmark Datasets title and the "Click on the links..." preceding the two right-justified lines.

**DATA:** [benchmarks_results.csv](https://github.com/jqnatividad/qsv/blob/master/scripts/results/benchmark_results.csv),[ latest_results.csv](https://github.com/jqnatividad/qsv/blob/master/scripts/results/latest_results.csv), [run_info_history.tsv](https://github.com/jqnatividad/qsv/blob/master/scripts/results/run_info_history.tsv) and [latest_run_info.tsv](https://github.com/jqnatividad/qsv/blob/master/scripts/results/latest_run_info.tsv)
Benchmarks generated using [benchmarks.sh](https://github.com/jqnatividad/qsv/blob/master/scripts/benchmarks.sh).

**Comment by rzmk** [comment]
@jqnatividad Changes deployed.
