### ISSUE TITLE
Autoindex size threshold

### ISSUE THREAD

**Issue by plambert** [jqnatividad/qsv#1300]
**Is your feature request related to a problem? Please describe.**
I work with a large number (currently about 90,000) of CSV files.  The vast majority are quite small, less than 3kb.  However, some can be much larger, the largest around 350MB and 4.2 million rows.

If I turn on auto indexing, it improves performance of operations that involve the larger files, but it creates another 90,000 index files.  Without indices, operations are still very quick unless they involve one or more of the large datasets, and then they can be very slow.

**Describe the solution you'd like**
I'd love if I could set `QSV_AUTOINDEX=50000` and it would only autoindex files that are more than 50,000 bytes in size.  This'd only create about 600 index files.

**Describe alternatives you've considered**
I've turned on `QSV_AUTOINDEX` and it has made the performance of many operations much better.  However, there are a lot of tiny index files created that don't seem to help anything at all.

I've also manually run `find . -name '*.csv' -size +50k -print0 | xargs -0 -n 1 qsv index` and this only creates about 900 index files, but performance of the operations I run are almost identical to having every index file in place.  However, I have to manually update this every time a dataset may have changed.

I don't think a threshold size for automatic indices would be very difficult to implement, though I don't know Rust well enough to do it myself.  But this feature would really afford me a happy medium between the two extreme solutions.

**Comment by plambert** [comment]
Made a gist with the script I used to do the manual indexing, in case it's useful to anyone.

https://gist.github.com/plambert/7c6504f852be1e71e2fececea919fb61

**Comment by jqnatividad** [comment]
Thanks for the detailed request @plambert .

This is a great idea!  Though I was thinking of replacing QSV_AUTOINDEX with QSV_AUTOINDEX_SIZE as its clearer.

WDYT?

**Comment by plambert** [comment]
Sorry for the late reply, but for posterity, I think it's a great idea.  :)

**Comment by jqnatividad** [comment]
I'd be interested to know if `QSV_AUTOINDEX_SIZE` is behaving as expected @plambert .

**Comment by plambert** [comment]
Again, sorry to take so long to reply, but it's been great.  Thank you very much!

**Comment by jqnatividad** [comment]
Hi @plambert , do you mind adding a little background on your 90,000 csv qsv use case here?

https://github.com/jqnatividad/qsv/discussions/1529

I'd really appreciate it as we make plans for qsv & qsv pro.

**Comment by plambert** [comment]
Hmm.  How best to describe it?

I have a data source for time-series data that doesn't have an API.  So I pull it via a ruby/selenium script.  Every Monday I run the script, and it downloads the data as CSV files.  I keep the files in their original form, untouched, so that I can start from scratch at any time—sometimes column names change, or other things occur, so I need to be able to easily reprocess it all.  While the CSV files have the first column as "date", the second row starts with "Total" and is the totals for the whole file.  Not very useful!  Also the column titles are horrible, and need to be cleaned up a lot.  Especially because they and the values don't actually match other data sources from the same vendor.  For example, this scraped data might call a product "Product One" and one REST API might call it "ProdOne" and another "prod_1".  So I have to normalize both column names and values.

The majority of the CSV files are small, a few kb.  Some can be several MB.  Common manipulations I have to do are take a part of the filename, and add it as a column.  So adding a 'foo' column to data-bar-2024-01-10.csv which has the value 'bar' from the filename, because there's a dimension in the data that is per report, and not inside the report.  I concatenate them with a custom script because data is repeated, and I need to replace records with the record from the most recently downloaded datafiles.  For example, `2024-01-10,foo,bar,baz,1.0` might be in a datafile downloaded today, and then next week a datafile has `2024-01-10,foo,bar,baz,1.1`.  I need just one record, with the 1.1 value, because the datasets overlap.  I pull 90 days' data every week, since the dataset can change after the fact.  Some data arrives late, other data changes because of other factors.  I need the most-recently downloaded value for every row.

I do all of this with a combination of qsv and custom scripts, and the final reports are produced in Excel.

What sort of edge cases do I run into?  Well, if I put daily data into an Excel table, it's limited to a little over a million rows (1024^2 I think).  So I have to cut off the report to include as many days of data that fits in that row limit.  However, I can't just cut anywhere--I have to have the complete set of data for each day.  Currently, I get the unique set of days, then iterate in reverse, extracting each to a file in a temp directory and counting its size.  When I cross the limit, I delete the most recent file, then concatenate and delete the temp files.

My final dataset is put into a sqlite database.  It's not super fast, but it's very flexible.  Although I think I have either encountered some bugs, or exceeded my own skills.  So I again use a custom script to generate delta info.

For example, if I have `2024-01-01,foo,bar,baz,1.0` and `2024-01-02,foo,bar,baz,1.1` I want to add a column to every row with the difference from the previous day's value for the same dimensions.  So in the second case, it'd become `2024-01-02,foo,bar,baz,1.1,0.1` showing that there was a 0.1 increase from the previous day's value.  I use a custom script to read all the data into memory into a big data structure, then iterate through the dates with the trailing and current date, iterate on every record for the current date, do a lookup of both values, and add the delta to the current date.  If the trailing date's record doesn't exist, I record the delta as 0.  It's appropriate for my use case.

Things I can't do in qsv, though I am not saying I should be able to do them, because I have no idea how many other people might want to do them...

1. Take a CSV lookup file with `value,canonical_value` and change every value in a particular column that is found in the lookup's value column, with the canonical_value.  For example, `Pepsi,cola` and `Coke,cola` in the lookup would allow every instance of exactly Pepsi or Coke in the selected column of the datafile be normalized to "cola".   Case sensitivity would not matter for me, but maybe for others.  In addition to the lookups, being able to apply a regex and replacement string from the lookup file rather than a separate invocation of `qsv replace` would be helpful.
2. Strip a trailing newline.  When pasting a tsv into Excel, if the last line ends in a newline, then Excel creates a blank row.  I have to strip that pesky newline, even though it really should be there.  I've written a csv2tsv script that does this, while also converting to tsv.  But an option to qsv fmt to not emit a newline after the final line, and clear documentation that this is how you make pasting a tsv into Excel easy, would be very helpful.  (as an aside: `perl -nE 'chomp; print "\n" if $. > 1; print'` does a good job of stripping a final newline... it'd be way faster in qsv of course...)
3. Simple aggregations.  If I have headers `date,keyname,lockname,doorname,cost` and want to spit out a new csv with `date,keyname,lockname,cost` that aggregates(sums) the cost... basically like a pivot table in Excel, if you're familiar.  Or a sql statement with 'sum(cost)' and 'group by'.
4. Support for SQLite and maybe other SQL databases.  It's trivial to load a CSV file into a sqlite file, but it's less trivial to load several into different tables in the same database, and being able to just pipe a series of qsv manipulations into something like `qsv sql --sqlite ./data.db --replace-table dataset` and have it do the "heavy lifting" would be great.
5. Many of the things that a pivot table can/could do, would be useful in qsv.  Especially because there are a lot of features of Excel pivot tables only available in the Windows version, so they're not useful for those using MacOS.  PowerQuery, for example.  I'd love to be able to say `qsv pivot -s date,keyname,lockname -sum cost file.csv > newfie.csv` and have it do the aggregation I mentioned above.  But even better would be saying `qsv pivot -s date,keyname,lockname --eval "100 * sum(cost) / sum(cost - delta)" --as cost datafile.csv > newfile.csv` though of course, the key would be documentation.
6. Documentation.  What does `qsv apply` do?  Why is it a handful of different things, none of which are obvious from the name?  I am not criticizing--it's obvious why and how the tool arrived to where it is now, in terms of organization and design.  But the learning curve is very high.  There needs to be a lot more documentation from the perspective of "how do I do X..." and the commands could be reorganized to be easier to learn.  In addition, it'd be good to take common use cases that are possible with one command, and make a specific command to do them as well.  `qsv tsv file.csv` should convert file to tsv format.  Sure, `qsv fmt` can do it... but someone who needs a tsv file will be looking for `tsv`.

Other random info, that probably isn't helpful:

When I say "custom script", it's probably in bash, perl, or crystal (https://crystal-lang.org/).  The first is great for just stringing commands together.  The second is great for quick scripts, though my script to calculate the deltas is in perl.  The latter is great for speed and memory usage, since it's a statically typed, compiled language.  I've been tempted on occasion to write my own variant of qsv in crystal, just for fun.  But it quickly stops being fun--to get anywhere near a useful subset of qsv's features would take a huge amount of time, as you obviously know.  :)

Anyway, that's my stream-of-consciousness dump.  I hope it's helpful in some way.
