### ISSUE TITLE
Create a `qsv` tutorial?

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1332]
### Discussed in https://github.com/jqnatividad/qsv/discussions/1189

<div type='discussions-op-text'>

<sup>Originally posted by **rickhg12hs** August  4, 2023</sup>
Is there a `qsv` tutorial that shows very basic operations, i.e., something that shows a newcomer how to use `qsv` to do very basic operations?

For example:
* selecting certain columns from a CSV file.
* specifying the field separation character(s)/regex
* concatenating multiple CSV files
* modifying columns of a CSV file (e.g., concatenating strings, simple math involving multiple columns, format changes)
* etc.

A tutorial for more advanced operations (if they exist) may be useful, as well.

For example:
* input from irregular CSV files
* variable assignment (for later use) from input of irregular CSV file (e.g., header line has values needed to modify following columns)
* etc.
</div>

Could also leverage https://github.com/jqnatividad/qsv/issues/1307, so we can get the latest usage text in the tutorial, perhaps, making it even interactive using the qsv website.

Perhaps, the tutorial can even be linked from the qsv website as well - making it a "living" tutorial.

cc @rickhg12hs @rzmk

**Comment by rzmk** [comment]
This seems possible with a single Jupyter Notebook and an "Open in Colab" badge too.
