### ISSUE TITLE
allow static musl binaries to include luau and/or sqlp

### ISSUE THREAD

**Issue by terefang** [jqnatividad/qsv#1362]
**Is your feature request related to a problem? Please describe.**
currentliy static musl binaries are build without luau and sqlp support

**Describe the solution you'd like**
include luau and sqlp support in static musl binaries

**Describe alternatives you've considered**
none

**Additional context**
this addition to github actions is used by bazeltools to build static deps.
https://github.com/bazeltools/bzl-gen-build/pull/81/files

**Comment by jqnatividad** [comment]
Thanks for the pointer to bazeltools @terefang. Not for a lack of trying, but previous attempts have failed.

**Comment by terefang** [comment]
unfortunately i am less than a n00b at rust. but i really like what i see in "qsv"

**Comment by terefang** [comment]
unfortunately i am less than a n00b at rust. but i really like what i see in "qsv"

**Comment by jqnatividad** [comment]
Hi @terefang , I managed to get `sqlp` and `joinp` (enabled by the polars feature) on must on 0.117.0.

However, luau won't compile because it needs gnu libraries.

**Comment by terefang** [comment]
from the error it looks like you compile with a gnu toolchain and then link with a musl one, but i dont understand the buildprocess of rust.

**Comment by terefang** [comment]
sorry this is not my area of competence

**Comment by terefang** [comment]
did you look here ? https://crates.io/crates/cc/

**Comment by terefang** [comment]
hello sqlp gone again from musl static 0.118 and up ?

**Comment by jqnatividad** [comment]
Ooopsss... forgot to update the musl publish workflow to account for the zipsigning of archives. I just updated it and the musl variants with luau and polars (sqlp and joinp) features is now available.

**Comment by terefang** [comment]
thanks

**Comment by terefang** [comment]
oh ... sorry was using the non-"-musl-1.2.3" version

many thanks

keep up the good work !
