### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by terefang** [jqnatividad/qsv#1370]
**Describe the bug**
i am getting the following error with sqlp

```
Failed to execute query: select DATE(Timestamp),SiteId,SLAClass as Profile,Appliance as HostName,0 as Speed_kbps,Network as InterfaceName,"BW Utilization Received BW-RX_bps" as in_bps,"BW Utilization Transmitted BW-TX_bps" as out_bps, "Round Trip Time (Delay)" as latency_ms  from IBM_InterfaceStats_20230713 where SiteId != '' and Network != ''
: invalid operation: unsupported SQL function: date
```

**Expected behavior**
looking here a DATE function exists

https://github.com/pola-rs/polars/blob/34d42c6dec6bb41889101bc758b0a4fe6419d4d0/crates/polars-sql/src/functions.rs#L228

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - qsv Version 0.117.0

**Comment by jqnatividad** [comment]
@terefang ,
The DATE function was just added two days ago
https://github.com/pola-rs/polars/commits/34d42c6dec6bb41889101bc758b0a4fe6419d4d0/crates/polars-sql/src/functions.rs

and we're on the latest Rust Polars at 0.33.2 which was released last month.

The SQL functions available with `sqlp` are the ones available at the time, mid-September
https://github.com/pola-rs/polars/blob/7f8cd7dbd6bc09a21a99c13020fbac8cfdd4aa90/crates/polars-sql/src/functions.rs

FYI, Polars has a very fast release tempo for python-polars, with a release every few days. In contrast, rust-polars is released about once a month.

Will update the links in `sqlp`'s usage text to ensure that we point to the available functions at the time of release.

**Comment by terefang** [comment]
thx for pointing that out

**Comment by jqnatividad** [comment]
@terefang , the DATE function will now work with the upcoming release of 0.118.0

**Comment by terefang** [comment]
+1

**Comment by jqnatividad** [comment]
Hi @terefang , I'd really appreciate it if you can add some background info on how you're using qsv here

https://github.com/jqnatividad/qsv/discussions/1529

Thanks in advance!
