### ISSUE TITLE
add `template` command

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1374]
For each row in a CSV, fill out a specified minijinja template with corresponding columns, and send the output to a file, whose filename can also be dynamically generated using  CSV data.

Extend the minijinja template with the ability to execute qsv's Luau DSL so we can do additional stuff like complex expressions, lookups, conditional filtering and dynamic content while populating a template.

Use minijinja crate - https://github.com/mitsuhiko/minijinja#readme

**Comment by ondohotola** [comment]
Currently I can't compile as it requires rust 1.73 and the Mac/Homebrew
only has 1.72.

el

**Comment by jqnatividad** [comment]
The `template` command can also be used to fill out a DCAT3 metadata profile.
