### ISSUE TITLE
Can't compile qsv 0.117.0 as it requires rust 1.73 & Homebrew has 1.72.1

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1375]
Currently I can't compile as it requires rust 1.73 and the Mac/Homebrew
only has 1.72.

el

_Originally posted by @ondohotola in https://github.com/jqnatividad/qsv/issues/1374#issuecomment-1770717129_

**Comment by jqnatividad** [comment]
Hi @ondohotola,
That is correct.  Please see qsv's latest MSRV policy - https://github.com/jqnatividad/qsv#minimum-supported-rust-version

I do try to wait a week after a Rust stable release to give Homebrew maintainers time to package Rust stable, but if more than a week passes by, I go ahead with the MSRV upgrade.

Hopefully, this adds a nudge, however little, for the HB maintainers to update their Rust formula to the latest Rust stable - https://github.com/Homebrew/homebrew-core/pull/149754.

The HB maintainers are really very good with keeping Rust and qsv formulas up to date, it's just that updating formulas, especially for big packages like Rust is non-trivial.

See [Goals/Non-Goals](..#goals--non-goals)

**Comment by jqnatividad** [comment]
There is an issue upstream in Rust that's preventing Homebrew from compiling v 1.73.0 on 12-arm

https://github.com/rust-lang/rust/issues/117299

**Comment by ondohotola** [comment]
Thanks

**Comment by chenrui333** [comment]
FYI, rust 1.74.0 got shipped in the homebrew side now, https://github.com/Homebrew/homebrew-core/pull/154526

**Comment by jqnatividad** [comment]
Awesome, been holding off on releasing qsv 0.119.0 till this is resolved.

Releasing it now... :)

**Comment by ondohotola** [comment]
Patience is a Virtue :-)-O

Thanks
