### ISSUE TITLE
qsv dedup -i sometimes missing duplicate rows

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#1381]
Given the following two files (simplified as much as I can from a problem I've encountered with much bigger files):

`data1.csv`:
```csv
office
Member of legislative assembly
Member of Legislative Assembly
```

and `data2.csv`:
```
office
Member of legislative assembly
Member of Legislative Assembly
Member of Tamil Nadu Legislative Assembly
```

`qsv dedup -Qi data1.csv` correctly returns a single result:

```
office
Member of legislative assembly
1
```
but adding a single extra row to the second file seems to confuse things somewhere, such that `qsv dedup -i data2.csv` no longer believes the first two rows are duplicates:

```
office
Member of legislative assembly
Member of Legislative Assembly
Member of Tamil Nadu Legislative Assembly
0
```

I get the same results with both the latest homebrew version (qsv 0.116.0-mimalloc-apply;Luau 0.596;-8-8;12.80 GiB-942.62 MiB-0 B-16.00 GiB (aarch64-apple-darwin compiled with Rust 1.72.1) compiled) and a freshly downloaded prebuilt verison (qsv 0.117.0-mimalloc-apply;fetch;foreach;generate;geocode;Luau 0.599;to;polars-0.33.2;self_update-8-8;12.80 GiB-958.62 MiB-0 B-16.00 GiB (aarch64-apple-darwin compiled with Rust 1.73.0) prebuilt)

**Comment by jqnatividad** [comment]
Thanks for the detailed report @tmtmtmtm .

I can confirm this is a bug.

While I fix it, you can use this workaround for now:

```
qsv sort -i data2.csv | qsv dedup -i --sorted          
office
Member of legislative assembly
Member of Tamil Nadu Legislative Assembly
1
```

**Comment by jqnatividad** [comment]
Hi @tmtmtmtm , lemme know how this works for you.

Note that it will use the last lowercase variant it sees in the result.
