### ISSUE TITLE
BUG Build failed on Fedora 39 with GCC 13.2.1

### ISSUE THREAD

**Issue by zamazan4ik** [jqnatividad/qsv#1431]
**Describe the bug**
`qsv` build failed on Fedora 39 with the following error: https://gist.github.com/zamazan4ik/bf8c9bbe3aaddbdf76a7e2ffc11aa79a

**To Reproduce**
1. Checkout QSV
2. Try to compile with `cargo build --release --locked -F feature_capable,apply,geocode,luau,to,polars --bin qsv`
3. See error

**Expected behavior**
QSV compiles successfully.

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - qsv Version: `master` branch on commit `b6d39762c62ca520aa7abb63dfe5a83fade0a24a`
 - `c++ --version`: GCC 13.2.1 (the default compiler from Fedora repos)
 - Rustc version: 1.74

**Comment by jqnatividad** [comment]
Thanks for the report @zamazan4ik ,

Have you tried compiling it without the `luau` feature?

What about compiling it with just the `luau` feature? That is:

`cargo build --release --locked -F feature_capable,luau`

I'm afraid I don't have access to Fedora 39... my daily driver is macOS Sonoma on M2, and I deploy primarily on Ubuntu 22.04 LTS where it compiles successfully.

What about the prebuilts? Have you tried them? Have you tried compiling using musl?

**Comment by zamazan4ik** [comment]
> Have you tried compiling it without the luau feature?

Yes, I tried. Forgot to mention it - without `luau` feature it compiles successfully (since we get errors in building Lua as a dependency - it's expected, I guess).

> I'm afraid I don't have access to Fedora 39... my daily driver is macOS Sonoma on M2

Yep, I also tested it on my M1 machine - it compiles fine. The error seems like is only triggered with one of the newest GCC toolchain (Fedora always has one of the most up-to-date compilers).

> What about the prebuilts? Have you tried them?

They are not suitable for me since I want to perform Profile-Guided Optimization (PGO)-optimization over `qsv`.

> Have you tried compiling using musl?

Could you please give me a command for compiling qsv with the Musl library? I can check it. But according to the error - it shouldn't help since it with a 99.999% probability due to missing C headers in the Lua dependency due to some internal libstdc++ changes with newer GCC.

**Comment by jqnatividad** [comment]
Looking at the error message again, it says you're compiling 0.118.0.  Have you tried compiling 0.119.0?

As for compiling with musl, I only how to do it on Ubuntu, issuing the following, before compiling qsv.

```
 sudo apt-get install musl-tools musl-dev
 sudo ln -s /usr/bin/g++ /usr/bin/musl-g++      
```

**Comment by zamazan4ik** [comment]
> Looking at the error message again, it says you're compiling 0.118.0. Have you tried compiling 0.119.0?

I just checked out the `master` branch on commit `531acbb072c48cbaca5d58b593243e0f5f0ec8d3` (the version is 0.119 in Cargo.toml) - nothing has changed, the error is the same.

**Comment by jqnatividad** [comment]
Have you tried installing these packages and compiling?

https://packages.fedoraproject.org/pkgs/musl/

**Comment by zamazan4ik** [comment]
> Maybe start with musl-gcc and musl-devel...

I installed them but Fedora does not provide `musl-g++`, only `musl-gcc`. Is there a way (maybe a one-liner) to use `musl-gcc` as `musl-g++`?

**Comment by jqnatividad** [comment]
Have you tried specifying the target?

`cargo build --release --locked -F feature_capable,apply,geocode,luau,to,polars --bin qsv --target x86_64-unknown-linux-musl`

**Comment by zamazan4ik** [comment]
The error is the same

**Comment by jqnatividad** [comment]
Sorry... don't have any more idears... If you do manage to compile qsv with luau on Fedora 39, please do update this issue...

**Comment by alerque** [comment]
Similar issues on Arch Linux. I haven't been able to bump the package from 0.118.0 as a result.

We were previously using `clang` for this build, but neither that nor `gcc` are working now.

**Comment by jqnatividad** [comment]
Thanks for the additional data point @alerque 

Will see if I can spin up Fedora 39 and Arch Linux VMs during the long Thanksgiving weekend to see what's causing the issue.
