### ISSUE TITLE
BUG missing "to postgres" with 119

### ISSUE THREAD

**Issue by SprickW** [jqnatividad/qsv#1449]
---
**Describe the bug**
Downloaded qsv-0.119.0-x86_64-unknown-linux-gnu and it seems to miss "to postgres".

**To Reproduce**
1. download
2. unzip
3. make executable
4. run (also with --help and --list not showing missed function)

**Expected behavior**
"to postgres" works as described

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - qsv Version: 199

**Comment by jqnatividad** [comment]
Thanks for the report @SprickW ,

Yes. I was forced to choose `polars` over the `to` feature when publishing the qsv prebuilt variant for x86_64-unknown-linux-gnu as GitHub's Action Runners were too small and the build was running out of space.

But that was a while ago, and the underlying dependencies of `to` and the polars commands have been updated - so I'm currently testing if I can reenable it.

Will let you know if it works.  And if it does, I'll republish the 0.119.0 binaries.

**Comment by jqnatividad** [comment]
Glad to report that the `to` and `polars` features seem to play nice now and can be enabled together.

https://github.com/jqnatividad/qsv/actions/runs/7089125354

Re-publishing the prebuilt archives for 0.119.0...

**Comment by jqnatividad** [comment]
@SprickW , the updated prebuilt archive for x86_64-unknown-linux-gnu is now available.

https://github.com/jqnatividad/qsv/releases/tag/0.119.0

I'm still building the nightly versions, but if you're not using nightly, then you should be good to go.
