### ISSUE TITLE
Create another prebuilt binary variant - qsvpy

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1451]
`qsvpy` - as the name implies, will have the Python feature enabled.

Due to packaging issues, we stopped enabling the python feature by default in the pre-built binaries as it was causing distribution issues, as Python is dynamically linked and will require that the right version be installed for it to work.

That is - if qsv is invoked in an environment that does not have the specific Python version libraries available at runtime, it will abort immediately **even if you're not using the `py` command.**

However, even if Luau can run circles around Python as qsv's DSL, it still remains that Python is the lingua franca of Data Wrangling.

So let's reintroduce `qsvpy` once again - with the proviso that it will only be built for the latest stable Python version, and its up to the user to build from source if they want to build qsv with an older version of Python.

**Comment by terefang** [comment]
please observe that python 3.12.0 is not really stable

**Comment by jqnatividad** [comment]
In the next release, we'll now also build qsvpy310, qsvpy311 and qsvpy312, with each having the latest patch version (i.e. python 3.10.13, 3.11.7 & 3.12.1)

**Comment by terefang** [comment]
can you say anything about usability in a python3.11 venv under RHEL8 ? or RHEL9 ?

**Comment by jqnatividad** [comment]
I don't have access to RHEL 8 nor 9, but it *should* work.

RHEL 9 apparently defaults to python 3.9, with ready upgrade path to 3.11

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/installing_and_using_dynamic_programming_languages/assembly_installing-and-using-python_installing-and-using-dynamic-programming-languages
