### ISSUE TITLE
apply dynfmt --formatstr won't access data

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#1458]
I'm having difficulty getting `qsv apply dynfmt` to combine, or even access, columns.

Given a `file.csv` of:

```csv
FirstName,MI,LastName
Adam,B,Case
Derek,E,Foster
Gordon,H,Irvin
Jack,K,Lynch
```

The example from the docs of `qsv apply dynfmt --formatstr 'Sir/Madam {FirstName} {MI}. {LastName}' -c FullName file.csv` is simply setting the new column to FirstName rather than the concatenation:

```csv
FirstName,MI,LastName,FullName
Adam,B,Case,Adam
Derek,E,Foster,Derek
Gordon,H,Irvin,Gordon
Jack,K,Lynch,Jack
```

If I make the format string something entirely static, e.g. `qsv apply dynfmt --formatstr 'Sir/Madam' -c FullName file.csv` then that works:

```csv      
FirstName,MI,LastName,FullName
Adam,B,Case,Sir/Madam
Derek,E,Foster,Sir/Madam
Gordon,H,Irvin,Sir/Madam
Jack,K,Lynch,Sir/Madam
```

but as soon as I include any column at all it reverts to only including the FirstName: e.g. `qsv apply dynfmt --formatstr '{MI}' -c FullName file.csv`:

```csv
FirstName,MI,LastName,FullName
Adam,B,Case,Adam
Derek,E,Foster,Derek
Gordon,H,Irvin,Gordon
Jack,K,Lynch,Jack
```

The same problem also seems to apply with calcconv: `qsv enum file.csv | qsv apply calcconv --formatstr '{index} * {index}' -c result`:

```csv
FirstName,MI,LastName,index,result
Adam,B,Case,0,ERROR: Lexing error: Invalid string: adam
Derek,E,Foster,1,ERROR: Lexing error: Invalid string: derek
Gordon,H,Irvin,2,ERROR: Lexing error: Invalid string: gordon
Jack,K,Lynch,3,ERROR: Lexing error: Invalid string: jack
```

I've tested this with `qsv 0.119.0-mimalloc-apply;fetch;foreach;generate;geocode;Luau 0.604;to;polars-0.35.4;self_update-8-8;12.80 GiB-909.19 MiB-0 B-16.00 GiB (aarch64-apple-darwin compiled with Rust 1.74.0) prebuilt` (freshly downloaded) and `qsv 0.116.0-mimalloc-apply;Luau 0.596;-8-8;12.80 GiB-909.19 MiB-0 B-16.00 GiB (aarch64-apple-darwin compiled with Rust 1.72.1) compiled` from homebrew.

**Comment by jqnatividad** [comment]
Good catch @tmtmtmtm !

Interestingly, it only happens on the release version of qsv, and it works as expected with a debug build as you can see from the test using your example.

I'll have to dig into this a little to see what is causing Rust to optimize away dynfmt's functionality in a release build.

**Comment by jqnatividad** [comment]
And as you found out, its the same with `calcconv` - works in debug build, but not in release...
