### ISSUE TITLE
CSV file debugging and troubleshooting tool

### ISSUE THREAD

**Issue by SoftTools59654** [jqnatividad/qsv#1461]
CSV file debugging and troubleshooting tool

In some files, the number of (,) is incorrect, which causes A tool that sets the number ( , ) in all rows to the same number even if there is no data

For example, the mentioned levels ( , ) are less

 CSV

>  Species , BodyWeight , BrainWeight , Grams  ,
>  MountainBeaver , Quantity 1.35   KiloGrams  ,    Quantity 8.1,   Grams  ,    
 **Cow , Quantity 465,   KiloGrams  ,**    
>  GreyWolf , Quantity 36.33   KiloGrams  ,    Quantity 119.5,   Grams  ,    
>  Goat , Quantity 27.66   KiloGrams  ,     Quantity 115,   Grams  ,    
**GuineaPig , Quantity 1.04,   KiloGrams  ,**

**Comment by SoftTools59654** [comment]
I need to convert my csv files in another tool to have a standard csv file
Not that there are few lines in some lines
There should be at least as many headers in each row as there are in other rows, but it is not possible to find such an error manually in data that has several million records.

The above standard should be in the following form and a few should be added to this

CSV

Species , BodyWeight , BrainWeight , Grams ,
MountainBeaver , Quantity 1.35 KiloGrams , Quantity 8.1, Grams ,
Cow , Quantity 465, KiloGrams , **,**
GreyWolf , Quantity 36.33 KiloGrams , Quantity 119.5, Grams ,
Goat , Quantity 27.66 KiloGrams , Quantity 115, Grams ,
GuineaPig , Quantity 1.04, KiloGrams , **,**

**Comment by jqnatividad** [comment]
Have you tried `qsv fixlengths`?

**Comment by SoftTools59654** [comment]
It was my mistake, I didn't pay enough attention, the problem was solved

Thank

 **qsv  fixlengths  -l 5 2.csv -o 3.csv**
