### ISSUE TITLE
BUG  `to_parquet` feature disabled.

### ISSUE THREAD

**Issue by SoftTools59654** [jqnatividad/qsv#1462]
Is it no longer possible to convert to Parquet file?

I could not convert the file with the command below

Let me know if the order is wrong

**qsv to parquet test 1.csv**

``to_parquet` feature disabled. `to parquet` subcommand not available.`

**Comment by jqnatividad** [comment]
@SoftTools59654, that is correct.  This is not a bug, and was done intentionally.

The `to parquet` feature is off by default in the prebuilt binaries as GitHub's action runners were running out of space when linking with all the features enabled. See [Features](https://github.com/jqnatividad/qsv/blob/master/docs/FEATURES.md) for more details.

You can build from source if you want to enable the `to_parquet` feature.

```
# build with all features enabled, including to_parquet`
cargo build --release --locked -F all_features

# or build with just the to and to_parquet features enabled specifically
cargo build --release --locked -F feature_capable,to,to_parquet

```

**Comment by jqnatividad** [comment]
BTW, you can also try using `sqlp` to convert a CSV to parquet, e.g.

`qsv sqlp "Select * from _t_1" --format parquet data.csv --output data.parquet`
