### ISSUE TITLE
regex_replace to empty string?

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#1469]
I'm struggling to work out how to set the `--replacement` value of a `regex_replace` to nothing.

`qsv apply operations regex_replace name -C ' \([^)]+\)' -R '' data.csv` gives the error: `usage error: --comparand (-C) and --replacement (-R) are required for regex_replace operation` suggesting that it's not differentiating between -R being entirely missing, and it being explicitly passed an empty string. 

I haven't been able to find very much documentation on `regex_replace`, but I'm not seeing anything more general in the docs about what else could be passed to `--replacement` instead, so I'm not sure if resolving this might just be about adding something to the docs, but it would be useful if -R could handle an empty string.

**Comment by jqnatividad** [comment]
Hi @tmtmtmtm ,

You're right, I didn't account for the empty replacement.

**Comment by tmtmtmtm** [comment]
Great, thanks!

**Comment by opax** [comment]
It seems there has been a regression on this issue. With homebrew-installed qsv 22.0.1, I get:

```
> printf 'col\na' | qsv apply operations regex_replace --comparand . --replacement '' col
usage error: --comparand (-C) and --replacement (-R) are required for regex_replace operation.

> printf 'col\na' | qsv apply operations regex_replace --comparand=. --replacement= col
usage error: --comparand (-C) and --replacement (-R) are required for regex_replace operation.

> printf 'col\na' | qsv apply operations regex_replace --comparand . --replacement '<EMPTY>' col
col
<EMPTY>
```

Also, the special value `<EMPTY>` is not mentioned any longer in `qsv apply --help`. I only tried that variant because I had a look at the pull request that initially solved this issue.
