### ISSUE TITLE
BUG `to` command is not available

### ISSUE THREAD

**Issue by dalisoft** [jqnatividad/qsv#1573]
**Describe the bug**
`to` command is not available

**To Reproduce**
1. Install `qsv` on macOS via `brew install qsv`
2. Run `qsv to`

**Expected behavior**
Working functionality?

**Actual behavior**
```
Could not match 'to' with any of the allowed variants: ["apply", "behead", "cat", "count", "dedup", "describegpt", "diff", "enum", "excel", "exclude", "explode", "extdedup", "extsort", "fill", "fixlengths", "flatten", "fmt", "frequency", "headers", "help", "index", "input", "join", "jsonl", "luau", "partition", "pseudo", "rename", "replace", "reverse", "safenames", "sample", "schema", "search", "searchset", "select", "slice", "snappy", "sniff", "sort", "sortcheck", "split", "stats", "table", "transpose", "tojsonl", "validate"]
```

**Screenshots/Backtrace/Sample Data**
<img width="857" alt="image" src="https://github.com/jqnatividad/qsv/assets/3511344/c0360eaf-8804-4da5-ba79-0664662e6755">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.3
 - qsv Version `0.122.0-mimalloc-apply;Luau 0.606;-8-8;12.80 GiB-882.88 MiB-939.84 MiB-16.00 GiB (aarch64-apple-darwin compiled with Rust 1.75.0) compiled`

**Additional context**
Trying to achieve functionality `qsv to xlsx data xlsx` as described in README

**Comment by jqnatividad** [comment]
Hi @dalisoft ,

Homebrew, I'm afraid, does not enable the `to` feature. It only enables the `apply` and `luau` features.

I added a note in the Installation Section.

BTW, my daily driver is also macOS. You should try the `aarch64-apple-darwin.zip` prebuilts. I optimized them with CPU optimizations for Apple Silicon and they run `blazingly-fast`.

https://github.com/jqnatividad/qsv#option-1-download-prebuilt-binaries

**Comment by dalisoft** [comment]
@jqnatividad Thank you for reply. 
Can i ask, why Homebrew does not support all features? There any limitations?

**Comment by ondohotola** [comment]
I think that has something to do with the way githib automates the
generation of binaries.

Do something like this:

   brew upgrade rust
   cargo install qsv --locked --features \
      apply,luau,fetch,foreach,to,polars,feature_capable
   ln -fs $HOME/.cargo/bin/qsv /usr/local/bin/

I go that in a function and whenever it is upgraded I run it, no drama.

el

**Comment by ondohotola** [comment]
I think that has something to do with the way githib automates the
generation of binaries.

Do something like this:

```
brew upgrade rust
cargo install qsv --locked --features \
   apply,luau,fetch,foreach,to,polars,feature_capable
ln -fs $HOME/.cargo/bin/qsv /usr/local/bin/
```

I go that in a function and whenever it is upgraded I run it, no drama.

**Comment by jqnatividad** [comment]
@dalisoft , that's really a choice of the package maintainer. If you want the Homebrew flavor of qsv to have other features, you can go ahead and create a pull request for the qsv formula.

https://github.com/Homebrew/homebrew-core/blob/7d4e80eae8a78aa56bd7df55be9931ad83d78c06/Formula/q/qsv.rb

Originally, it didn't have any features and I actually managed to get them to accept the `apply` and `luau` features.

And as per @ondohotola , you can just install/compile from source like his example.

You can even get Rust from the source instead of using the brew flavor of rust, which often lags the Rust release cycle.

`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Comment by dalisoft** [comment]
Thank for your detailed response @jqnatividad
