### ISSUE TITLE
Split based on maximum file size

### ISSUE THREAD

**Issue by BeanBagKing** [jqnatividad/qsv#1609]
**Is your feature request related to a problem? Please describe.**
I'm working with large CSV files that often need to be split into chunks no larger than X size (e.g. max file size 1024 MB) for file transfer. The amount of data in each column varies wildly, so taking a 10 gb file and splitting it into 10 chunks doesn't usually work. One file may end up being significantly over 10gb, and others may be significantly under. Same with splitting by the number of lines. I could split it into more chunks, until the largest is below 1gb, but that requires some trial and error at best and I'm trying to optimize this process. In my case at least, the order of the lines does not have to remain the same.

**Describe the solution you'd like**
Add an option, maybe --filesize 1024MB that would split a file into as many chunks as necessary without any being larger than the give size.

**Describe alternatives you've considered**
The following one-liner does what I want, more or less, but it's not the fastest process. Replace both instances of InFile.csv with your file. There's no application I've been able to find that does this though.

`tail -n +2 InFile.csv | split -C 1000MB -d - --filter='sh -c "{ head -n1 InFile.csv ; cat; } > $FILE.csv"'`

**Additional context**
Apologies if this exists, I looked in https://github.com/jqnatividad/qsv/blob/master/src/cmd/split.rs#L2 and search the Issues for similar suggestions, but didn't see any.

**Comment by jqnatividad** [comment]
Hi @BeanBagKing ,
Thanks for the detailed feature request.

I can certainly see the utility of splitting by filesize, especially for files with "free text" columns that really make for highly variant record lengths.

Will put it in the backlog.

**Comment by jqnatividad** [comment]
@BeanBagKing , implemented the `--kb-size` option.

Let me know if it works for you.
