### ISSUE TITLE
more options for apply datefmt

### ISSUE THREAD

**Issue by terefang** [jqnatividad/qsv#1614]
**Is your feature request related to a problem? Please describe.**

allow the `apply datefmt` to specify input and output timezone and allow `UTC` and `Zulu` format styles

**Describe the solution you'd like**

`$ qsv apply datefmt 'Timestamp' --timezone 'Europe/Vienna'` — should interpret timezone-less input in 'Europe/Vienna' and use 'Europe/Vienna' for output

`$ qsv apply datefmt 'Timestamp' --input-timezone 'US/Chicago' --output-timezone 'Europe/Vienna'` — should interpret timezone-less input in 'US/Chicago' and use 'Europe/Vienna' for output.

`$ qsv apply datefmt 'Timestamp' --utc` — shorthand for `--timezone 'UTC'`

`$ qsv apply datefmt 'Timestamp' --zulu` — shorthand for `--output-timezone 'UTC' --formatstr "%Y-%m-%dT%H:%M:%SZ"`

**Describe alternatives you've considered**

importing/exporting to/from sqlite with sql based conversion

**Comment by jqnatividad** [comment]
As `apply` does other things other than `datefmt`, it'd be easier to just pull it out as a separate dedicated command like we did with `geocode`, which used to be an `apply` subcommand.

The new command will be `datefmt`.

**Comment by terefang** [comment]
omg ... you implemented this so quickly !

will try it out as soon as it is in release
