### ISSUE TITLE
more options for enum

### ISSUE THREAD

**Issue by 13minutes-yt** [jqnatividad/qsv#1630]
**Is your feature request related to a problem? Please describe.**
upon using enum, the index starts at zero with index as header. if I use -n the header name is 0 and the indexing works; I will have to rename the header from 0 to index for example an extra step.

**Describe the solution you'd like**
I would like an option whereby I can have indexing starts from 1 with header index, and the column on the left side. I am currently using nl in linux but qsv will be faster.

**Comment by jqnatividad** [comment]
@13minutes-yt this is a quick one. Let me know if the `--start` option meets your reqts.

**Comment by 13minutes-yt** [comment]
works great. yet the index column better be on the leftmost column place in the csv file not on far right by default if it is possible. I have workaround with the select tool but to have this option inside enum is optimal
