### ISSUE TITLE
Validate: improve performance

### ISSUE THREAD

**Issue by mhuang74** [jqnatividad/qsv#164]
Validate currently runs under a single-thread and could become a bottleneck for data validation pipelines.

* Would like to improve performance through higher concurrency
* ~~Concurrency should be controlled via `--jobs` option or `QSV_MAX_JOBS` env var~~
* ~~Concurrency should not exceed CPU count~~
* ~~When _jobs_ is set to 0, apply same rules as `stats` to calculate optimal concurrency~~
* Use Rayon to automatically control concurrency
* Include __validate__ performance numbers in performance suite

```
$ head -50000 NYC_311_SR_2010-2020-sample-1M.csv > NYC-short.csv
$ qsvlite index NYC-short.csv
$ time qsvlite schema NYC-short.csv --value-constraints --enum-threshold=25
Schema written to NYC-short.csv.schema.json

real	0m6.941s
user	0m12.050s
sys	0m3.960s
$ time qsvlite validate NYC-short.csv NYC-short.csv.schema.json 
[00:00:08] [==================== 100% validated 49,999 records.] (6,015/sec)
0 out of 49,999 records invalid.

real	0m8.424s
user	0m8.202s
sys	0m0.128s
```

**Comment by jqnatividad** [comment]
Awesome!

BTW, while I was revamping qsv's benchmarks last year, i found [cargo-flamegraph](https://github.com/flamegraph-rs/flamegraph) very useful in quickly finding the hotspots to focus tuning.  You may want to check it out.

**Comment by mhuang74** [comment]
@jqnatividad  I played around with Rayon instead of using threadpool, which seems unmaintained. Please let me know your thoughts.

https://github.com/jqnatividad/qsv/pull/170

**Comment by jqnatividad** [comment]
@mhuang74 , indeed, rayon is the current goto crate for parallelism.  Last year, I was thinking of enabling parallelism on other commands but I also found threadpool support lacking.

Let's go with rayon, and migrate the other commands to it over time so we can remove the threadpool dependency.

**Comment by mhuang74** [comment]
Thanks @jqnatividad. Follow-up PR to mainly fix `--fail-fast` panic.

https://github.com/jqnatividad/qsv/pull/171

**Comment by jqnatividad** [comment]
Merged! Just in time for this week's release...

**Comment by mhuang74** [comment]
Generated flamegraph, but haven't concluded what else can be improved.

https://github.com/mhuang74/qsv/blob/flamegraph/docs/flamegraph-validate-command.svg

**Comment by jqnatividad** [comment]
Avoiding calling serde_json on every row should improve performance.

As for profiling rayon-enabled code, it seems to be a known issue (https://github.com/rayon-rs/rayon/issues/591).

It's a little better with `export RAYON_NUM_THREADS=1`, but the rayon wrappers obscure the call stack...
```
$ export RAYON_NUM_THREADS=1
$ flamegraph --no-inline  target/release/qsvlite validate scripts/NYC_311_SR_2010-2020-sample-1M.csv scripts/nyc-50k.csv.schema.json 
```

![flamegraph-validate-1thread](https://user-images.githubusercontent.com/1980690/155008856-2423787f-fb8f-4eb0-ab58-890b5c202cd0.svg)

It's still useful though as it gives you some insight as to where most of the time is spent - per the flamegraph above - about 33% of the time on jsonschema stuff, and 24% on serde::ser::SerializeMap::serialize_entry.

Still, the `rayon` payoff is clear on my Ubuntu VM with 8 logical CPUs:
```
# qsvlite v0.32.1 (before rayon)
[00:01:44] [==================== 100% validated 1,000,000 records.] (9,589/sec)
621 out of 1,000,000 records invalid.

# qsvlite v0.32.2 (with rayon and RAYON_NUM_THREADS=1)
# showing the apparent overhead of rayon to be minimal
[00:01:42] [==================== 100% validated 1,000,000 records.] (10,046/sec)
621 out of 1,000,000 records invalid.

# qsvlite v0.32.2 (with rayon without setting RAYON_NUM_THREADS)
[00:00:17] [==================== 100% validated 1,000,000 records.] (68,212/sec)
621 out of 1,000,000 records invalid.
```

**Comment by jqnatividad** [comment]
It's blazing fast!
```
[00:00:06] [==================== 100% validated 1,000,000 records.] (283,848/sec)
621 out of 1,000,000 records invalid.
```
Yep! It's production-ready indeed. 

The throughput is amazing - from 9,500 records/sec on v0.32.1 pre-rayon to 280,000 records/sec after all your performance tweaking.

It'd be interesting to see how it performs with regex patterns, but even then, that will be in the jsonschema engine, so I think we can close this. WDYT?

**Comment by jqnatividad** [comment]
Hi @mhuang74 , I tweaked it a little more and managed to squeeze a little more performance - #173 

```
$ qsv validate NYC_311_SR_2010-2020-sample-1M.csv nyc-50k.csv.schema.json 
[00:00:03] [==================== 100% validated 1,000,000 records.] (298,775/sec)
Writing invalid/valid/error files...
621 out of 1,000,000 records invalid.
```

**Comment by mhuang74** [comment]
Thanks @jqnatividad . #173 looks good. Take 3-4 seconds to write the files while user reads the message.

**Comment by jqnatividad** [comment]
Closing this for now until the next round of performance tweaks.
