### ISSUE TITLE
BUG: Cargo install still refers to 0.122

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#1652]
I am still getting 0.122 when trying to cargo it on mac

**Comment by jqnatividad** [comment]
It's because the gender_guesser crate is still on the old release even after the maintainer merged my PR 
- https://github.com/Raduc4/gender_guesser/pull/3

If gender_guesser 0.2.0 is not released by this weekend, I'll just create a renamed fork named qsv-gender_guesser and publish it on crates.io.

**Comment by ondohotola** [comment]
Thanks

**Comment by ondohotola** [comment]
Still not working :-)-O

**Comment by jqnatividad** [comment]
Will have to wait when 0.124.0 is released. Targeting to release it today...

**Comment by ondohotola** [comment]
Cool :-)-O

**Comment by jqnatividad** [comment]
0.124.1 can now be built with cargo install

**Comment by ondohotola** [comment]
thank you
