### ISSUE TITLE
dedup functionality is wrong for numeric even with sorted

### ISSUE THREAD

**Issue by 13minutes-yt** [jqnatividad/qsv#1665]
A couple of problems I encountered on using dedup

`echo -e "data\n3\n1\n3\n10\n5"|qsv dedup`
```
data
1
10
3
5
1
```

it removed the duplicate yet it did not sort them numerically, and the 1 in the end is the duplicate count which is annoying (can be removed by -Q)

In the documentation, it is said to sort first

`echo -e "data\n3\n1\n3\n10\n5"|qsv sort -N|qsv dedup --sorted`
```
data
1
3
Aborting! Input not sorted! ByteRecord(["5"]) is greater than ByteRecord(["10"])
```

and of course 
```
$ echo -e "data\n3\n1\n3\n10\n5"|qsv sort -N|qsv dedup
data
1
10
3
5
1
```

**Comment by jqnatividad** [comment]
Good find @13minutes-yt . This is indeed a bug with `dedup`, will have to give it a `--numeric` option as well.

As for the 1 being returned to stderr by `dedup`, I needed that to get the number of dupes found in a program that uses qsv.  The `--quiet` option is there to suppress that.

**Comment by jqnatividad** [comment]
#1666 fixes this.  And you can now do:

```
echo -e "data\n3\n1\n3\n10\n5"| qsv dedup -N -Q 
data
1
3
5
10
```
