### ISSUE TITLE
new option for datefmt part 2 ( milliseconds to the epoch)

### ISSUE THREAD

**Issue by 13minutes-yt** [jqnatividad/qsv#1678]
Some json dates come as milliseconds to the epoch timestamps. like this 1707369660000. QSV identifies 10 digits only and if i use it for example
```
 echo -e "date\n1707369660000"|qsv datefmt 1 --formatstr "%Y-%m-%d"
date
2262-04-11

```
i had to remove the zeroes using regex to make it to work
 echo -e "date\n1707369660"|qsv datefmt 1 --formatstr "%Y-%m-%d"
date
2024-02-08

**Comment by jqnatividad** [comment]
Added to the enhancement backlog

**Comment by jqnatividad** [comment]
@13minutes-yt , this now works with the `--ts-resolution` option:

```
echo -e "date\n1707369660000"|qsv datefmt 1 --formatstr "%Y-%m-%d" --ts-resolution milli
date
2024-02-08
```

And yeah, "1707369660000" is actually milliseconds, not microseconds per
https://www.unixtimestamp.com/
