### ISSUE TITLE
datefmt doesn't recognize this timestamp

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#1692]
I can't seem to make it recognize this time stamp

`2024-03-24 20:16:24.355934+00:00Z`

it does 

`2024-03-24 20:16:24.355934+00:00`

though.

What am I doing wrong?

**Comment by jqnatividad** [comment]
This will require modifying qsv-dateparser - the crate qsv uses for date format inferencing.

I'll modify it so that it also supports unix epoch microseconds for #1678

**Comment by ondohotola** [comment]
Cool

**Comment by jqnatividad** [comment]
Actually, `2024-03-24 20:16:24.355934+00:00Z` is not a valid date format since it has both the timezone offset (`+00:00`) and the Zulu suffix.

It should be `2024-03-24 20:16:24.355934Z`. If so, we get:

```
echo -e "date\n2024-03-24 20:16:24.355934Z" | qsv datefmt 1 --formatstr "%s"
date
1711311384

echo -e "date\n2024-03-24 20:16:24.355934Z" | qsv datefmt 1 --zulu
date
2024-03-24T20:16:24Z
```
