### ISSUE TITLE
`slice`: add a `--json` flag for JSON output

### ISSUE THREAD

**Issue by rzmk** [jqnatividad/qsv#1718]
**Is your feature request related to a problem? Please describe.**
My task requires outputting a part of a dataset as JSON and currently I use `qsv slice` for this, however I need to convert the sliced data to a valid JSON format which is an extra step.

**Describe the solution you'd like**
A `--json` flag for `qsv slice` with the output formatted like `sqlp`'s `--format json` flag. No need for pretty-printing the output (could be another flag).

**Describe alternatives you've considered**
Potentially combining commands or if `sqlp` has a way to slice data based on start and end row number. Though for my purposes a `--json` flag would likely be the easiest to work with.

**Comment by jqnatividad** [comment]
Hi @rzmk ,

To confirm, do you want the JSON as a JSON array of arrays or as JSONL, where each JSON record is separated by newlines.

**Comment by rzmk** [comment]
An array of dictionaries where the keys of each dictionary are the headers and the values of each dictionary are that row's values.

**Comment by jqnatividad** [comment]
@rzmk, I did an implementation and it's a bit kludgy. Will keep tweaking it but have you tried piping the output of slice to `qsv tojsonl`?

Do you intend to use the JSON with DataTables that's why you need it in JSON array format?

**Comment by jqnatividad** [comment]
After tweaking it a bit, the implementation is much better now. The only thing it doesn't do is infer JSON types with everything as a JSON string, which for your use case, may not be required.
