### ISSUE TITLE
qsv validate - valid pass feature request

### ISSUE THREAD

**Issue by hughcameron** [jqnatividad/qsv#1728]
**Is your feature request related to a problem? Please describe.**

Thanks for the package. The `qsv validate` function is valuable in CI/CD use cases.

While, the documentation on the behaviour of valid files [is clearly stated](https://github.com/jqnatividad/qsv/blob/5105290820d8daced3c21f56ece203264a796cfd/src/cmd/validate.rs#L7-L8) - handling this case requires an extra step:

```bash
qsv validate data.csv validation.schema.json || true

if [ -f "data.csv.valid" ]; then
    mv "data.csv.valid" "valid_data.csv"
else
    cp "data.csv" "valid_data.csv"
fi
```

**Describe the solution you'd like**
An alternative approach could support a `--pass-valid` that passes all valid rows to the output file and returns an exit code of 1.

`qsv validate --pass-valid false data.csv validation.schema.json`

**Comment by jqnatividad** [comment]
@hughcameron , I implemented it as:

```
--valid-output <file>      Change validation mode behavior so if ALL rows are valid, to pass it to
                           output, return exit code 1, and set stderr to the number of valid rows.
                           Setting this will override the default behavior of creating
                           a valid file only when there are invalid records.
                           To send valid records to stdout, use `-` as the filename.
```

WDYT?

**Comment by hughcameron** [comment]
Thanks @jqnatividad. I've just tested this on `0.127.0`, and it works well.
This will be very useful in our pipelines. Appreciate you making the change 🙌.
