### ISSUE TITLE
`stats` & `frequency`: add a `--json` flag for JSON output

### ISSUE THREAD

**Issue by rzmk** [jqnatividad/qsv#1737]
**Is your feature request related to a problem? Please describe.**
Similar to #1718, currently I perform an extra step for getting JSON output from `qsv stats` and `qsv frequency` so it may be better for me (both from a refactoring and performance perspective) to not manually perform this step and have qsv handle it for me.

**Describe the solution you'd like**
A `--json` flag for `qsv stats` and `qsv frequency` with the output formatted like `sqlp`'s `--format json` flag. No need for pretty-printing the output (could be another flag).

**Comment by jqnatividad** [comment]
Now that `stats` has the `--stats-jsonl` option, this is partly completed.

**Comment by jqnatividad** [comment]
Given the verbosity of frequency results, this is better implemented by piping frequency results thru the `tojsonl` command rather than making this a native feature of `frequency`.
