### ISSUE TITLE
Locating.installing qsv

### ISSUE THREAD

**Issue by ggrothendieck** [jqnatividad/qsv#1753]
One of the main obstacles to using qsv is installing it. Not the actual installation process itself but
1. It is fairly difficult to locate the page where the downloads are if you don't already know.
2. The downloads are way down the page so even if you get there it's not clear you are on the right page.
3. If you do get that far there is a bewildering number of alternatives with no advice on how to determine which download you need.

It's not so hard for me now that I know but I did have trouble the first time and even worse is if if I ask someone else to run my qsv script who is not so computer savvy it's a real challenge for them.

**Comment by ondohotola** [comment]
Those who can read are in advantage…

**Comment by jqnatividad** [comment]
Thanks @ggrothendieck for your feedback.

I'll wordsmith the Installation section a bit to make it more accessible.

**Comment by jqnatividad** [comment]
I'll add a TLDR note on top of the Install section 😉 for 0.132.0
