### ISSUE TITLE
add `--no-headers` support to qsv cat rowskey

### ISSUE THREAD

**Issue by ggrothendieck** [jqnatividad/qsv#1756]
I need to concatenate two files with no headers and identify which file each row came from.  It would be nice if this worked.
```
qsv cat rowskey -n -g fstem file1.dat file2.dat
usage error: cat rowskey does not support --no-headers, as we use column headers as keys.
```
This works but it involves a lot of code, requires multiple passes,  results in temporary files that need to be removed and is not a single pipeline.
```
qsv rename -n Name,Value file1.dat > file1.csv
qsv rename -n Name,Value file2.dat > file2.csv
qsv cat rowskey --group-name Account --group fstem -- file1.csv file2.csv
```
This involves a single pipeline and no temporary files but is a lot of code and seems awkward.  Thesearch command was added at the end just to show we can continue the pipeline. (Assume this is in a windows bat file.)
```
@echo off
( qsv rename -n Name,Value file1.dat | qsv enum -c Account --constant file1 
qsv enum -n --constant file2 file2.dat ) | ^
qsv search "A|B"
```
Here are some files that can be used to test this out

file1.dat:
```
A,1
B,2
C,3
```
file2.dat:
```
A,11
A,21
C,31
```

**Comment by jqnatividad** [comment]
Hi @ggrothendieck ,
The way I'm thinking of implementing `cat rowskey --no-headers` is by temporarily auto-generating column names by column position using a 1-based index (e.g. _c_1, _c_2, etc) and then using these temporary colnames to cat the files, and then at the end, removing the temporary header.

Issuing `qsv cat rowskey -n -g fstem file1.dat file2.dat` would then result in:
```
file1,A,1
file1,B,2
file1,C,3
file2,A,11
file2,B,21
file2,C,31
```

WDYT?

**Comment by ggrothendieck** [comment]
That would be great. Would significantly simplify the pipeline.
