### ISSUE TITLE
`frequency`: add `--other` option

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1774]
When compiling frequency tables with the different limit options, give the user the option to create an "other" aggregation, summing up the other values beyond the limit, e.g. if we run frequency with the default limit of 10...

```
field,value,count
state,NY,100
state,NJ,70
state,CA,60
state,MA,55
state,FL,45
state,TX,43
state,NM,40
state,AZ,39
state,NV,38
state,MI,35
state,OTHER,250
```

**Comment by rzmk** [comment]
Another thing that may be useful is adding a flag to also add a column for the percentage/decimal based on the frequency/(total rows). Could maybe use `qsv count` for the total rows part.

**Comment by rzmk** [comment]
Also I'm curious how `--other` would handle if a value itself is named `OTHER`.

**Comment by jqnatividad** [comment]
The percentage option is a great idea. And for `--other`, maybe we can add another option called `--other-text` with a default value of `OTHER`.  It should be easy to add some field value collision logic on the off chance a valid field value is `OTHER`.

**Comment by rzmk** [comment]
Maybe for `--other` it could be consolidated to `--other <text>` with default `OTHER`?

**Comment by jqnatividad** [comment]
Given @rzmk 's feedback, we'll add a percentage column:

```
field, value, count, percentage
state, NY, 100, 12.90
state, NJ, 70, 9.03
state, CA, 60, 7.74
state, MA, 55, 7.10
state, FL, 45, 5.81
state, TX, 43, 5.55
state, NM, 40, 5.16
state, AZ, 39, 5.03
state, NV, 38, 4.90
state, MI, 35, 4.52
state, OTHER, 250, 32.26
```
