### ISSUE TITLE
`stats`: Max precision for float types

### ISSUE THREAD

**Issue by chadbaldwin** [jqnatividad/qsv#1803]
Summary: I'd like to see a max precision field added to the stats output for float type data.

**Is your feature request related to a problem? Please describe.**
I'm trying to use qsv to generate SQL Server `CREATE TABLE` statements. I _could_ just create columns using the `float` datatype, but I prefer to create them as decimal/numeric columns when I can. But with decimal/numeric you need to specify the scale and precision. For example...`100.3873` would be a scale of 7 and a precision of 4, so the SQL column would be `decimal(7,4)`.

I've been using `csvkit` which works well, and its `stats` feature (`csvstat`) _does_ include a `maxprecision` field. However, `csvstat` is extremely slow for large files, whereas `qsv` is extremely fast...it's just missing this one feature.

**Describe the solution you'd like**
I'd like to see a new field added for the stats feature. Basically reporting on the max precision. As far as how to handle trailing zero's...I don't know...I could argue either way, but counting them is probably better than truncating them off.

**Describe alternatives you've considered**
Already described above. I'm currently using csvkit's `csvstat` command, it's just _really_ slow. The other option is to just somehow do it myself by extracting that one column with qsv, and then using PowerShell/Python to treat them as a string and get the max length after the decimal point.

**Additional context**
None

**Comment by jqnatividad** [comment]
Hi @chadbaldwin , 

Thanks for the detailed enhancement request. And yep, max precision for float types would be most useful so I'll add it to the backlog.

**Comment by jqnatividad** [comment]
[qsv-stats 0.17](https://github.com/jqnatividad/qsv-stats) now has max_precision().

Will incorporate in the next release of qsv.

**Comment by jqnatividad** [comment]
I ended up removing the max_precision function from qsv-stats and just implemented it in qsv itself, with the added bonus that max_precision is computed in a streaming, multi-threaded manner, so it can be computed for arbitrarily large CSV files.

**Comment by chadbaldwin** [comment]
Awesome thanks! This will be perfect for what I'm trying to do (generate T-SQL Table schema from a CSV).

**Comment by jqnatividad** [comment]
And its now generally available with 0.128.0...
