### ISSUE TITLE
sqlp selects wrong data when multiple tables have the same named column

### ISSUE THREAD

**Issue by urkle** [jqnatividad/qsv#1820]
**Describe the bug**
qsv sqlp selects the wrong "table" when multiple CSV files have the same-named column.

**To Reproduce**
1. create CSV file "one.csv" with contents
```csv
id,data
1,open
```
2. create CSV file "two.csv" with contents
```csv
id,data
1,closed
```
3. run `qsv sqlp one.csv two.csv 'SELECT _t_1.id, _t_2.data FROM _t_1 JOIN _t_2 ON _t_1.id = _t_2.id'
The wrong output is produced
```csv
id,data
1,open
```

**Expected behavior**
The output
```csv
id,data
1,closed
```

**Desktop (please complete the following information):**
 - OS: macOS 12.7.4
 - qsv Version: qsv 0.127.0-standard-apply;fetch;foreach;geocode;Luau 0.622;to;polars-0.39.2;self_update-16-16;51.20 GiB-1.43 GiB-22.83 GiB-64.00 GiB (x86_64-apple-darwin compiled with Rust 1.77.2) prebuilt

**Comment by urkle** [comment]
This looks to be an issue with polars.

I installed polars-cli 0.7.0 and ran this query.

`select a.id, a.data as d1, b.data as d2 from read_csv('one.csv') as a join read_csv('two.csv') as b ON a.id = b.id;`

which yields
```text
┌─────┬──────┬──────┐
│ id  ┆ d1   ┆ d2   │
│ --- ┆ ---  ┆ ---  │
│ i64 ┆ str  ┆ str  │
╞═════╪══════╪══════╡
│ 1   ┆ open ┆ open │
└─────┴──────┴──────┘
```

**Comment by jqnatividad** [comment]
Thanks @urkle for the report and checking the query on polars-cli as well.

As you surmised, `sqlp` is really a convenience wrapper to tap the power of Polars for CSVs from the command-line.

Given polars' development tempo, if you report the issue, I wouldn't be surprised if the fix makes it into the next Rust Polars release.

**Comment by urkle** [comment]
@jqnatividad I am working on reporting w/ polars right now.

**Comment by jqnatividad** [comment]
https://github.com/pola-rs/polars/issues/16255 was closed as the problem was originally reported in https://github.com/pola-rs/polars/issues/16255, which is still awaiting resolution.

**Comment by jqnatividad** [comment]
Just upgraded polars to 0.40.0 and unfortunately, its still not returning the expected result.

**Comment by alexander-beedie** [comment]
FYI: the fix will be landing on our side in the (very) near future ;)
https://github.com/pola-rs/polars/pull/16507

**Comment by jqnatividad** [comment]
GH prematurely closed this...

**Comment by jqnatividad** [comment]
Now works as expected after we pinned our polars to the latest py-polars 0.20.31 release
