### ISSUE TITLE
Getting "usage error: " prepended to help messages for commands

### ISSUE THREAD

**Issue by rzmk** [jqnatividad/qsv#1833]
**Describe the bug**
When using `-h` on a qsv command like `stats`, `count`, or `headers`, I get `usage error: ` prepended to the output. Not sure what other commands this may occur on as I haven't tested them.

**To Reproduce**
1. Run `qsv headers -h`.

**Expected behavior**
No `usage error: ` before the help message.

**Screenshots/Backtrace/Sample Data**

![image](https://github.com/jqnatividad/qsv/assets/30333942/4d30b719-afde-4df8-b610-cd7f7db0ce2c)

**Desktop (please complete the following information):**
 - OS: Windows
 - qsv Version: v0.127.0

**Comment by jqnatividad** [comment]
Thanks @rzmk for the detailed bug report!
