### ISSUE TITLE
Update `contrib/bashly/completions.bash` & `contrib/bashly/src/bashly.yml` for qsv v0.129.0

### ISSUE THREAD

**Issue by rzmk** [jqnatividad/qsv#1877]
**Is your feature request related to a problem? Please describe.**

The currently available Bash completions files in [`contrib/bashly`](https://github.com/jqnatividad/qsv/tree/master/contrib/bashly) are set up for qsv v0.128.0. The [`contrib/bashly/src/bashly.yml`](https://github.com/jqnatividad/qsv/tree/master/contrib/bashly/src/bashly.yml) and `contrib/bashly/completions.bash` files must be updated for the upcoming qsv v0.129.0 release (steps explained in that directory's `README.md`).

**Describe the solution you'd like**

Update [`contrib/bashly/src/bashly.yml`](https://github.com/jqnatividad/qsv/tree/master/contrib/bashly/src/bashly.yml) with all the commands/subcommands/options/etc. for qsv v0.129.0 and then generate the updated `contrib/bashly/completions.bash` file.

**Additional context**

Identifying all of the changes (new/modified commands/subcommands/options/etc.) that have been made since v0.128.0 is required.

**Comment by rzmk** [comment]
If #1307 is completed then this could potentially be automated by comparing the JSON outputs (e.g., between versions, manual workflows, etc.) and generating the necessary files. Users could then also generate the latest completions from master and this could lead to a command that automatically generates and/or enables completions (e.g., `qsv completions`).

**Comment by jqnatividad** [comment]
This could be further automated by extending qsv-docopt as noted in #1307

**Comment by rzmk** [comment]
See `qsv enum` for new changes.

**Comment by rzmk** [comment]
Remove `--ollama` for `qsv describegpt`.
