### ISSUE TITLE
add enum-like options to `qsv fill`

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#1887]
I have a CSV file with an ID column created with `qsv enum`. Currently, unless I'm missing an obvious route, when I add additional rows to the file later, it's quite complicated to get them to also follow this ID pattern. (I have a similar issue with one with a `qsv enum --uuid` column, though that's easier to generate out-of-band.)

Perhaps one way to make this simpler might be to allow `qsv fill` to also take these incrementing-enum and uuid options, rather than only a constant value? Or is there a simpler approach here that I'm not thinking of?

**Comment by jqnatividad** [comment]
Perhaps, the best way to "fix" this is to implement a new option to `enum` to `--overwrite-index` where `enum` will not create a new index/id column, but overwrite it instead?

In this way, with the upcoming `--hash` option (#1888), you can `fill` then recalc the id with `enum --hash`?

WDYT @tmtmtmtm ?

**Comment by jqnatividad** [comment]
Hi @tmtmtmtm ,
With the new deterministic `--hash` option in `enum`, I believe we don't need to extend `fill` with similar incrementing-enum and uuid options...

Can you confirm?

**Comment by tmtmtmtm** [comment]
Hi @jqnatividad. I'm not sure yet, and it's probably going to take a while of playing with `enum --hash` to know how easily I can migrate the existing approaches over to that. Do you have an expected release date for that yet?

**Comment by jqnatividad** [comment]
@rzmk and I are targeting to release 0.129.0 this week - it'll be the biggest release ever!

**Comment by jqnatividad** [comment]
Hi @tmtmtmtm , we just released 0.129.1. Please do let us know if `enum --hash` works to fulfill this request.

**Comment by tmtmtmtm** [comment]
Hi @jqnatividad — `qsv enum --hash` seems like it'll _probably_ be a good enough solution to this, but it's going to take a while to work through all the different places I've jury-rigged my own workarounds to see if there are any gotchas. I'm happy enough to close this for now, though, and open something new if that happens.
