### ISSUE TITLE
deterministic qsv enum 

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#1888]
A lot of times I add id columns to incoming CSVs that don't already have one, to make various other tasks simpler later. But when the upstream file changes, and I re-generate a new version of my copy, and then `diff` that, I can end up with a lot of noise in the case where, say, one line has been moved, and everything after than gets renumbered. 

It would be great if there was an option, similar to `--uuid`, but where the result was more deterministic (perhaps by generating a SHA of the existing data, or something along those lines?)

Or is there some way to get there with `qsv apply dynfmt` that I can't think of atm (other than explicitly concatenating all the other fields together)?

**Comment by jqnatividad** [comment]
Generating a hash is a good idea to enable `enum` to create a deterministic ID.

I'll add a `--hash` option to enum, perhaps using the [xxhash](https://crates.io/crates/xxhash-rust) crate to make it fast and the same hash is generated across platforms.
