### ISSUE TITLE
CSV -> JSON -> CSV conversion diff and loss of double quotes

### ISSUE THREAD

**Issue by rzmk** [jqnatividad/qsv#1892]
**Describe the bug**

Particularly to the CSV I present though it may also appear with other CSVs too, when converting a CSV to JSON with `qsv slice --json` then back to a CSV with `qsv jsonp` there is a diff found with `qsv diff` and double quotes are lost too.

**To reproduce:**

Say I have a file `House.csv`:

```csv
id,date
"5036300431","20150311T000000"
"4168000060","20150226T000000"
"6021501535","20140725T000000"
"6021501535","20141223T000000"
"1483300570","20140908T000000"
"3422049190","20150330T000000"
```

Then I run `qsv slice House.csv --json -o House.json`

Here's  `House.json`:

```json
[{"id":"5036300431","date":"20150311T000000"},{"id":"4168000060","date":"20150226T000000"},{"id":"6021501535","date":"20140725T000000"},{"id":"6021501535","date":"20141223T000000"},{"id":"1483300570","date":"20140908T000000"},{"id":"3422049190","date":"20150330T000000"}]
```

Followed by `qsv jsonp House.json -o House2.csv`.

Here's `House2.csv`:

```csv
id,date
5036300431,20150311T000000
4168000060,20150226T000000
6021501535,20140725T000000
6021501535,20141223T000000
1483300570,20140908T000000
3422049190,20150330T000000

```

When I run `qsv diff House.csv House2.csv` I get some diff result as follows:

```csv
diffresult,id,date
-,6021501535,20141223T000000
+,6021501535,20140725T000000

```

**Expected behavior**
No diff between `House.csv` and `House2.csv` and no loss of double quotes for string values in `House2.csv`.

**Screenshots/Backtrace/Sample Data**

![image](https://github.com/jqnatividad/qsv/assets/30333942/c445c7bd-f423-4b66-acb5-c32754dbf1c7)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - qsv Version: master (between v0.128.0 and v0.129.0)

**Additional context**

`qsv jsonp` uses Polars and this may result in some sort of conversions but I'm not sure why a diff is showing.

**Comment by jqnatividad** [comment]
@rzmk, I also think it's a polars issue.
I just upgraded the engine to the latest tagged release - py-polars-1.0.0-beta.1.

There are a ton of fixes, so you may want to give it a try...

**Comment by rzmk** [comment]
@jqnatividad Still getting the same issue.

![image](https://github.com/jqnatividad/qsv/assets/30333942/e8a7c2ef-30f7-423b-9d5a-c6cb166aedc9)

For example I add the double quotes into `House2.csv` afterwards:
```csv
id,date
"5036300431","20150311T000000"
"4168000060","20150226T000000"
"6021501535","20140725T000000"
"6021501535","20141223T000000"
"1483300570","20140908T000000"
"3422049190","20150330T000000"

```

Then use `qsv diff House.csv House2.csv` again but still get the same diff:

<img src="https://github.com/jqnatividad/qsv/assets/30333942/c57e8ba7-2f5c-4c25-8eb3-f894aa36d31b" width="200">

Not sure why this is the case. Using an online diff checker and removing the newline at the end of `House2.csv` I get identical:

![image](https://github.com/jqnatividad/qsv/assets/30333942/fa2b673e-83bb-43d1-a5f6-e3c304c74c8f)

**Comment by jqnatividad** [comment]
So its an issue with `diff` then.

Any clues why `diff` fails here @janriemer?

**Comment by rzmk** [comment]
I think this issue is because I didn't notice that `qsv diff` is basing its `--key` value on the default of column `0`:

```
-k, --key <arg...>              The column indices that uniquely identify a record
                                as a comma separated list of indices, e.g. 0,1,2.
                                (default: 0)
```

`House.csv` and `House2.csv` have duplicate entries within the first column, not a uniquely identifying column. For example we can use `qsv enum House.csv -o House_enum.csv` and `qsv enum House2.csv -o House2_enum.csv` then compare with `qsv diff House_enum.csv House2_enum.csv -k 2` to get the expected no diff:

<img src="https://github.com/jqnatividad/qsv/assets/30333942/647e3108-a020-4b93-874e-86ce87af70d6" width="300" />

**Comment by jqnatividad** [comment]
Thanks for the thorough investigation @rzmk! Merged #1897 and closing this.

**Comment by janriemer** [comment]
Thank you for the (correct) analysis, @rzmk, and thank you for tagging me @jqnatividad ! 👍 

Currently, I haven't much time, so the following will be rather short and sweet (I might open separate issues for it later):

Some ideas to make this error less likely in the future:

- Store key fields in HashSet or similar and throw error if duplicates are found
  - this unfortunately goes exactly against one of `diff`'s core optimizations, which is to __reuse memory__ (records that are equal are thrown away), but maybe we can provide it as an option (not sure what the default should be)
- Make it mandatory to specify key field(s) in the args, so people are more aware of it

IMO, the second option would be best, because it is the easiest to implement, but will require a breaking change. 😕

Even if we decide to go with the second option now, we can later still implement the first option as well and have both.

**Comment by jqnatividad** [comment]
Thanks @janriemer for your short and sweet! 😉 

IMHO, we just just wordsmith the usage text to let users be more aware of the default behavior.

In addition, perhaps we can add a special sentinel value (e.g. ALL) to use all columns as an index...

WDYT?

**Comment by janriemer** [comment]
> In addition, perhaps we can add a special sentinel value (e.g. ALL) to use all columns as an index...

Oh, this is neat, I really like this!🤩

> just wordsmith the usage text to let users be more aware of the default behavior

Yes, agreed, let's go with both of your solutions then!👍
