### ISSUE TITLE
create custom apt repository

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1989]
So folks with Debian-based distros (e.g. Ubuntu, Alpine, Fedora, etc.) can easily install qsv using `apt-get`.

This should also make it easier to install qsv for DP+ and to have semantic versioning auto-upgrades of qsv for DP+ as qsv gains additional inferencing and analysis capabilities for DRUF workflow over time.

**Comment by jqnatividad** [comment]
Thanks @tino097 ! Let's create a GH publish workflow to build the .deb file and upload it to releases.

Just copy the existing `[publish-wix-installer](https://github.com/jqnatividad/qsv/blob/master/.github/workflows/publish-wix-installer.yml)` workflow and customize it.

In that way, with every release, we can just invoke it as part of the release process.

**Comment by tino097** [comment]
@jqnatividad 
Can you please test https://github.com/tino097/qsv-deb-releases 
Currently i need to add the new releases manually but im working the github action to get this process automated

**Comment by jqnatividad** [comment]
Can confirm that this works!

Thanks @tino097!

Closing this now and creating a new ticket to get it automated.
