### ISSUE TITLE
Error when using `qsv reverse` when index file is present

### ISSUE THREAD

**Issue by rzmk** [jqnatividad/qsv#2002]
**Describe the bug**
At times when I'm using `qsv reverse` and an index file is present for a given CSV file, I get an io error even though the reversed output is also produced as intended.

**To Reproduce**
1. Generate an index file for a CSV file with `qsv index`.
2. Run `qsv reverse <filepath>`.

**Expected behavior**
No error when reversing the file even with the index file present.

**Screenshots/Backtrace/Sample Data**
![image](https://github.com/user-attachments/assets/b28e58fd-fa2a-4e4e-9067-9f64d26a3911)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - qsv Version: 0.129.1

**Comment by jqnatividad** [comment]
Good catch @rzmk!
