### ISSUE TITLE
`qsv edit` - Edit a specific cell with a new value by row and column

### ISSUE THREAD

**Issue by rzmk** [jqnatividad/qsv#2046]
**Is your feature request related to a problem? Please describe.**
Looking for a relatively simple interface to edit a specific cell within a spreadsheet. Editing a specific cell with a new value, maybe called `qsv edit`.

**Describe the solution you'd like**
qsv command that lets a user specify a row and cell to edit with a new value. At a basic level the cell can be replaced with a string and in the future could consider regex, etc.

For example if I want to replace the cell value `comb` with `notebook` as shown in the following image then I'd run a command using the row and column indices:

![Untitled](https://github.com/user-attachments/assets/b58647b3-c930-45ce-bec4-4c604f427357)

```bash
qsv edit items.csv 2 2 "notebook"
```

Or something similar (`-x`/`col` and `-y`/`row` flags? different input order? index change based on header value or choose 0 vs 1 index? choose column by column name? choose row by a specific column's value? validate cell editing by an optional schema input?)

**Describe alternatives you've considered**
qsv `replace` but that interface may be too much for this specific use case where a user may just want to edit a single cell with a new value (and no regex by default).

**Comment by jqnatividad** [comment]
Great idea!

For consistency, I would use `select` syntax for setting the column/s.  For selecting the rows, I would use `slice` syntax.

I agree that for the initial implementation, let's just keep it to a single cell.  And then when you want to operate on multiple columns/rows, to have the `columns` and `rows` subcommands respectively.

**Comment by rzmk** [comment]
Can you show an example of the what this command would look like using that syntax?

**Comment by jqnatividad** [comment]
I think the main thing, is that they're consistent with `select/slice`, but only operating on single cells for the initial implementation.

That is, for column selection, support names. For row selection, that it be 0-based like `slice`.

```
# for your example above
qsv edit items.csv item 1 "notebook"

# edit the last column, 3rd row
qsv edit items.csv _ 2 "1.99"
```

In that way, by being consistent with `select/slice` syntax/semantics for single cell `edit`ing, you can implement multi-column/multi-row `edit`ing in a qsv-consistent way when you do choose to implement compound editing in the future.

WDYT?

**Comment by jqnatividad** [comment]
Closing this with the `edit` command merged. Thanks @rzmk !
