### ISSUE TITLE
BUG: panic with qsv frequency

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#2053]
After auto-updating to qsv 0.131.1 lots of my scripts have started failing. There still seems to be a problem with `qsv frequency`:

```sh
> echo "id\n1\n2\n3\n3\n3" | qsv frequency      
thread 'main' panicked at src/util.rs:1956:66:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jqnatividad** [comment]
There was a problem with how it handle stdin input that I introduced when I made `frequency` "smarter" by using a column's cardinality when a stats cache is available.

It's now fixed. Let me know if there are any other `frequency` issues beyond stdin input.

**Comment by tmtmtmtm** [comment]
Thanks for the fast fix @jqnatividad — most of my uses of `frequency` are in a pipeline against the output of other qsv commands, so that explains why they all exploded so spectacularly :)
