### ISSUE TITLE
Exact search?

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#2056]
I fairly regularly find myself wanting to run `qsv search` for an exact string, and then get caught out by`qsv search -s id 179` also returning 1790, 1791, etc.

So then I remember to anchor it as `qsv search -s id "^179$"`, and everything is fine until I'm looking for something with special characters (`qsv search -s url "^https://example.com/?id=179$"`). So then I have to dig even deeper into my memory to remember the syntax for `qsv luau filter "url = …"` (often forgetting at first that I need `==` there)`. 

At this point I return to the docs sure that I've overlooked something much simpler for what has to be a common usage pattern.

Am I actually missing something really obvious? Or, might it be possible to add an 'exact match' flag to `qsv search` (or possibly a separate `qsv find` or the like)?

**Comment by jqnatividad** [comment]
That's a good idea @tmtmtmtm !

I'll add a new `--literal` option to both `search` and `searchset`. If the `--literal` option is set, you can search even with the regex special characters.
