### ISSUE TITLE
Scoop.sh install (or update) is failling with version 0.132

### ISSUE THREAD

**Issue by Orcomp** [jqnatividad/qsv#2080]
Updating qsv via scoop is failing with version 0.132

(`scoop install qsv@0.129.1` works fine, so I'm running 0.129.1 for now.)

The error message I am getting when installing 0.132 is:
```
λ scoop install qsv
Installing 'qsv' (0.132.0) [64bit] from 'main' bucket
Loading qsv-0.132.0-x86_64-pc-windows-msvc.zip from cache
Checking hash of qsv-0.132.0-x86_64-pc-windows-msvc.zip ... ok.
Extracting qsv-0.132.0-x86_64-pc-windows-msvc.zip ... done.
Linking ~\scoop\apps\qsv\current => ~\scoop\apps\qsv\0.132.0
Creating shim for 'qsv'.
Get-Command: D:\Users\orcomp\scoop\apps\scoop\current\lib\install.ps1:757
Line |
 757 |              $bin = (Get-Command $target).Source
     |                      ~~~~~~~~~~~~~~~~~~~
     | The term 'qsv.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
     | Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Can't shim 'qsv.exe': File doesn't exist.
```

**Comment by jqnatividad** [comment]
Thanks for the report @Orcomp .

However, as noted in [Installation Option 2](https://github.com/jqnatividad/qsv?tab=readme-ov-file#option-2-package-managers--distributions), the qsv scoop package is not maintained by us, but by other volunteers.

Have you tried opening an issue there?

https://github.com/search?q=repo%3AScoopInstaller%2FMain+qsv&type=issues

**Comment by rzmk** [comment]
There's no `qsv.exe` in qsv-0.132.0-x86_64-pc-windows-msvc.zip but there is `qsvp.exe`.

**Comment by Orcomp** [comment]
Apologies for the noise.

**Comment by jqnatividad** [comment]
No worries @Orcomp , and thanks @rzmk for digging into why scoop failed.

FYI, we've been enabling CPU features on the prebuilts for performance. However, this prevents qsv from running on older machines, that's why we created the "portable" version with the p suffix recently.

The msvc zip archive should have both `qsv.exe` and `qsvp.exe` though, so this is a publishing bug on our end. Will correct it for the next release.

So its not noise @Orcomp , its a valid `bug` signal... 😄

**Comment by jqnatividad** [comment]
Note that with #2083, I re-published 0.132.0 and qsv-0.132.0-x86_64-pc-windows-msvc.zip now has qsv.exe.

**Comment by jqnatividad** [comment]
Will close this once qsv scoop package is rebuilt.

**Comment by jqnatividad** [comment]
Per   https://github.com/ScoopInstaller/Main/issues/6133, the fix will be picked up on the next qsv release...
