### ISSUE TITLE
qsv fmt -t <space>?

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#2081]
I'm not sure if there's a trick I'm missing, but I don't seem to be able to get `qsv fmt -t ' '` to work no matter what sort of shell hoops I jump through. Does this need to be special-cased, or is there a standard workaround?

**Comment by jqnatividad** [comment]
Interesting...  what does `qsv --version` say and what OS are you using?

`qsv fmt -t ' '` works as expected on my daily driver - a 24gb M3 MacBook Air, running macOS Sequoia 15.1 Developer Beta, using the default zsh shell.

Regardless, I can easily add another `--out-delimiter` special case for space ('S'), similar to tab ('T').

**Comment by tmtmtmtm** [comment]
Aha. It seems the space between the `-t` and `' '` is significant here, though it doesn't seem to be more generally:

```sh
> echo "foo,bar" | qsv fmt -t'%'
foo%bar

> echo "foo,bar" | qsv fmt -t' '
io error: failed to open -t : No such file or directory (os error 2)

> echo "foo,bar" | qsv fmt -t ' '
foo bar
```

This makes me feel a little better, in that I was sure this had worked for me before, but it was clearly too early in the morning for me to find the super-simple workaround of adding an extra space 😀

**Comment by jqnatividad** [comment]
Before your first cup? 😉 I'm getting a cup of coffee myself as I close this... 😄
