### ISSUE TITLE
move --help from stderr to stout

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#2105]
If I run `--help` I have to add `2>&1` before I can pipe it through `less` which I don't have to do for `--list`.

I often forget and then have to quit `less`, repeat the command, with the redirection.

**Comment by jqnatividad** [comment]
This requires tweaking docopt a bit.

Added it to the backlog @ondohotola .

**Comment by ondohotola** [comment]
Thanks.

**Comment by jqnatividad** [comment]
To confirm, looking at GNU guidelines...

https://www.gnu.org/prep/standards/standards.html#g_t_002d_002dhelp

It does specify that `--help` and `--version` should both go to stdout, not stderr.

**Comment by jqnatividad** [comment]
Move qsv_docopt crate to https://github.com/dathere/qsv-docopt.

Fixes will be done there going forward.

@rzmk, also will implement the enhancement there so qsv pro can show usage text. Thinking of using markdown on all usage text so it looks prettier on qsv pro...

**Comment by rzmk** [comment]
If switching to markdown for the usage text then it may be neat to render it as formatted in the terminal too:

- This crate may be useful: https://github.com/Canop/termimad
- This other one's in alpha: https://github.com/guilhermeprokisch/see

**Comment by jqnatividad** [comment]
termimad looks awesome @rzmk!

Apart from styling, it handles scrolling too!
