### ISSUE TITLE
Homebrew installer

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#215]
We publish pre-built binaries here, and qsv has self-update.

But it'd be nice if you can also install it using [Homebrew](https://brew.sh/) as well.

**Comment by FnControlOption** [comment]
Done https://formulae.brew.sh/formula/qsv

**Comment by jqnatividad** [comment]
Oh! Thanks heaps @FnControlOption !!!!

Sorry I missed this, but will be sure to add it to the docs with the next release!
