### ISSUE TITLE
Gate the `prompt` command behind a `prompt` feature

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#2160]
### Discussed in https://github.com/jqnatividad/qsv/discussions/2155

<div type='discussions-op-text'>

<sup>Originally posted by **derekmahar** September 20, 2024</sup>
How can I exclude crate [rfd](https://github.com/PolyMeilex/rfd) from the qsv build?  Crate rfd breaks my qsv build on a headless server that has no window manager because it indirectly requires crate [wayland-sys](https://github.com/smithay/wayland-rs) which fails to build because wayland-sys cannot find wayland-client which isn't installed.</div>

**Comment by derekmahar** [comment]
Thank you for implementing the `prompt` feature.  Did you intend for `all_features` to include `prompt`?  `all_features` in `Cargo.toml` includes `prompt`, but [FEATURES](https://github.com/jqnatividad/qsv/blob/master/docs/FEATURES.md) specifies that `all_features` does not include `prompt`?  Is it possible to instruct `cargo build` to exclude a feature that a feature list includes?

**Comment by derekmahar** [comment]
Note that I now successfully build qsv using the command

```
cargo build --release --locked --features "feature_capable apply fetch foreach geocode lens luau polars python to"
```

Would it be useful to group these features in a feature list named "console_features", for example?

**Comment by jqnatividad** [comment]
Glad to know you can build qsv now on your headless server.

As for `prompt` not being documented in FEATURES.md, that was an oversight on my part and have since updated it.

As for creating a `console_features` grouping feature, let's bookmark that for now until we get more commands that require a window manager.  Right now, `prompt` is the only one - though technically, you can actually still build and run it headless by just installing `libwayland-dev` like we do on the publishing workflows.

https://github.com/jqnatividad/qsv/blob/7c76af7415be8a85afbf0f63e3382a145cfbe49d/.github/workflows/publish.yml#L153-L156

All commands requiring a GUI, going forward, will be on qsv pro.
