### ISSUE TITLE
BUG: qsv enum --hash with --new-column blows up if a 'hash' column already exists

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#2172]
If I have a CSV file with a column named 'hash' (no matter the contents of it) then `qsv enum --hash` coupled with `--new-column` (no matter the new column name) fails with mismatched column counts:

For example:

```sh
> echo "name\nFred\nJoe\nMary" | qsv enum -c hash > data.csv
> qsv enum --hash name -c id data.csv
name,hash,id
Fred,7744023578077004230csv error: CSV error: found record with 2 fields, but the previous record has 3 fields
```
 
[qsv 0.134.0-mimalloc-apply;fetch;foreach;geocode;Luau 0.640;to;polars-0.42.0-fe04390;self_update-8-8;12.80 GiB-698.38 MiB-0 B-16.00 GiB (aarch64-apple-darwin compiled with Rust 1.81) prebuilt]

**Comment by jqnatividad** [comment]
`--new-column` was originally just intended for `--increment` and not the other enum modes.

But I "fixed" your scenario above and enabled setting `--new-column` for the other enum modes as well.

**Comment by tmtmtmtm** [comment]
Ah, it's wasn't clear to me that `--new-column` wasn't meant to work here, but yay for making it so that it does 😁
