### ISSUE TITLE
Set up qsv MSI installer signing

### ISSUE THREAD

**Issue by rzmk** [jqnatividad/qsv#2181]
With datHere as a verified publisher, the qsv.msi file can be signed which can remove the Defender Smartscreen warning when attempting to install qsv from the MSI installer.

**Comment by jqnatividad** [comment]
Thanks @rzmk , I merged the change to the GH action. Just send the secrets separately, and it successfully builds and confirm that it installs without triggering Windows Defender, we'll close this.

**Comment by jqnatividad** [comment]
Hi @rzmk, I tried running the MSI publishing workflow and its looking for the secrets. Let's set it up so we publish signed MSI files again.

**Comment by rzmk** [comment]
Are the secrets added to the repo yet?

**Comment by jqnatividad** [comment]
No... I gather you sent them over to me? I must have missed it...

**Comment by rzmk** [comment]
Since this is not planned for now I think it'd make sense to remove the secrets changes. Also may want to consider whether to (optionally?) bundle `qsvp` instead of `qsv` for devices that can't work with the CPU optimizations.

**Comment by jqnatividad** [comment]
OK... let's close the issue for now.

In the future though, it'd be great if we can use sysinfo the get the system's capabilities in qsv pro, and fetch a private build of qsv that is optimized for the detected architecture.
