### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#234]
Currently, the next-gen datapusher ( #189) is invoking qsv by using python's `subprocess` module.

This is not so bad as qsv (as with Rust programs) is statically linked and the binary is relatively small.

It would be nice if we take advantage of [Pyo3](https://github.com/PyO3/pyo3) to create python bindings for qsv so we can create a qsv python module and call it directly from python, not only for datapusher+, but for other data-wrangling tasks in CKAN.

**Comment by jqnatividad** [comment]
With the qsvdp - the Datapusher+ optimized binary weighing in at 3.4M (vs 8.4M for qsvlite and 19M for qsv), I think the need to do this is as important.

DP+ is already very fast and calling qsvdp repeatedly doesn't seem to have any material performance impact as the OS I'm sure must be loading it from cache and not from the disk repeatedly).

Calling Rust binaries from other languages doesn't seem to be a bad thing anyway - Visual Studio Code does it with ripgrep (which weighs in at 4.3M) whenever you do "Find in Files..."

**Comment by jqnatividad** [comment]
Reprioritize this for the next major release of DP+, so we can call qsv directly as a python module.

**Comment by kindly** [comment]
I think that `qsv` should have some kind of rust library interface first. Even if the libararies interface is essentially just passing the command line arguments to the function:

`apply.run(argv: &[&str])`
`behead.run(argv: &[&str])`
...

This would be very useful for other rust libaries to use but also make python bindings easier.

**Comment by jqnatividad** [comment]
Good idea @kindly!  As you pointed out, doing so will be a good intermediate step towards getting Python bindings.
