### ISSUE TITLE
error line handle way

### ISSUE THREAD

**Issue by pkptzx** [jqnatividad/qsv#253]
i want `options` handle error level.

(i have many csv files , every file more then 100GB )

eg.  header field 10, but content field 9
i want to set `error options` it's ok, this valid.

and
i know last line it's error , i want ignore last line ,how to do ?

and 
i konw some file , head 3 lines it's summary info, how to skip before 3

**Comment by jqnatividad** [comment]
Hi @pkptzx ,
Can you post your "how to" question on [Discussions](https://github.com/jqnatividad/qsv/discussions) instead? I try to keep issues to bug reports and feature requests.

**Comment by jqnatividad** [comment]
Hi @pkptzx,
I answered your first two queries in Discussions
 #258 and
 #259 

as for your last question re summary info, check #112

**Comment by pkptzx** [comment]
@jqnatividad thanks!!!
before, I just want to use qsvcli ,  use qsvcli find/statistics csv file. reluctant use other knowledge/cmd .
Now it seems that it can only be handled in your suggest way.

but , I still hope qsv support   skip head and tail line  `^_^`
