### ISSUE TITLE
Provide linux musl binaries

### ISSUE THREAD

**Issue by dufferzafar** [jqnatividad/qsv#269]
**Is your feature request related to a problem? Please describe.**
Current x86_64 Linux binaries are only compiled with GNU libraries - so I'm not able to run qsv on machines with older GLIBC.

Building with musl on Linux would fix this.

**Comment by jqnatividad** [comment]
Done. 
@dufferzafar , `x86_64-unknown-linux-musl` binaries are now also published on release starting with qsv 0.41.0.

**Comment by howff** [comment]
This might be exactly what I need, thank you.

I did try building it myself but nothing happened!
```
$ cargo build --release
    Updating git repository `https://github.com/jqnatividad/calamine`
    etc
  Downloaded serial_test v0.6.0
  Downloaded 1 crate (4.5 KB) in 0.20s
  etc
    Finished release [optimized] target(s) in 15.04s
```
Nothing at all has been built! There's nothing in the target directory or anywhere else. How do I get it to build?!

**Comment by jqnatividad** [comment]
Hi @howff , sorry I missed this.
But yes, you need to specify which binary you want to build:

```
# for qsv
cargo build --release --features apply,generate,lua,fetch,foreach,python,full
# for qsvlite
cargo build --release --features lite
# for qsvdp
cargo build --release --features datapusher_plus
```
