### ISSUE TITLE
Additional date format detection, DD/MM/YYYY

### ISSUE THREAD

**Issue by EricSoroos** [jqnatividad/qsv#275]
In #174 and #177, there were some additional date formats and styles parsed. 

We would like to disambiguate between the mm/dd/yyyy and dd/mm/yyyy formats. This is possible on a large enough dataset (at least, one that contains dates after the 13th of the month.

The current dateformats provided by dateparser don't include any of the ambiguous date formats, and the current ones are US centric. 

As a start, we'd like to be able to detect this date format, but ultimately I think we'd end up wanting to rewrite this into the ISO standard date format.

**Comment by EricSoroos** [comment]
I'm aware that it's non-trivial, but at the very least recognizing the non-us DD/MM/YYYY format is important for my use in the EU. So long as the dataset is consistent and large enough, it's possible to disambiguate between that and the MM/DD/YYYY format. 

The most non-trivial part of it might be maintaining compatibility with the standardized schema types, because that is a finer distinction than the schema seems to account for (it being concerned with date/datetime/time level metadata)

I was able to hack this into messytables/datapusher at least well enough that we'd generally detect the right date format.

**Comment by jqnatividad** [comment]
There is an identical open issue on the upstream crate

https://github.com/waltzofpearls/belt/issues/21

I'll be sure to incorporate it into the qsv-dateparser fork once its implemented upstream.

And per @waltzofpearls, we can have a date preference given the challenge of disambiguating between dd/mm/yyyy and mm/dd/yyyy, that qsv can in turn expose as an environment variable.

**Comment by jqnatividad** [comment]
@EricSoroos , would adding an option and a related env var to prefer DD/MM/YYYY be sufficient?

Insofar as Datapusher+ is concerned, we can have a DP+ env var for the default preferred date format, that can be overridden on a resource-by-resource basis "DMY format" resource extra.

I'm expediting implementing this as DMY is more prevalent than I thought -

**Comment by EricSoroos** [comment]
I think that combination is ok, but it would absolutely have to be coordinated with postgres if you're using it's native dateparsing in copy. 

If there was a way to do date detection where the entire column would need to be one order or the other, that would be ideal (and that's basically what I did to messytables). But in order to do that, you'd need to be able to assert that all of the rows of a column were the same/compatible format, and that's not how QSV does things. 

The worst thing is an adaptive solution (which was native postgres for a while) that would try one, and if it failed try the other.
