### ISSUE TITLE
Add an option to have sniff output in machine readable format

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#282]
It would be great to have a way to have sniff output  in machine readable format.
Because sometimes it's useful to inspect a lot of files and create a summary output for all.

Thank you

```json
{
  "Delimiter": "f",
  "Has header row?": "true",
  "Number of preamble rows": 1,
  "Quote character": "none",
  "Flexible": "false",
  "Number of records": 10,
  "Number of fields": 2,
  "Types": {
    "0": "Text",
    "1": "Text"
  }
}
```

**Comment by jqnatividad** [comment]
@aborruso I implemented this, but ultimately decided not to do the column names, as that will require modifying the csv-sniffer crate.

**Comment by aborruso** [comment]
@jqnatividad thank you very much.

Is it normal that there is not the `-d` option?

**Comment by jqnatividad** [comment]
Hi @aborruso , just wanted to let you know that I ended up creating a qsv-optimized fork of csv-sniffer that sniffs out field names as well :)

Lemme know how it works for you...

And yes, there is no `--delimiter` option for `sniff` as it detects the delimiter.

**Comment by aborruso** [comment]
Hi @jqnatividad , I have installed `qsv 0.50.1-mimalloc-apply;fetch;foreach;generate;lua;python;-8-8`, and in the sniff output I do not have field names. In example:

```
{
  "delimiter_char": ";",
  "header_row": true,
  "preamble_rows": 0,
  "quote_char": "none",
  "flexible": false,
  "is_utf8": true,
  "num_records": 29,
  "num_fields": 10,
  "types": [
    "Unsigned",
    "Text",
    "Text",
    "Text",
    "Text",
    "Text",
    "Text",
    "Text",
    "Text",
    "Text"
  ]
}
```

Is it normal?

Thank you for all

**Comment by jqnatividad** [comment]
Hi @aborruso ,
You'll have to wait for the next release - probably by late this week.
I just made the changes yesterday after releasing 0.50.1.

Of course, you can always compile from source if you can't wait.

But to give  you an idea:

https://github.com/jqnatividad/qsv/blob/6734a7744dceaf8f290db11799d553e8ea47b14a/tests/test_sniff.rs#L142-L173

**Comment by jqnatividad** [comment]
@aborruso , [0.51.0](https://github.com/jqnatividad/qsv/releases/tag/0.51.0) is out as promised with the additional `sniff` functionality.  Hope you find it useful!

**Comment by aborruso** [comment]
> @aborruso , [0.51.0](https://github.com/jqnatividad/qsv/releases/tag/0.51.0) is out as promised with the additional `sniff` functionality. Hope you find it useful!

Really great, thank you
