### ISSUE TITLE
To have schema output also in stdout

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#319]
**Describe the solution you'd like**
I think it should be useful to have the schema output in stdout, to use it in some ETL processing.

To have it as option.

Thank you

**Comment by jqnatividad** [comment]
Here you go @aborruso.

I'll let you know once 0.52.0 comes out with this functionality.

**Comment by aborruso** [comment]
> I'll let you know once 0.52.0 comes out with this functionality.

Great, thank you

**Comment by jqnatividad** [comment]
Hi @aborruso, the latest release is out with `schema --stdout` .

**Comment by aborruso** [comment]
> Hi @aborruso, the latest release is out with `schema --stdout` .

Once again, great.

Thank you
