### ISSUE TITLE
A valid CSV mapped as not valid?

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#370]
Hi,
if I run

```
qsv validate -d ";" input
```

on this [CSV](https://gist.github.com/33861712316d3a2c153c775f32db35b7), I have:

> Validation error: CSV error: record 1 (line: 1, byte: 205): found record with 18 fields, but the previous record has 23 fields. Try "qsv fixlengths" or "qsv fmt" to fix it.

But it seems correct to me. It has simply all the first rows of the last columns empty.
Am I wrong?

Thank you

![image](https://user-images.githubusercontent.com/30607/177556764-3f629d50-6a8c-41e5-9426-46839ef33b27.png)

**Comment by jqnatividad** [comment]
Hi @aborruso ,
It is indeed invalid. Looking at the file, the rows with the empty fields do not have delimiters between them, so it looks like those rows have 18 columns, and the other rows have 23 columns.

Using `fixlengths`, you can quickly "fix" this:

```
$ qsv fixlengths -d ";" > output
```

Notice though that the resulting "fixed" output file has "," as delimiters.

If you prefer to preserve ";" as your delimiter, you can do this instead:

```
$ qsv fixlengths -d ";" input | qsv fmt -t ";" > output 
$ qsv validate output
Valid: 1 columns ("Period;Zone_101;Zone_102;Zone_103;Zone_104;Zone_105;Zone_106;Zone_107;Zone_108;Zone_109;Zone_110;Zone_111;Zone_112;Zone_113;Zone_114;Zone_115;Zone_116;Zone_117;Zone_201;Zone_202;Zone_203;Zone_204;Zone_205") and 31 records detected.
```

**Comment by aborruso** [comment]
> It is indeed invalid. Looking at the file, the rows with the empty fields do not have delimiters between them, so it looks like those rows have 18 columns, and the other rows have 23 columns.

True, I made a wrong consideration. Thank you
