### ISSUE TITLE
A wrong CSV mapped as valid?

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#371]
Hi,
if I run

```
qsv validate -d ";" input.csv
```

on this [CSV](https://gist.github.com/36fd3f1cb3d9dbfb2dc433e0c5de05c6), I have no errors.

But it seems wrong to me. It has two cells in two fields without field name.
Am I wrong?

Thank you

![image](https://user-images.githubusercontent.com/30607/177558039-18ccb03e-b1df-41ab-a955-5b19009333cf.png)

**Comment by jqnatividad** [comment]
Yes @aborruso , by qsv's definition, that CSV file is valid as the number of columns in your header are equal to the number of columns in the data part of the CSV, even though the last two columns in your header row are blank/empty.

However, as soon as you remove the two trailing semicolons in your header row, the file is considered invalid.

**Comment by aborruso** [comment]
> even though the last two columns in your header row are blank/empty

You are right, it's rfc compliant. But as user, I think that a warning would make sense, because here it is evident that or someone has forgotten to enter the names of the two fields, or that an automatic processing has worked badly.

An alert whenever some fields have a title and others don't

My 2 cents


```
+-------+---------+--------+--------------------------------------------------+
| row   |   field | code   | message                                          |
+=======+=========+========+==================================================+
|       |      24 | blank- | Label in the header in field at position "24" is |
|       |         | label  | blank                                            |
+-------+---------+--------+--------------------------------------------------+
|       |      25 | blank- | Label in the header in field at position "25" is |
|       |         | label  | blank                                            |
+-------+---------+--------+--------------------------------------------------+
```
