### ISSUE TITLE
Don't read entire CSV in order to print headers

### ISSUE THREAD

**Issue by kyku** [jqnatividad/qsv#410]
In current version (0.61.1-mimalloc--12-12) printing headers of a very large CSV takes long because qsv appears to be reading entire contents of the file (found by strace and just by the time of the operation). XSV prints them right away.

**Comment by kyku** [comment]
@jqnatividad , the file is about 330M lines long. I do `zstd -dc file.csv.zst | xsv_or_qsv headers` to get the headers. xsv takes about 0,076s to print headers, qsv - after one minute I press control-c. Setting QSV_SKIPUTF8_CHECK=1 makes qsv print the headers instantaneously as with xsv. Does it makes sense to validate entire file only to print its headers? Maybe a better idea would be to validate only the header line?

**Comment by jqnatividad** [comment]
@kyku , just merged #418 and will create a new release today with the fix.

**Comment by kyku** [comment]
Seems to be fixed, thanks.
