### ISSUE TITLE
Glibc & Python library not found

### ISSUE THREAD

**Issue by useraccessdenied** [jqnatividad/qsv#415]
**Bug**
qsv binaries downloaded from release page of the repo are throwing the error as below. 
For linux-64bit-glibc
```
[~]$ qsv
qsv: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
[~]$ qsvlite
qsvlite: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by qsvlite)
qsvlite: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by qsvlite)
qsvlite: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by qsvlite)
qsvlite: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by qsvlite)
[~]$ qsvdp
qsvdp: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by qsvdp)
qsvdp: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by qsvdp)
qsvdp: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by qsvdp)
```
For linux-64bit-musl
```
[~]$ qsv
Segmentation fault (core dumped)
```
**To Reproduce**
Download latest (0.61.1) linux 64bit binaries.

**Expected behavior**
Should run

**Desktop:**
 - OS: CentOS 7 x86_64
 - qsv Version: 0.61.1

**Additional context**
I believe the shared libraries aren't bundled with the release of this version. I have tried few older versions too but they are too are not working.

**Comment by jqnatividad** [comment]
Thanks for the report @useraccessdenied.

For python, you need to have at least python 3.8 installed to use the prebuilt qsv binary.

For the glib not found messages, CentOS 7 seems to be on an older version of glibc.  Can you run `yum list glibc` to get the exact version?

And yeah, the MUSL build is supposed to take care of that by removing the glibc dependency, so I'll have to take a look into that.

Have you tried building from source? 

I primarily use macOS as my main daily driver, and use Windows 11 and Ubuntu Linux as well. I depend on GitHub's action runners to test on other cross-compiled platforms... 

Thinking about it, I may just add a "test binaries" step to the publishing workflow to ensure the prebuilt binaries are compiled properly...

**Comment by useraccessdenied** [comment]
Hi @jqnatividad, Here is the glibc version installed on my server.
```
Installed Packages
glibc.x86_64                                      2.17-326.el7_9                                      @updates
Available Packages
glibc.i686                                        2.17-326.el7_9                                      updates
```

I haven't tried building from source but I will try building musl variant and debug it. I generally use only musl builds to avoid such compatibility problems with Centos 7. Most of the libraries are outdated in it. CentOS 7 comes with python3.6 as the default and python3.8 needs to be built from source or downloaded from a 3rd party repositories.

**Comment by jqnatividad** [comment]
For python, if you want to stay with the CentOS's default python version of 3.6, you can download python3.8 or later and create a virtualenv using the more up-to-date python.

If you run qsv from that virtualenv, qsv will use the python version for that venv.

BTW, if you don't want to deal with python venv and python module dependency hell - I find lua is more performant than python and is good enough for data-wrangling workloads qsv was designed for anyway. You'll have to build from source though to drop the python feature.

**Comment by useraccessdenied** [comment]
I have successfully built v0.61.2 glibc and musl variants on CentOS 7. The GLIBC errors are now gone. After putting libpython on LD Path, even the python support was working well. On musl variant, the full featured version was seg faulting because libpython was not on LD path. qsvlite & qsvdp were working properly. So I believe there is no issue in your musl builds. It's just that the errors were unhelpful. 

Lua support is great but our team uses mostly python. So, is there is any way to bundle libpython as well? Then I will have complete static binary for distribution.

**Comment by jqnatividad** [comment]
Good to know @useraccessdenied .

FYI, I suspect the root cause of the MUSL errors was that the MUSL build was using the mimalloc allocator. I switched it back to use the standard allocator by setting `--no-default-features` when building.

Can you confirm if that's the case on your manual build? 

As for bundling python, [there is a way to do so](https://pyo3.rs/v0.16.4/building_and_distribution.html#embedding-python-in-rust) with [PyOxidizer](https://github.com/indygreg/PyOxidizer).

I'll put it in the backlog but I don't think I'll do it anytime soon as I want to keep qsv's flexibility to work with any ABI3 compatible version of python >= 3.8. But I'd be more than happy to accept a PR. :)

For now, I'll document the LDPATH workaround in the FAQ section.

Also, in addition to adding the detected python in the --version option, I'll try to see if I can add more helpful messages when python is not found.

**Comment by useraccessdenied** [comment]
I don't think the mimalloc allocator was the issue. qsvlite and qsvdp were working fine in 0.61.2 & 0.61.1 as well. Sorry, I forgot to mention this previously.

Let me check out your guides of linking the libpython and see what I am able to do.

**Comment by jqnatividad** [comment]
@useraccessdenied , you may want to check out the approach suggested here - 
https://github.com/PyO3/pyo3/issues/1396#issuecomment-767420362

Perhaps, you can wrap qsv with a shell script. 

As pointed out by Py03's core maintainer, there's really nothing we can do on the Rust side - "_due to the nature of linking, LDPATH is the only option you have. The symbols have to be resolved during program load time. By the time any Rust code starts executing, it's too late._"

**Comment by useraccessdenied** [comment]
Another alternative I found is to set `RPATH` to `$ORIGIN`. This will make qsv binary to look for libraries in the current folder as well. The current folder is given priority though. This will allow us to distribute without static linking.

I compiled qsv with this
`(base) [qsv]$ RUSTFLAGS="-C link-args=-Wl,-rpath,\$ORIGIN" cargo build --release --features all_full`

The resultant binary has this in its dynamic section
```
(base) [release]$ objdump -p qsv
Dynamic Section:
  ...
  RPATH                $ORIGIN
  ...
```

And the library is found properly too.
```
(base) [release]$ ldd qsv
	linux-vdso.so.1 =>  (0x00007fff987c0000)
	libpython3.9.so.1.0 => /home/gabbar/qsv/target/release/./libpython3.9.so.1.0 (0x00007f4c9f87a000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4c9f664000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f4c9f45c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4c9f240000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f4c9ef3e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f4c9ed3a000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4c9e96c000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f4c9e769000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4ca0ed4000)
```

I like this approach for portability much better and wonder why it is not the default. I know I am spoiled by the windows environment where dumping dll in the same folder makes the executable work.

What are your opinion on this?

**Comment by jqnatividad** [comment]
Hi @useraccessdenied ,

Thanks for sharing this as I do agree that this approach is more portable.

So I went ahead and added it to qsv. 😄 

https://github.com/jqnatividad/qsv/commit/3e1172c8b99b84d3ae2da380fad3f345371ca786

WDYT?

**Comment by useraccessdenied** [comment]
This is great! I just compiled it on CentOS and it worked as expected.

But I believe that python should not be enabled by default in the all_full variant. Instead, a separate binary should be built for python so that other features will not be held hostage if libpython is not found. Many new users might not have libpython on their paths and they will get confused by this.

Currently, I have built qsv with all_full variant except python in it. For python support, I have built a separate qsvpy binary with `-rpath,$ORIGIN`.

One more thing I noticed is that $ORIGIN is Linux specific RPATH variable. On MacOS, it didn't work as I was expecting it to. After a bit of searching, I found that MacOS uses `@loader_path` for the current directory. So, I changed the linker flag to `-rpath,@loader_path`, and then it worked. I need to check it out on Windows too. I believe it should work without any change.

**Comment by jqnatividad** [comment]
@useraccessdenied , tweaked cargo.toml based on your findings

https://github.com/jqnatividad/qsv/commit/92756ba21907c75ee6b5745b7ee9bebc758049a4

As for another qsv binary variant - I hear you. Will tweak the publishing workflow to do as you suggested.

**Comment by jqnatividad** [comment]
@useraccessdenied , check out 0.61.4.  It now has the `qsvnp` np for "no python" variant.

**Comment by useraccessdenied** [comment]
Thankyou @jqnatividad, for this. I just checked with windows version and it worked as expected.
Here are the sys.paths for windows executables: (My qsv directory is C:\\bin\\)
 sys.path = [
    'C:\\bin\\python39.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\bin',
  ]
