### ISSUE TITLE
Add a --quiet flag to seach to return 1 or 0 based on match?

### ISSUE THREAD

**Issue by harrisj** [jqnatividad/qsv#435]
**Is your feature request related to a problem? Please describe.**

For use in shell scripting, it would be nice if there was an option for search that would return a 1 if there was no match (eg, shell parlance for an error) or a 0 if there is a match (shell for success).

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
An alternative would be to pipe the output of the command to another command like `wc` and use that to see if there are 0 or more matches.

Name could be different, but I think there are similar options on other CLI commands

**Comment by jqnatividad** [comment]
@harrisj , I'll look into this. 

Perhaps, I can use [custom exit codes introduced in Rust 1.61.0](https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html#whats-in-1610-stable) in a consistent way for all the qsv commands.

**Comment by harrisj** [comment]
Thank you. I don't think it necessarily needs to be a 1 on failure, all the shell scripts care is [0 or 1-255 for error](https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html).

On grep, this argument is

```
       -q, --quiet, --silent
              Quiet; do not write  anything  to  standard  output.   Exit
              immediately with zero status if any match is found, even if
              an error was detected.  Also see the  -s  or  --no-messages
              option.
```

**Comment by jqnatividad** [comment]
@harrisj , [qsv 0.63.1](https://github.com/jqnatividad/qsv/releases/tag/0.63.1) is now available with your requested changes.

Please let me know how it works for you...

**Comment by harrisj** [comment]
Thank you, the exitcode does work! I was also curious if we could suppress output (it could even short-circuit)  although I can pipe to >/dev/null

Basically, I was asking because I have a CSV with a "hash" column and I wanted to see if a new entry collided with that by doing something like `qsv search -e -s hash e8e17c03af850d088b45ce833442771d ...` and the exit code is enough, I don't need stdout

**Comment by jqnatividad** [comment]
Good to know it works for your usecase @harrisj!  

As for suppressing output, you'll have to pipe to /dev/null for now, as I want to maintain the ability to compose data pipelines with qsv.

Also, I'll go ahead and send the match count to stderr when --exitcode is enabled (as I need it for a pipeline I'm working on 😄 ), but your idea of short-circuiting is a good one.  I'll add a --short-circuit option (that's only valid when --exitcode is used) to do so.

Of course, match count will not be sent to stderr when --exitcode and --short-circuit are both enabled.
