### ISSUE TITLE
BUG: qsv apply operations lower fails on piped csv or prints (unexpected) progress bar.

### ISSUE THREAD

**Issue by slonyik** [jqnatividad/qsv#437]
If you have a Usage question, an Idea for a new feature; or a qsv story you want to share, go to [Discussions](https://github.com/jqnatividad/qsv/discussions).   
GitHub Issues is primarily used for bug reports, and for tracking Ideas that have been added to the [Backlog](https://github.com/jqnatividad/qsv/projects/1) for implementation.
---
**Describe the bug**
The qsv apply operations lower 
a. prints progress bar (unexpected)
b. when input provided via pipe qsv crashes

**To Reproduce**
1.  create sample file:
```shell
cat >file<<'EOF'
header1
Row1
Row2
EOF
```
2. 
a. Run `qsv  apply operations lower header1 file` , it returns:
```
[00:00:00] [█████████████████████████ 100% of 2 records] (645.682/s)
header1
rrow1
row2
```
Piping to, for example `|qsv headers` fails like described in the issue "b."

b. ⚠ Run ` cat file |  ~/qsv.win.xxx/qsv  apply operations lower header1 `, it returns :

```
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\slice\mod.rs:895:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
header1
```

**Expected behavior**
👉 qsv does not crash and provides lowercase string of the selected column

**Screenshots/Backtrace/Sample Data**

The cmd ` cat file |  ~/qsv.win.xxx/qsv  apply operations lower header1 ` with `export RUST_BACKTRACE=full`
```
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\slice\mod.rs:895:9
stack backtrace:
   0:     0x7ff7d2d4938c - <unknown>
   1:     0x7ff7d28cbe2a - <unknown>
   2:     0x7ff7d2d3369a - <unknown>
   3:     0x7ff7d2d4add0 - <unknown>
   4:     0x7ff7d2d4bae7 - <unknown>
   5:     0x7ff7d2d4b6b3 - <unknown>
   6:     0x7ff7d2d4b619 - <unknown>
   7:     0x7ff7d2d4b5d4 - <unknown>
   8:     0x7ff7d2e762f5 - <unknown>
   9:     0x7ff7d28cbb3a - <unknown>
  10:     0x7ff7d2e66560 - <unknown>
  11:     0x7ff7d28526b6 - <unknown>
  12:     0x7ff7d285ba4a - <unknown>
  13:     0x7ff7d276d11d - <unknown>
  14:     0x7ff7d286ba36 - <unknown>
  15:     0x7ff7d2868f9c - <unknown>
  16:     0x7ff7d26d2896 - <unknown>
  17:     0x7ff7d2871744 - <unknown>
  18:     0x7ff7d2e61cbc - <unknown>
  19:     0x7ffe8c487034 - BaseThreadInitThunk
  20:     0x7ffe8d0c2651 - RtlUserThreadStart
header1
```

**Desktop (please complete the following information):**
 - OS: Windows 10 + cygwin
 - qsv Version: qsv 0.62.0-mimalloc-apply;fetch;generate;lua;python-3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]-12-12 (x86_64-pc-windows-msvc)

**Additional context**
none

**Comment by slonyik** [comment]
On the progress bar - 
To be honest -  as not all commands have progressbar - I would expect the progress bar displayed only when explicitly requested as CLI  ( ex: -p/--progress ?) option.

Maybe having an env variable QSV_PROGRESBAR to control whether progress bar shall be disabled or not ( default: no ) 

Forgot to mention - great _thanks_ for expanding on xsv by adding superb/missing features !🎆

**Comment by jqnatividad** [comment]
Hhmmm... thinking more about it, I agree that no progress bar should be the default.

That means changing the --quiet flag to --progressbar instead, and adding the QSV_PROGRESSBAR env var.

Much appreciate the thanks! 

TBH, I was just scratching an itch for a project I was working on at the time, used it to learn Rust, and got carried away-I'm now using it in several production data pipelines and including it in other projects!

**Comment by slonyik** [comment]
Thanks Joel, Hope you will be scratching more itches in future  as it helps others (me) as well ;-)

**Comment by jqnatividad** [comment]
Hi @slonyik , [qsv 0.63.1](https://github.com/jqnatividad/qsv/releases/tag/0.63.1) is now available with the stdin fix.

It also implements your progressbar suggestion Just run qsv without any parameters to self-update.

Let me know how it works for you...
