### ISSUE TITLE
Feature request: to use apply for multiple columns in one command

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#444]
**Describe the solution you'd like**
To be able to run

```
qsv apply datefmt 'fieldOne','fieldTwo' input.csv
```

Thank you very much

**Comment by udsamani** [comment]
@jqnatividad If you don't mind I can give it a try ?

**Comment by jqnatividad** [comment]
Of course not @udsamani... Go for it!

**Comment by udsamani** [comment]
@aborruso Just double clarifying here. You are looking to apply the command like :
```shell
qsv apply datefmt '<col1-header>', '<col2-header>' input.csv
```
Currently we just have support for taking in one column instead of multiple columns.

**Comment by udsamani** [comment]
@aborruso @jqnatividad  What should be the behavior in case of `--rename` for columns.  Let's say a user intends to uses the apply command in the following manner
```shell
qsv apply trim,uppercase -r uppercase_name,uppercase_surname names.csv
```

For rename if same number of columns are not provided then should we take 1-1 mapping and just rename whatever possible or ideology would be to fail ?

**Comment by aborruso** [comment]
I would prefer to have an error, about wrong number of columns.

My 2 cents

**Comment by jqnatividad** [comment]
Same here - an error should be raised.

Speaking of which @udsamani , I'm moving the `geocode` subcommand to its own command (see #96), so don't include it in the multi-column feature work you're doing. Just emit an error too when a multi-column geocode operation is attempted.

**Comment by udsamani** [comment]
Ack. Thanks for quick turnaround of the replies. I ll create a PR by end of this week. Just adding test cases.

**Comment by udsamani** [comment]
https://github.com/jqnatividad/qsv/pull/462 - PR

**Comment by aborruso** [comment]
> #462 - PR

thank you very much @udsamani

**Comment by jqnatividad** [comment]
Awesome @udsamani !  It works like a charm!

It will be the major new feature of the 0.66.0 release!
