### ISSUE TITLE
filter feature

### ISSUE THREAD

**Issue by alperyilmaz** [jqnatividad/qsv#449]
**Is your feature request related to a problem? Please describe.**
`filter` is part of data wrangling process and usually one of the steps 

**Describe the solution you'd like**
`qsv` is very fast and capable. but it lacks (arithmetic) filtering. String filtering can be achieved with `search` command but simple filtering such as `Population<100000` or `Age>50` is not possible (as far as I know). So, `qsv filter -f 'Age>50'` should be possibility 

**Describe alternatives you've considered**
* Obvious example is awk. `awk '$3 > 50'` will quickly filter according to third column values. 
* `csvtk` has both `filter` and `filter2` (latter is awk-like filtering). 
* Finally, `tsv-utils` has `tsv-filter` has an comprehensive (checking null, checking is.numeric, etc.) filtering. I added the help section for an example:

```
Operators:
* Test if a field is empty (no characters) or blank (empty or whitespace only).
  Syntax:  --empty|not-empty|blank|not-blank  FIELD
  Example: --empty name               # True if the 'name' field is empty

* Test if a field is numeric, finite, NaN, or infinity
  Syntax:  --is-numeric|is-finite|is-nan|is-infinity FIELD
  Example: --is-numeric 5 --gt 5:100  # Ensure field 5 is numeric before --gt test.

* Compare a field to a number (integer or float)
  Syntax:  --eq|ne|lt|le|gt|ge  FIELD:NUM
  Example: --lt size:1000 --gt weight:0.5  # ('size' < 1000) and ('weight' > 0.5)

* Compare a field to a string
  Syntax:  --str-eq|str-ne|istr-eq|istr-ne  FIELD:STR
  Example: --str-eq color:red         # True if 'color' field is "red"

* Test if a field contains a string (substring search)
  Syntax:  --str-in-fld|str-not-in-fld|istr-in-fld|istr-not-in-fld  FIELD:STR
  Example: --str-in-fld color:dark    # True if 'color field contains "dark"

* Test if a field matches a regular expression.
  Syntax:  --regex|iregex|not-regex|not-iregex  FIELD:REGEX
  Example: --regex '3:ab*c'     # True if field 3 contains "ac", "abc", "abbc", etc.

* Test a field's character or byte length
  Syntax:  --char-len-[le|lt|ge|gt|eq|ne] FIELD:NUM
           --byte-len-[le|lt|ge|gt|eq|ne] FIELD:NUM
  Example: --char-len-lt 2:10   # True if field 2 is less than 10 characters long.
           --byte-len-gt 2:10   # True if field 2 is greater than 10 bytes long.

* Field to field comparisons - Similar to field vs literal comparisons, but field vs field.
  Syntax:  --ff-eq|ff-ne|ff-lt|ff-le|ff-gt|ff-ge  FIELD1:FIELD2
           --ff-str-eq|ff-str-ne|ff-istr-eq|ff-istr-ne  FIELD1:FIELD2
  Example: --ff-eq 2:4          # True if fields 2 and 4 are numerically equivalent
           --ff-str-eq 2:4      # True if fields 2 and 4 are the same strings

* Field to field difference comparisons - Absolute and relative difference
  Syntax:  --ff-absdiff-le|ff-absdiff-gt FIELD1:FIELD2:NUM
           --ff-reldiff-le|ff-reldiff-gt FIELD1:FIELD2:NUM
  Example: --ff-absdiff-lt 1:3:0.25   # True if abs(field1 - field2) < 0.25
```

**Comment by jqnatividad** [comment]
Hi @alperyilmaz ,
Thanks for this detailed feature request.
And yes, I agree that filtering is an essential to the data-wrangling process.

That's why you have multiple options to do so:
* with the `lua` --filter option (I just added an example in the usage text)
* with the `py` --filter option
* as for the other operators in your request, check out the `apply` command. It has several subcommands that fulfill your exact requirements.

Originally, I was hoping to write more articles in the wiki showing qsv in action, but I've been too busy adding features to qsv 😄 .  I was also hoping there'd be more contributions to the wiki...

**Comment by alperyilmaz** [comment]
hi @jqnatividad thanks for quick reply. I really appreciate you keep this tool alive, keep improving it.. 
I didn't know about filtering by different means. Thanks for the example code, that helped a lot.

I'd like to add *select, filter, mutate, groupby* themed cookbook (inspired from R/tidyverse) but I'd need help from your side, since I have zero experience with Lua.

**Comment by jqnatividad** [comment]
That'd be awesome @alperyilmaz !

Please do add as many recipes as you like in the cookbook.

As for lua, I'm no expert myself - but it's quite handy and performant as a language - purpose-built for embedding into other applications.

Perhaps, you can start with the `py` command if you're more familiar with python?

**Comment by alperyilmaz** [comment]
hi @jqnatividad 
thanks for the pointer. I can try the python way. I'd be glad if I can contribute.
I did a small test, in wcp.csv file, I wanted to remove rows which have no population.
```
$ ime qsv py filter 'len(Population)>0' worldcitiespop.csv | wc -l
47981

real	1m18.989s
user	1m8.373s
sys	0m8.676s
```
it was slow and it used lots of RAM. So, if I understand correctly, the python needs to load everything to memory to process? In case of Lua, does it run per line?

Also, I was trying to use Python expression to check for None (Null, Nil, etc), the code below didn't give error but the result was wrong:
```
$ time qsv py filter 'Population is not None' worldcitiespop.csv | wc -l
3173959

real	0m54.335s
user	0m49.141s
sys	0m4.926s
```
So, are there limitations or constraints about what expressions be used with `qsv py filter` ?

**Comment by jqnatividad** [comment]
Hi @alperyilmaz ,

Here are my timings for the equivalent functions in python & lua.

Using python:
```
$ qsv py filter 'int(Population.strip() or 0) > 0' wcp.csv --progressbar > testpy2.csv
Detected python=3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)]
[00:00:25] [█████████████████████████ 100% of 2,699,354 records] (107,224.9207/s)

$ qsv count testpy2.csv
47004
```
Using lua:
```
$ qsv lua filter '(tonumber(Population) or 0) > 0' wcp.csv --progressbar > testlua.csv
[00:00:14] [█████████████████████████ 100% of 2,699,354 records] (185,608.9751/s)

$ qsv count testlua.csv 
47004
```

So yeah, lua is faster. It's also more memory-efficient, as the way I implemented the `py` command is to use one global GILPool, so the memory keeps adding up (see https://pyo3.rs/v0.16.4/memory.html#gil-bound-memory for an explanation).  That was a conscious decision, as the thinking is memory is cheap and qsv sessions are short-lived.

With yesterday's release of Py03 0.17, I'm looking to refactor the py command so it will be more memory-efficient without sacrificing too much performance.

**Comment by alperyilmaz** [comment]
Hi @jqnatividad  again.
Wow, you're such an amazing developer. Keep this up please :pray: .. Thanks for replying and whole-hearted discussion.

It was glad to know about `Population or 0` trick in both Python and Lua. 

As you mentioned, 160k records per second is fast enough. For the last question, there might be other cli tools which are faster (awk derivatives, sql-based approaches,etc.), but qsv is probably the fastest one which incorporates Python.

**Comment by jqnatividad** [comment]
Thanks for your generous words @alperyilmaz... I just stood on the shoulders of xsv and the numerous contributions of the community.

And we're not only just keeping it up - our company is going to give qsv a major power-up in the next month or so... stay tuned! 😉 

As for the py command taking a lot of memory, I'm currently working on adding a new `--release-mem` option for it to be more memory efficient (at the price of reduced performance) that should be available for the next release...

**Comment by jqnatividad** [comment]
Hi @alperyilmaz , I just refactored the `py` command so it processes the CSV in batches of 30,000 rows, instead of doing all 2.7m rows in one go.

So instead of consuming several gigabytes of memory while running , it now just tops out at around 80mb of memory on my 16gb M1 Mac Mini... 

And as it turns out, instead of taking a performance hit, performance actually improved by 30% and is now only a tad slower than lua! :rocket:

```
$ qsv py filter 'int(Population or 0) > 0' wcp.csv --progressbar > testpy2.csv 

# Before batch refactor:
Detected python=3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)]
[00:00:23] [█████████████████████████ 100% of 2,699,354 records] (116,415.4267/s) 

# After batch refactor:
Detected python=3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)]
[00:00:16] [█████████████████████████ 100% of 2,699,354 records] (161,825.4866/s)

**Comment by alperyilmaz** [comment]
Oh my! looks like it's not only qsv is blazing fast but also its development..
