### ISSUE TITLE
Adapt additional commands from @Yomguithereal xsv fork

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#45]
Hi @Yomguithereal!

Your fork has several commands that are quite useful that I'd like to pull in to qsv.

https://github.com/Yomguithereal/xsv#readme

Would it be OK if I do so?

**Comment by Yomguithereal** [comment]
Hello @jqnatividad. I don't have any issues with this as long as you keep my commits and don't take credit for them :). You should probably use those from the `prod-no-python` branch as the python commands can make the project difficult to build on some computers.

**Comment by jqnatividad** [comment]
Thanks @Yomguithereal!  Of course, all attribution will be maintained and I won't take credit for all your great work! :)

I'm just pulling in all the great innovation by the xsv community into this renamed fork as per https://github.com/BurntSushi/xsv/issues/267 while we wait for the xsv rewrite.

And thanks for pointing me to the `prod-no-python` branch. However, I'm actually quite keen to include the python command, and I'll take an initial stab of adding conditional compilation logic to see if it at least builds properly on different platforms.
