### ISSUE TITLE
Add Environment variables

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#47]
- [x] QSV_NO_HEADERS (in addition to the existing QSV_TOGGLE_HEADERS)
- [x] QSV_DELIMITER
- [x] QSV_FLEXIBLE (https://docs.rs/csv/1.1.6/csv/struct.ReaderBuilder.html#method.flexible) 
- [x] QSV_REGEX_UNICODE

Note: implementation of each env var will be tracked by a separate issue and checked off here as they are done.

**Comment by peterjc** [comment]
I strongly prefer TSV over CSV, so a big +1 on adding ``QSV_DELIMITER`` which I would set to tab, and avoid having to keep adding ``-d "\t"`` on piped inputs and using ``qsv fmt -t "\t"`` on my outputs.

**Comment by jqnatividad** [comment]
Not doing QSV_FLEXIBLE. 

Users are meant to use `fixlengths` - which works in flexible mode, to fix CSV files, which can then be used with other qsv commands.

**Comment by jqnatividad** [comment]
Done.  Logging, if implemented, will NOT use an environment variable. It will just check the log4rs yaml file.
