### ISSUE TITLE
stats option to limit precision/round  of resulting stats.

### ISSUE THREAD

**Issue by slonyik** [jqnatividad/qsv#472]
**Is your feature request related to a problem? Please describe.**
no problem :)

**Describe the solution you'd like**
add option ( called precision or trunc, truncate, round ) to limit precision of stats  example:
`qsv stats --round 2`   would round up stats to 2 decimal places.
the default behaviour: current/no rounding

**Describe alternatives you've considered**
postprocessing of results via script...

**Comment by jqnatividad** [comment]
Hi @slonyik ,
I implemented the `--round` option with a default of 4 decimal places.

WDYT?

**Comment by jqnatividad** [comment]
Released with 0.66.0

**Comment by slonyik** [comment]
Hi @jqnatividad 

tested and works ok 🎆:)
Just for reference I am putting the comment from the code


    // round using "Bankers Rounding" rule
    // https://docs.rs/rust_decimal/latest/rust_decimal/enum.RoundingStrategy.html#variant.MidpointNearestEven

https://github.com/jqnatividad/qsv/commit/402d56aa2a23bd9b4f75d7ed790bb6914a6ba502#diff-824046348311068fc0c2237be704930054a9fc00b5499eb2c2aa239fe1d154a3R433

so that it is clear it is a proper rounding ;-)

Thanks for the fast implementation !
