### ISSUE TITLE
Not able to use geocode in apply

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#476]
Hi,
I have this input.csv file

```
input,en_input
Torino,Turin
Roma,Rome
```

If I run 

```
qsv apply geocode en_input -f state --new-column output input.csv
```

I have

```
+--------+----------+--------+
| input  | en_input | output |
+--------+----------+--------+
| Torino | Turin    | Turin  |
| Roma   | Rome     | Rome   |
+--------+----------+--------+
```

In the output column I have a copy of the input field, not the geocoded state. Is it normal? What am I doing wrong?

Thank you

**Comment by aborruso** [comment]
My error.

I must have as input a coordinates column

```
input,en_input
Torino,"38,13"
Roma,"38,12"
```

and then in output I will have

```
+--------+----------+--------+
| input  | en_input | output |
+--------+----------+--------+
| Torino | 38,13    | Sicily |
| Roma   | 38,12    | Sicily |
+--------+----------+--------+
```

**Comment by jqnatividad** [comment]
Hi @aborruso,
The current functionality of the `apply geocode` is only limited to forward geocoding a WGS84 lat,long coordinate to the nearest city using an embedded copy of the Geonames city database.

See the geocode tests for more examples:
https://github.com/jqnatividad/qsv/blob/ac7bd7cc95f68dbba0862bfd602bd0d89eb709e7/tests/test_apply.rs#L1286-L1391

But I am planning to make geocoding a command of its own, so stay tuned. (#96).

In the meantime, if you want to do reverse geocoding, you can already do that using the `fetch` command, though you have to compose the API call yourself.

See `fetch` for an example:
https://github.com/jqnatividad/qsv/blob/ac7bd7cc95f68dbba0862bfd602bd0d89eb709e7/src/cmd/fetch.rs#L60-L86

**Comment by aborruso** [comment]
> In the meantime, if you want to do reverse geocoding, you can already do that using the `fetch` command, though you have to compose the API call yourself.

Wow, great!

Thank you for your time
