### ISSUE TITLE
Allow different sort order and type for different columns

### ISSUE THREAD

**Issue by plambert** [jqnatividad/qsv#480]
**Is your feature request related to a problem? Please describe.**
I often need to sort a CSV with certain fields ascending and others descending, where some fields are numeric and some are text.

**Describe the solution you'd like**
It would be great if I could specify the `-s` option to `qsv sort` with an optional prefix to each column that describes whether it should be sorted ascending or descending,  and should be treated as numeric or text.

**Describe alternatives you've considered**
I'm not aware of any good alternatives, except maybe writing my own custom sorting script to use in the pipeline.

**Additional context**
For example, it'd be great if I could do this: `qsv sort -s last_name,first_name,-date file.csv` and the result be sorted with the last and first name fields ascending, but the date field descending.

Or `qsv sort -R -s text_column,text_column_that_looks_like_numbers:t,+numeric_column:n` to sort with the text_column descending, text_column_that_looks_like_numbers descending and treated explicitly as text, and numeric_column ascending, and treated as numeric.

**Comment by jqnatividad** [comment]
Thanks @plambert for the clear request.

I'm afraid this won't be easy to implement on the existing `sort` command...

However, I've been meaning to leverage [polars](https://www.pola.rs/) for a while, and this looks like a good candidate for it...

Putting it in the backlog...

**Comment by ondohotola** [comment]
mlr can so something like that if I am not mistaken
