### ISSUE TITLE
More information on use of python scripts/examples

### ISSUE THREAD

**Issue by slonyik** [jqnatividad/qsv#504]
**Is your feature request related to a problem? Please describe.**
looking for sample execution of python scripts

The inline documentation 
```
  Load helper file with function to compute Fibonacci sequence of the column "num_col"
  $ qsv py map --helper-file fibonacci.py fib qsv_uh.fibonacci(num_col) data.csv
```
like
- is not clear on  what finobacci.py needs to look like.
- does it need to have return statement
- how parameters are used
- what "qsv_uh" is for 
- help lists "map --helper-file" and "map --helper" (the latter works)
- has progress bar implicitly (piping not possible) :/ similar to #437 
- returns "Detected python.... " extra line
- can python return multiple values (multiple columns) or just one (presume the latter)
- feat: would it be possible to reference columns by number, and ranges/selector

Use case : 
need to calculate cksum/md5um/ of some columns eg. first column is "id", and do md5sum of rest.
 
I had success with 
test.csv:
```
c1,c2,c3,c4
1,a2,a3,,a4
2,b2,b3,b4
3,c2,c3,c4
```

`qsv py map --helper  p.py f 'qsv_uh.f(c2,c3,c4)' test.csv`
with `p.py`:
```python
import hashlib
def f (*args):
    s=",".join(args);
    return(hashlib.md5(s.encode('utf-8')).hexdigest())
```
which returns:
```
Detected python=3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
[00:00:00] [█████████████████████████ 100% of 3 records] (1,253.2899/s)
c1,c2,c3,c4,f
1,a2,a3,a4,cb675342ed940908eef0844d17c35fab
2,b2,b3,b4,7d594b33f82bdcbc1cfa6f924a84c4cd
3,c2,c3,c4,6eabbfdbfd9ab6ae7737fb2b82f6a1af
```
works
so looks like params are 
`qsv py map --helper <new_col_name> 'qsv_uh.<python_fuction>(<column>[,<columns>])'` 

Thanks

**Comment by jqnatividad** [comment]
Hi @slonyik ,
Thanks for the report..  I'll get back with a detailed response later, but here's an example of the `--helper` option from the CI test:

https://github.com/jqnatividad/qsv/blob/03e895fad712304ab83a61fd692b486c0c705387/tests/test_py.rs#L123-L208

And yeah, more documentation is needed for qsv in general. Originally, I was hoping there would be more contributions to the [Cookbook](https://github.com/jqnatividad/qsv/wiki), but I think I need to seed it with more examples and a concrete call to action for contributions.

**Comment by jqnatividad** [comment]
Hi @slonyik ,
I fixed most of the issues you raised, and even included your example in the usage text :)

* `--progressbar` its now optional by default as a result of #437 , and having them with piped input is just not possible (as we need to get a count of rows for progressbar). Just use `tee` to get around this limitation if you want progressbars with piped input.

* Python version info is now only display when debug logging is on

* for python supporting multiple return values, that's an interesting feature and I can certainly put that in the backlog

* referencing columns by position and row number is already possible. As for referencing columns using ranges/selector, that's an interesting feature request.  Can you create a dedicated feature request for that?
