### ISSUE TITLE
BUG extsort --help does not return help

### ISSUE THREAD

**Issue by slonyik** [jqnatividad/qsv#506]
If you have a Usage question, an Idea for a new feature; or a qsv story you want to share, go to [Discussions](https://github.com/jqnatividad/qsv/discussions).   
GitHub Issues is primarily used for bug reports, and for tracking Ideas that have been added to the [Backlog](https://github.com/jqnatividad/qsv/projects/1) for implementation.
---
**Describe the bug**
`qsvlite extsort --help`
does not return the help, lists "Invalid arguments" error:
```
Invalid arguments.

Usage:
    qsv extsort [options] <input> <output>
```

QSV version: 
`qsvlite 0.68.0-mimalloc--6-6 (x86_64-unknown-linux-gnu compiled with Rust 1.63) compiled`

https://github.com/jqnatividad/qsv/blob/master/src/cmd/extsort.rs 
shows the USAGE is defined in the code.
Also the usage is correctly displayed in `qsv 0.62.0-mimalloc-apply;fetch;generate;lua;python-3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15)  [MSC v.1929 64 bit (AMD64)]-12-12 (x86_64-pc-windows-msvc)`

**To Reproduce**
1. compile qsvlite
2. run qsvlite extsort --help

```
git clone https://github.com/jqnatividad/qsv
cd qsv
cat >Dockerfile<<'eof'
FROM rust:latest as builder

WORKDIR /qsv
COPY . .

RUN cargo build --release --features lite
RUN /qsv/target/release/qsvlite -v
eof
docker build -t qsv:latest .
docker run -it qsv  target/release/qsvlite extsort --help

```

**Expected behavior**
Prints the help page for extsort

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - qsv Version qsvlite 0.68.0-mimalloc--6-6 (x86_64-unknown-linux-gnu compiled with Rust 1.63) compiled

**Comment by jqnatividad** [comment]
Thanks for the report @slonyik .

https://github.com/jqnatividad/qsv/commit/c0ed469b4e18bce0eb40f140035ef323da0c99e1 fixes this.
