### ISSUE TITLE
[FEATURE] Allow spaces and blank/empty strings as arguments

### ISSUE THREAD

**Issue by Prid13** [jqnatividad/qsv#515]
### Problem
Wanted to replace spaces _within_ strings (not at the ends) with empty strings to effectively _remove_ them:
`www. google .com` -> `www.google.com`
But the CMD in Windows wouldn't accept whitespaces or empty strings to be passed as arguments, nor within Batch files. Those were just interpreted as missing arguments and thus complained about invalid number of arguments.

### Attempts
- ❌ `qsv apply operations replace column -C " " -R "" test.csv`
- ❌ `qsv apply operations replace column -C   -R  test.csv`
- ❌ `qsv apply operations replace column -C ^  -R ^ test.csv`
- ❌ `qsv apply operations regex_replace column -C \s -R "" test.csv`
- ✅ `qsv apply operations regex_replace column -C \s(\S*) -R $1 test.csv`

The regex replace with capturing groups actually worked, but idk, using regex just to remove spaces from thousands of lines seems inefficient

### Solution
Would love a way to pass blank strings or spaces as arguments in a way that's compatible with the native OS cmd rules :)

**Comment by jqnatividad** [comment]
Hi @Prid13 ,
https://github.com/jqnatividad/qsv/pull/518 adds these operations to `apply`:
* squeeze0
* strip_prefix
* strip_suffix



Perhaps, you can just use `squeeze0` for your use case?

**Comment by Prid13** [comment]
Awesome. `squeeze0` seems to fit my use case perfectly :)

**Comment by jqnatividad** [comment]
Closing this for now @Prid13 as doing the original request is really something we can't do with docopt.

I may revisit this feature request later by having a special reserved literal for empty strings for ALL qsv commands.
