### ISSUE TITLE
Concatenating rows from mismatcing csv files driven by header lines

### ISSUE THREAD

**Issue by vi** [jqnatividad/qsv#527]
**Is your feature request related to a problem? Please describe.**

`qsv cat row`, like `xsv cat row`, seems to work only in simple cases, when number of columns is always the same and columns are in the same order.

I think it may be beneficial to have trickier mode where it scans header lines of all involved files and concatenates rows driven by matching column names in those header lines.

```
$ cat > 1.csv
a,b
1,2

$ cat > 2.csv
b,a
2,1

$ qsvlite cat rows 1.csv 2.csv
a,b
1,2
2,1  (Expected: 1,2)
```

**Describe the solution you'd like**

`qsv cat rows` should have option like `--header-driven` to switch to this complex mode. `fixlengths` would be implied in this mode.

**Describe alternatives you've considered**

I rolled my own tool for this: https://github.com/vi/csvcatrow

**Comment by jqnatividad** [comment]
Hi @vi,

This is an interesting, useful feature request.

Perhaps, since you already implemented it in csvcatrow, you can create a PR to implement `--header-driven`? 😉

**Comment by vi** [comment]
Maybe someday, e.g. when I also need another unrelated additional to `qsv`.
