### ISSUE TITLE
non-lite pre-built qsv versions fail to start due to Python.

### ISSUE THREAD

**Issue by vi** [jqnatividad/qsv#528]
---
**Describe the bug**

Pre-built version of qsv downloaded from Github fails to run on Debian Bullseye due to some Python issues.

**To Reproduce**
1. Download and unpack qsv 0.69.0 from Github releases
2. Try running Python-dependent i.e. non-lite version.

**Expected behavior**

It works. Or at least functions not requiring Python work.

**Actual behavior**

```
$ LD_LIBRARY_PATH=/opt/qsv /opt/qsv/qsv --version
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/opt/hostedtoolcache/Python/3.10.7/x64'
  sys.base_exec_prefix = '/opt/hostedtoolcache/Python/3.10.7/x64'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/opt/hostedtoolcache/Python/3.10.7/x64'
  sys.exec_prefix = '/opt/hostedtoolcache/Python/3.10.7/x64'
  sys.path = [
    '/opt/hostedtoolcache/Python/3.10.7/x64/lib/python310.zip',
    '/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10',
    '/opt/hostedtoolcache/Python/3.10.7/x64/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f923b017980 (most recent call first):
  <no Python frame>

$ python --version
Python 3.9.2
```

---

Do I correctly assume that even if it works, it spends time initializing Python environment even for lightweight commands like `qsv dedup`?

**Comment by jqnatividad** [comment]
This is the expected behavior.

That's why we have non-python enabled variants of the prebuilt qsv binaries, as it's **linked** against Python 3.10.

So you'll have to have Python 3.10 installed for it to work even with qsv commands that don't require Python - see https://github.com/jqnatividad/qsv#python for more details.

So if you need it to run qsv using your preferred version of Python, you'll have to do a `cargo install` or `cargo build` from source.

**Comment by vi** [comment]
Why is there `libpython3.10.so.1.0` in the distribution then?
I assumed qsv release just contains Python 3.10 it needs.

---

Maybe Python-enabled version of `qsv` should be called like `qsv_py`, and usual version should be called just `qsv`?
