### ISSUE TITLE
`jsonl` command panics when encounters invalid JSON

### ISSUE THREAD

**Issue by vi** [jqnatividad/qsv#529]
**Describe the bug**

`qsv jsonl mytable.csv` panics when fails to parse the data as JSON.
Expected regular error (not a panic), ideally also ignorable on line-per-line basis.

**To Reproduce**

```
$ qsvlite jsonl <(echo a)
thread 'main' panicked at 'Could not parse line as JSON!: Error("expected value", line: 1, column: 1)', src/cmd/jsonl.rs:138:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**

Something like

```
$ qsvlite jsonl <(echo a)
Error: Could not parse line 1 of file /dev/fd/63 as JSON!: Error("expected value", line: 1, column: 1)
Use `--ignore-errors` option to skip malformed input lines.
Use `tojsonl` command to convert _to_ jsonl instead of _from_ jsonl.
```

**Comment by jqnatividad** [comment]
Thanks for the bug report/feature request @vi 

I fixed it and implemented the --ignore-errors option as requested.

Lemme know how it works for you!
