### ISSUE TITLE
`tojsonl` scans the file multiple times, but accepts stdin as input.

### ISSUE THREAD

**Issue by vi** [jqnatividad/qsv#530]
**Describe the bug**

`qsv tojsonl` seems to need to open input files multiple times to work. Yet it accepts `-` as input argument instead of showing warning or error.

**To Reproduce**

(`^D` denotes EOF)

```
$ qsvlite tojsonl -
a,b
1,2
^Da,b
1,2
^Da,b
1,2
^D
{"a":1,"b":2}

$ qsvlite tojsonl -
a,b
1,2
^D^D
Failed to infer field types via stats and frequency: Input is empty.

$ qsvlite tojsonl -
a,b
1,2
^Da,b
1,2
^D^D
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/slice/mod.rs:895:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**

Either error message is displayed when input is not seekable/reopenable/`-` or it switches to buffered mode and proceeds in one scan.
Also inconsistent input files (and other filesystem-related problems) should probably not be panics, just regular errors.

**Comment by jqnatividad** [comment]
@vi, thanks for your detailed report.

`tojsonl` is supposed to scan the input multiple times so it can infer the schema and use the right data types when creating the jsonl file.  And it can accept stdin as input, creating a temporary file so it can scan it multiple times.

But there was indeed a bug when qsv checks for utf8 encoding on stdin and it was panicking on an empty stdin buffer. #536 fixes that.

I also added better error-handling for `tojsonl`.
