### ISSUE TITLE
Enable arbitrary posting for fetchpost -> new command: `fetchpostj`

### ISSUE THREAD

**Issue by andrejohansson** [jqnatividad/qsv#544]
**Is your feature request related to a problem? Please describe.**
When using fetchpost today the data is sent form encoded and with the header `application/x-www-form-urlencoded`. It would be nice if we could send arbitrary content headers and arbritrary content data instead.

For example, posing a json payload per csv row to the endpoint and setting content type header to `application/json`. I know I can set headers today but I cannot change the posted data format.

**Describe the solution you'd like**

1. Add a parameter to let us define a payload template, for example in [mustcache format](https://mustache.github.io/) (or handlebar or other template language)
2. Expose all csv row columns as variables (eg. column `country` can be used in template as `{{country}}`
3. For each csv row, render the template and post it

**Comment by jqnatividad** [comment]
This is an interesting feature request @andrejohansson and can appreciate its utility.

I'll add it to the backlog.

**Comment by jqnatividad** [comment]
This will be implemented as the new `fetchpostj` command.

**Comment by jqnatividad** [comment]
Reopening... still planned, just need time... bad github-actions bot!

**Comment by jqnatividad** [comment]
Just to close the loop on this one - there is no need for a new `fetchpostj` command.

`fetchpost` can now post just about any content-type, so long as the requisite MiniJinja template is created for it.
