### ISSUE TITLE
`tojsonl` does not escape newlines and double quotes in field

### ISSUE THREAD

**Issue by thanhbinh01234** [jqnatividad/qsv#552]
**Describe the bug**
When using `tojsonl`, qsv does not escape newline and quote character, leading to invalid output.

**To Reproduce**
```bash
$ echo "a,b\n1,\"2\n3\"\"\"" | qsv tojsonl
{"a":1,"b":"2
3""}
```
**Expected behavior**
Newline and quote is escaped.
```bash
echo "a,b\n1,\"2\n3\"\"\"" | qsv tojsonl
{"a":1,"b":"2\n3\""}
```

**Comment by jqnatividad** [comment]
Thanks for the report @thanhbinh01234 ,

I just fixed it with #553. Let me know how it works for you...
