### ISSUE TITLE
Linux Homebrew Installer

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#578]
**Is your feature request related to a problem? Please describe.**
Be able to install qsv easily on the major Linux distros (Ubuntu, Debian, RedHat, CentOS, Fedora, etc.) with a bistro-agnostic installer.

**Describe the solution you'd like**
Be able to use Homebrew for Linux

**Additional context**
The macOS Homebrew installer has already been developed (#215). Leverage that work for Linux.

**Comment by jqnatividad** [comment]
Cancel that... the existing Homebrew formula should already work on Linux. :)

**Comment by minhajuddin2510** [comment]
@jqnatividad  It's working
