### ISSUE TITLE
BUG qsv 0.71.0 fails to load Python library stored in same directory.

### ISSUE THREAD

**Issue by derekmahar** [jqnatividad/qsv#584]
**Describe the bug**

qsv 0.71.0 fails to load Python library stored in same directory.

**To Reproduce**

1. Copy `qsv` and included Python 3.11 library object files to $HOME/bin.
2. `cd $HOME/bin; ./qsv`
3. `qsv` fails to run and reports that it cannot load shared library `libpython3.11.so.1.0`.

**Expected behavior**

I expected `qsv` to print the help page.

**Sample Output**
```
derek@tb350-btc:~/bin$ ./qsv
./qsv: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory
derek@tb350-btc:~/bin$ ls -la
.rwxr-xr-x  33M derek  8 Nov 15:43 libpython3.11.so
.rwxr-xr-x  33M derek  8 Nov 15:43 libpython3.11.so.1.0
.rwxr-xr-x  16k derek  8 Nov 15:43 libpython3.so
.rwxr-xr-x  20M derek  8 Nov 15:41 qsv
.rwxr-xr-x 7.7M derek  8 Nov 15:41 qsvdp
.rwxr-xr-x 8.9M derek  8 Nov 15:41 qsvlite
.rwxr-xr-x  20M derek  8 Nov 15:41 qsvnp
derek@tb350-btc:~/bin$ uname -a
Linux tb350-btc 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
derek@tb350-btc:~/bin$ python3 --version
Python 3.8.10
```

**Desktop:**

- Architecture: x86_64
- OS: Ubuntu Server 20.04.1
- Python 3.8.10
- qsv 0.71.0

**Additional context**

Invoking `cargo install qsv --locked --features all_full` to install `qsv` from source is successful.

**Comment by jqnatividad** [comment]
Thanks for the report @derekmahar .

I think at this point, I'll just skip bundling python and leaving the python feature out of the prebuilt binaries - it's just too problematic.

I thought bundling the python shared libraries would help, but it's been more of a problem.

I'll rebuild the 0.71.0 binaries and ping you when its ready.

**Comment by jqnatividad** [comment]
With the release of 0.71.1, we're no longer enabling the `python` feature by default because of how problematic it can be distributing the qsv prebuilt with the python shared libraries.

Closing this "bug" for now.

Will revisit enabling python by default in the future once we figure out a bulletproof way of bundling the python shared libraries.
