### ISSUE TITLE
Remove leading dollar signs from example scripts in the Cookbook?

### ISSUE THREAD

**Issue by derekmahar** [jqnatividad/qsv#588]
May I remove the leading dollar signs from the example scripts in the [Cookbook](https://github.com/jqnatividad/qsv/wiki/Cookbook) so that qsv users may copy-and-paste the examples without any changes?

**Comment by jqnatividad** [comment]
Sure @derekmahar ... go for it!

**Comment by derekmahar** [comment]
Done.
