### ISSUE TITLE
qsv validate does not create valid and invalid output

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#612]
Hi,
if I run

```
qsv validate --valid v --invalid i -p progetto_cup_pnrr.csv progetto_cup_pnrr.csv.schema.json
```

I have no CSV valid and invalid files.

I think it's a bug.

Thank you

**Comment by jqnatividad** [comment]
@aborruso thanks for the report.

Can you provide the csv and schema files you used in the example above so I can reproduce the error?

**Comment by aborruso** [comment]
> Can you provide the csv and schema files you used in the example above so I can reproduce the error?

The CSV https://gist.githubusercontent.com/aborruso/ebfeb8ee4fa06bc7a7bc1fd62359240a/raw/3f39868ba5fdd0692d501710a3389c6a8dcb31b0/test.csv

The schema https://gist.githubusercontent.com/aborruso/1a5b2834c7f17fc651edd020b290bdaa/raw/efc4461fd8cc20b174c52a4b645eede9f1ec13ac/progetto_cup_pnrr.csv.schema.json

My command 

```
qsv validate --valid v --invalid i -p test.csv progetto_cup_pnrr.csv.schema.json
```

I have no output

**Comment by aborruso** [comment]
Thank you very much
