### ISSUE TITLE
qsv validate: add jsonl output -> new command: `fixdata`

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#613]
Once I have created a schema file, it would be great to use it to create a useful output.

In example if I have CSV with a wrong qsv inferencing (a column that contains `01` often is mapped as integer, and it's a string), I could use a right schema to export a JSONL in which I have `{"fieldA": "01"}` and not `{"fieldA": 1}`.

Validate could be a tool to augment an input, creating an output that could be worked on better.

Thank you

**Comment by aborruso** [comment]
I think only WOW!!!!!

It would be a great thing, for all us that work on data and data quality.

You are great

**Comment by jqnatividad** [comment]
`fixdata` will also maintain a log file json file detailing for each "fixed" row:
* the row number
* the old data
* the "fixed" data
* the JSON Schema validation rule used

**Comment by aborruso** [comment]
@jqnatividad what a great things!!

Thank you

**Comment by jqnatividad** [comment]
In addition, if the schema says the field is a date, and the value is a number, it will convert the number to a date.

This is so CSV files produced by the `excel` command without date-inferencing can be "fixed" to become dates.

**Comment by aborruso** [comment]
Thank you @jqnatividad I have added a new issue in some way related to this one: https://github.com/jqnatividad/qsv/issues/646

**Comment by jqnatividad** [comment]
https://github.com/jqnatividad/qsv/pull/902 sets the stage to finally work on this.

**Comment by jqnatividad** [comment]
ensure that we can also `fixdata` using a JSON schema on a url.
