### ISSUE TITLE
better input

### ISSUE THREAD

**Issue by kpym** [jqnatividad/qsv#618]
**My problerm**
1. If the csv uses a delimiter without a comma, we need to run `sniff` first to find out the delimiter and then specify it by hand as a `-d` parameter to `input` or other commands.
1. When `-d` is set to `;` for example, this is very often because the decimal separator in many countries is `,`. Currently, `input -d ';'` converts `1,2` to `"1,2"` (in quotes), but I'm waiting for it to be converted to `1.2`.

**Desired behavior**
1. Introduce the `--auto` parameter, which uses `sniff` to guess all unspecified parameters.
1. When the field separator is not `,`, the decimal separator should default to `,`.   

**Remarks:** 
1. In countries where `,` is the decimal separator, the field separator is chosen to be another character (most often `;`) and this is the main reason for not using `,` as the field separator (except for `\t` which is used independently of the decimal separator). 
1. Perhaps input should also remove the [thousands separator](https://en.wikipedia.org/wiki/Decimal_separator).

**Comment by jqnatividad** [comment]
Hi @kpym ,
Thanks for the report.

First off, have you tried using the environment variables `QSV_DEFAULT_DELIMITER` and `QSV_SNIFF_DELIMITER`?

`QSV_SNIFF_DELIMITER`, like the suggested `--auto` option, uses sniff during startup to automatically detect the delimiter.

As for 2, I'll have to look into it further. Do you mind providing some sample files I can use and perhaps even integrate into the CI tests?

As you can see, qsv has a pronounced USA-specific defaults. I've started making it more localizable (with the `--prefer-dmy` option and env var for instance), but I need to do more, like with the thousands separator.

**Comment by kpym** [comment]
- Here is one possible example (`test.fr.csv`)
  ```csv
  Un;Deux, avec virgule;"Voilà un troisième"
  1,1;Texte, avec vigrule;1.01
  -2,;"Un autre, avec virgule";2.02
  -,3;Un sans virgule;3.03
  ```

- The expected conversion to strict "standard" (en) csv:
  ```csv
  "Un","Deux, avec virgule","Voilà un troisième"
  1.1;"Texte, avec vigrule";"1.01"
  -2.;"Un autre, avec virgule";"2.02"
  -.3;"Un sans virgule";"3.03"
  ```

- More relaxed interpretation could be to let the third column as is (numeric) because it can happens (in badly formated csv) that some columns use `.` as digital separator.
  ```csv
  Un,"Deux, avec virgule",Voilà un troisième
  1.1;"Texte, avec vigrule";1.01
  -2.;"Un autre, avec virgule";2.02
  -.3;Un sans virgule;3.03
  ```

- For this file `qsv sniff` fails:
  ```bash
  > qsv sniff test.fr.csv 
  sniff error: Sniffing failed: unable to find valid delimiter
  ```

- And when run with `-q ';'` we get 
  ```bash
  > cat test.fr.csv | qsv input -d ';'
  Un,"Deux, avec virgule",Voilà un troisième
  "1,1","Texte, avec vigrule",1.01
  "-2,","Un autre, avec virgule",2.02
  "-,3",Un sans virgule,3.03
  ```

I hope this can help.
Thanks for considering my request. 🙏

**Comment by jqnatividad** [comment]
Hi @kpym ,
Sorry it took me a while to get back to you.

* `qsv sniff` now works for the test file:
```bash
> qsv sniff test.fr.csv --pretty-json
{
  "delimiter_char": ";",
  "header_row": true,
  "preamble_rows": 0,
  "quote_char": "none",
  "flexible": false,
  "is_utf8": true,
  "num_records": 3,
  "num_fields": 3,
  "fields": [
    "Un",
    "Deux, avec virgule",
    "\"Voilà un troisième\""
  ],
  "types": [
    "Text",
    "Text",
    "Float"
  ]
}
```

* And when running `qsv input` with delimiter set to `;`:
```bash
cat test.fr.csv| qsv input -d ';' | qsv table
Un   Deux, avec virgule      Voilà un troisième
1,1  Texte, avec vigrule     1.01
-2,  Un autre, avec virgule  2.02
-,3  Un sans virgule         3.03
```

* And with QSV_SNIFF_DELIMITER set:
```bash
> export QSV_SNIFF_DELIMITER=1
> qsv input test.fr.csv | qsv table
Un   Deux, avec virgule      Voilà un troisième
1,1  Texte, avec vigrule     1.01
-2,  Un autre, avec virgule  2.02
-,3  Un sans virgule         3.03
```

* However, `QSV_SNIFF_DELIMITER` does not work with stdin:
```bash
> unset QSV_SNIFF_DELIMITER
> cat test.fr.csv | qsv input | qsv table
Invalid CSV. Last valid row (2): CSV error: record 1 (line: 2, byte: 45): found record with 3 fields, but the previous record has 2 fields
Un;Deux  " avec virgule;""Voilà un troisième"""
```
   
     
On a related note, I added a `--delimiter` option to `sniff` as a way to force it to use a delimiter, as the delimiter-guessing algorithm can sometimes be wrong if not enough delimiters are present in the sample. https://github.com/jqnatividad/qsv/pull/732

I also recently added a `thousands` separator operation to `apply` that you may find useful - https://github.com/jqnatividad/qsv/pull/748

**Comment by kpym** [comment]
@jqnatividad Thank you for considering my request! 🙏 
This looks very promising.

**Comment by jqnatividad** [comment]
My pleasure! Refined the `apply thousands` operation further with https://github.com/jqnatividad/qsv/pull/749

**Comment by jqnatividad** [comment]
@kpym , closing this for now. Please create a new issue if you have another request.
