### ISSUE TITLE
Pre-built Linux version does not run on Debian Stable

### ISSUE THREAD

**Issue by vi** [jqnatividad/qsv#639]
**Describe the bug**

```
$ /opt/qsv/qsvlite --version
/opt/qsv/qsvlite: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/qsv/qsvlite)
/opt/qsv/qsvlite: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/qsv/qsvlite)
/opt/qsv/qsvlite: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/qsv/qsvlite)

$ apt policy libc6
libc6:
  Installed: 2.31-13+deb11u4
```

**Expected behavior**

Downloaded version works for most distros (i.e. it is built using some older sysroot than the cutting edge).
Alternatively, supported or tested distro versions are listed in Github release notes.

**Desktop (please complete the following information):**
 - OS: Linux Debian 11, x86_64
 - qsv Version: `0.76.3-mimalloc-apply;fetch;foreach;generate;self_update-12-12 (x86_64-unknown-linux-musl compiled with Rust 1.65) prebuilt`

**Workaround**

Use musl version of qsv.

**Comment by jqnatividad** [comment]
Thanks @vi for the suggestion.

I'll be sure to add a README to the prebuilt zip archives documenting supported/tested distro versions - perhaps, we can even get the telemetry we collect from the hw_survey to generate the list.

https://github.com/jqnatividad/qsv/blob/f450a3d10841c9266eedbaf7047dddd269effcdb/src/util.rs#LL635

Also, to mention to use the must version if their OS does not have the required glibc libraries.

**Comment by jqnatividad** [comment]
Thanks for the heads-up @vi .

qsv only collects general HW/OS data similar to [Steam's Hardware Survey](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam), but still, I'll make it user-triggered as part of `qsv --update`.

Also, `self-update` has a feature-flag, and folks can compile from source if they want to remove it altogether.

FYI, the survey was originally part of a qsv benchmark suite revamp (#98), where I wanted to give qsv users the ability to run benchmarks on their hardware, and send the results along with their HW/OS configuration...
