### ISSUE TITLE
does not compile on Mac M1 Ventura

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#643]
**Describe the bug**

`cargo install qsv --features all_full` fails

**To Reproduce**

`cargo install qsv --features all_full` on M1

**Expected behavior**

previously it compiled

**Screenshots/Backtrace/Sample Data**
```
  [...]
   Compiling qsv v0.76.3
error: couldn't read /Users/el/.cargo/registry/src/github.com-1ecc6299db9ec823/qsv-0.76.3/src/cmd/../../resources/luau/vendor/luadate/date.lua: No such file or directory (os error 2)
   --> /Users/el/.cargo/registry/src/github.com-1ecc6299db9ec823/qsv-0.76.3/src/cmd/luau.rs:195:27
    |
195 |     let luadate_library = include_bytes!("../../resources/luau/vendor/luadate/date.lua");
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `qsv` due to previous error
error: failed to compile `qsv v0.76.3`, intermediate artifacts can be found at `/var/folders/mp/9p6_x0pd27jdgcnrx6tx35tw0000gp/T/cargo-installsDHozm`
```
**Desktop (please complete the following information):**
 ```
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
```
```
qsv v0.76.3
cargo 1.65.0 (4bc8f24d3 2022-10-20)
```

**Additional context**
The Intel version of v0.76.3 runs on the M1 13.0.1 (under Rosetta presumably)

**Comment by ondohotola** [comment]
```cargo install --features all_full --path $(pwd)```

works from the source download directory

**Comment by jqnatividad** [comment]
Thanks for the report @ondohotola .

I'll be sure to package the vendor Lua file so you can use cargo install...

**Comment by ondohotola** [comment]
Thank you.

That would become available in the next version then? Tried it today, did not work yet.

But, as above the compile from source works, so no drama until then.

**Comment by jqnatividad** [comment]
Yes @ondohotola , I just enabled it on 0.77.0.

Please confirm if it works as expected.

**Comment by ondohotola** [comment]
Joel,

thank you.

And I confirm :-)-O

el

On 09/12/2022 13:57, Joel Natividad wrote:
> Yes @ondohotola, I just enabled it on 0.77.0.
> 
> Please confirm if it works as expected.
[...]

-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply
