### ISSUE TITLE
Add a subrule to field inferencing

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#646]
Hi,
daily I work with data where some columns have only numerical values in the cells, but which are actually string fields.

A typical case is that of administrative codes, of regions, provinces and cities. In Italy (in example in the file below) these are some official regions code:  the Lombardy has the code `03`, and obviously it's a string.
But if you run `stats` on it, the field `state_code` is mapped wrongly as integer.

| field | type | sum | min | max | min_length | max_length | mean | stddev | variance | nullcount |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| state_code | Integer | 71 | 2 | 20 | 2 | 2 | 10.1429 | 7.7354 | 59.8367 | 0 |
| label | String |  | Aosta Valley | Veneto | 6 | 29 |  |  |  | 0 |

I know, octal numbers exist, but in 99% of cases (I'm talking about my experience), if I have fields with cells starting with zero they are not octal numbers, but string codes.

If it were possible I would add a subrule for all fields mapped as numbers: if there are cells that start with a zero,  not followed by a `,` or `.`, set that inferenced field as `string` and not as `number`.

Thank you.

## Example file

```
state_code,label
19,Sicily
18,Calabria
20,Sardinia
02,Aosta Valley
03,Lombardy
04,Trentino-Alto Adige/Südtirol
05,Veneto
```

**Comment by aborruso** [comment]
Thank you very much.

Does it works both in stats and in schema?
Is it in some way general?

**Comment by jqnatividad** [comment]
Yes @aborruso , it works the same way for both stats and schema.

Let me know how it works for you!

**Comment by aborruso** [comment]
How to compile qsv

**Comment by jqnatividad** [comment]
```
git clone git@github.com:jqnatividad/qsv.git
cd qsv
cargo build --release --locked --features all_full
```

**Comment by aborruso** [comment]
@jqnatividad thank you. I have this error

```
error: failed to select a version for the requirement `ahash = "^0.8"`
candidate versions found which didn't match: 0.8.0, 0.7.6, 0.7.5, ...
location searched: crates.io index
required by package `qsv v0.77.0 (/home/aborruso/lavagna/qsv)`
```

**Comment by aborruso** [comment]
> Interesting, can you try it again with the 0.78.0?

The same

```
error: failed to select a version for the requirement `ahash = "^0.8"`
candidate versions found which didn't match: 0.8.0, 0.7.6, 0.7.5, ...
location searched: crates.io index
required by package `qsv v0.78.0 (/home/aborruso/lavagna/qsv)`
```

**Comment by aborruso** [comment]
> What environment do you have?

Debian 11 (inside WSL2)
 
> If you download a qsv prebuilt, what does `qsv --version` say?

I use always the x86_64-unknown-linux-gnu. Now I have `qsv 0.78.0-mimalloc-apply;fetch;foreach;generate;luau;self_update-8-8 (x86_64-unknown-linux-gnu compiled with Rust 1.65) prebuilt`

**Comment by jqnatividad** [comment]
and what does `rustup check` show?

**Comment by aborruso** [comment]
> and what does `rustup check` show?

stable-x86_64-unknown-linux-gnu - Update available : 1.59.0 (9d1b2106e 2022-02-23) -> 1.65.0 (897e37553 2022-11-02)
rustup - Update available : 1.24.3 -> 1.25.1

**Comment by jqnatividad** [comment]
That's it... qsv always targets Rust stable, which is currently 1.65.0.

You need to upgrade Rust - `rustup update`

**Comment by aborruso** [comment]
> That's it... qsv always targets Rust stable, which is currently 1.65.0.

thank you

**Comment by ondohotola** [comment]
I am currently circumventing this with `mlr` using its `string($columnname)` function.

**Comment by aborruso** [comment]
> I am currently circumventing this with `mlr` using its `string($columnname)` function.

Currently qsv manages this well, you can also just use qsv.
It's not like before, if it reads "02" it maps it as a string.
