### ISSUE TITLE
qsv uses very new glibc/glibxx on Ubuntu

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#649]
Ubuntu 20.04 lacks required dynamic libraries to run qsv 0.77.0

update qsv to v 0.77.0
run qsv
results in:
```
qsv: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by qsv)
qsv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by qsv)
qsv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by qsv)
qsv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by qsv)
```
Description:	Ubuntu 20.04.5 LTS
qsv v 0.77.0

This will be the same as LUAU issue [#773](https://github.com/Roblox/luau/issues/773) so perhaps the same solution ie try switching to ubuntu-20.04 in the Github Actions.

greetings, el

**Comment by jqnatividad** [comment]
Hi @ondohotola ,
qsv 0.78.0 was just released. It's built using ubuntu 20.04, so it should be linked to the older glibc libraries.

Please let me know how it works for you...

**Comment by ondohotola** [comment]
Thank you very much, works very well :-)-O

el
