### ISSUE TITLE
Scan CSV for CSV Injection vulnerability

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#66]
see https://owasp.org/www-community/attacks/CSV_Injection
https://securityboulevard.com/2019/09/data-extraction-to-command-execution-csv-injection/

And a recent CSV injection attack
https://threatpost.com/woocommerce-multi-currency-bug-pricing/169394/

**Comment by rzmk** [comment]
Has this recipe been added yet?
