### ISSUE TITLE
opposite of currencytonum

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#660]
**Is your feature request related to a problem? Please describe.**
Large floats (amounts like `1234567.9394`) are difficult to read 

**Describe the solution you'd like**
I would like to be able to see something like `1,234,567.94`  by way of `qsv apply operations enumtocurrency --round 2` or even `1,234,567.94 EUR` by way of `qsv apply operations enumtocurrency  --round 2 --currency "EUR"`  and of course the thousands separator should be locale dependent, ie the Germans like `1.234.567,94` 
 
**Describe alternatives you've considered**
I could not find a simple way of formatting this with lua(u) and anyway, mapping only works for single columns whereas `qsv apply operations currencytoenum 1-` works very well. 

I have no clue about Python which in any case is not compiled into the distributed versions I have 
```
qsv 0.79.0-mimalloc-apply;fetch;foreach;generate;luau;self_update-16-16 (x86_64-unknown-linux-gnu compiled with Rust 1.66) prebuilt
qsv 0.79.0-standard-apply;fetch;foreach;generate;luau;self_update-8-8 (x86_64-apple-darwin compiled with Rust 1.66) prebuilt
```

**Additional context**
none

**Comment by ondohotola** [comment]
Thank you, I'll wait for the auto-updated version, test and report back :-)-O

I like the conversion idea. 

I'll write up another little recipe in the cookbook how to get the latest exchange rates from the ECB (into a pipe)

**Comment by jqnatividad** [comment]
That'd be great @ondohotola! As a qsv power user, please do not hesitate to add recipes to the cookbook.

It sorely needs to be seeded with more content.

**Comment by ondohotola** [comment]
If I do something like 

```
printf 'currency,rate\nZAR,18.3529\n' | qsv table
```

I receive something like

```
currency  rate
ZAR       18.3529
```

and this

```
printf 'currency,rate\nZAR,18.3529\n' | qsv apply operations numtocurrency rate | qsv table
```
yields

```
currency  rate
ZAR       18.35
```

But the result of this 

```
printf 'currency,rate\nZAR,18.3529\n' | qsv apply operations numtocurrency currency,rate | qsv table
```

is rather unexpected
.
```
currency  rate
0.00      18.35
```

In other words a non-numeric value should be unchanged
