### ISSUE TITLE
add --yes to qsv --update

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#661]
**Is your feature request related to a problem? Please describe.**
I would like to update without having to hit Return at the `Do you want to continue? [Y/n]` prompt.

**Describe the solution you'd like**
add something like `--yes` to `qsv --update`

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by jqnatividad** [comment]
good idea @ondohotola .

I implemented it as `-U, --updatenow`.

**Comment by ondohotola** [comment]
Even better :-)-O

greetings, el
