### ISSUE TITLE
stats: wrong field inferencing?

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#666]
Hi,
if I run `qsv stats` for [this CSV](https://gist.github.com/9a4cc32dea2f772a084af35dcc2f4a03), I have the field `IMPO_IMPORTO_FINANZIATO` mapped as string, but it seems to me that it does not contain any string, it should be mapped as number.

Am I wrong?

Thank you

**Comment by jqnatividad** [comment]
Thanks @aborruso for the report.
It is indeed a bug introduced by the recently merged leading zero handling (https://github.com/jqnatividad/qsv/pull/648).
I'll fix should be relatively simple and will be in the next release.

**Comment by aborruso** [comment]
It works very well, thank you very much
