### ISSUE TITLE
case independent sort

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#672]
**Is your feature request related to a problem? Please describe.**
Occasionally I would like so sort case independently

**Describe the solution you'd like**
I would like to have an option to sort case independently (ie something like `sort -f`

**Describe alternatives you've considered**
Currently I pipe through `sort -f -t','`

**Additional context**
nil

**Comment by jqnatividad** [comment]
Here you go @ondohotola !

Another great suggestion... keep 'em coming! 😄

**Comment by ondohotola** [comment]
Without wishing to be impatient, how often is an update (that I can pull via -u) built?

I tried on the M1 but it failed because homebrew only provided rust 1.65 so I won't try in my Intel Mac.

**Comment by jqnatividad** [comment]
@ondohotola , at this stage, I normally create a release about once a week.

And yes, 0.80.0 is out. Let me know how it works for you...
