### ISSUE TITLE
Add the UNIX epoch timestamp to the list of time formats that qsv-dateparser can parse.

### ISSUE THREAD

**Issue by derekmahar** [jqnatividad/qsv#682]
Please add the UNIX epoch timestamp format (seconds since the UNIX epoch) to the list of time formats that qsv-dateparser can parse, including timestamps having fractional seconds to nanosecond or microsecond precision.  As an alternative to fractional seconds, the timestamp might instead be an integer representing the number of nanoseconds or microseconds since the epoch.

I would like to transform columns in CSV files that contain UNIX epoch timestamps to [ISO 8601](https://en.m.wikipedia.org/wiki/ISO_8601) format.  Many of these timestamps include fractional seconds (milliseconds, microsecond, or nanoseconds).

Alternatives:

[csvq](https://mithrandie.github.io/csvq/reference/cast-functions.html#datetime)
```
$ csvq --format csv "SELECT UTC(DATETIME(1671673426.123456789)) AS timestamp;"
timestamp
2022-12-22T01:43:46.1234567Z
```
[DuckDB](https://duckdb.org/)
```
$ duckdb -csv -c "SELECT epoch_ms('1671673426.123456789'::BIGINT * 1000) + INTERVAL (string_split('1671673426.123456789', '.')[2]::BIGINT/1000) MICROSECONDS AS timestamp"
timestamp
"2022-12-22 01:43:46.123456"
```
[goawk](https://github.com/benhoyt/goawk) and [GNU date](https://www.gnu.org/software/coreutils/manual/html_node/date-invocation.html)
```
$ printf "timestamp\n1671673426.123456789\n" | goawk -H -i csv -o csv 'BEGIN { print "timestamp" } { system("date --date=@" @"timestamp" " +%FT%T.%N") }'
timestamp
2022-12-21T20:43:46.123456789
```

[Miller](https://miller.readthedocs.io/en/latest/reference-dsl-builtin-functions/#strftime)
```
$ echo timestamp=1671673426.123456789 | mlr put '$timestamp = strftime($timestamp, "%FT%H:%M:%3S");'
timestamp=2022-12-22T01:43:46.123
$ echo timestamp=1671673426.123456789 | mlr put '$timestamp = strftime($timestamp, "%FT%H:%M:%6S");'
timestamp=2022-12-22T01:43:46.123456
$ echo timestamp=1671673426.123456789 | mlr put '$timestamp = strftime($timestamp, "%FT%H:%M:%9S");'
timestamp=2022-12-22T01:43:46.123456716
```
Notice in the last example using format string `%9S` that function `strftime` in Miller suffers from a [precision problem](https://github.com/johnkerl/miller/issues/1152).

[SQLite](https://sqlite.org/lang_datefunc.html)
```
$ echo | sqlite3 -csv -header -cmd "SELECT strftime('%Y-%m-%dT%H:%M:%f', 1671673426.123456789, 'unixepoch', 'utc') AS timestamp;"
timestamp
2022-12-22T06:43:46.123
```
Notice that function `strftime` in SQLite prints seconds to at most millisecond precision.

**Comment by jqnatividad** [comment]
OK @derekmahar , this is a good addition, especially since I'm currently working on computing descriptive statistics for dates (#681).

**Comment by derekmahar** [comment]
What are descriptive statistics?

**Comment by jqnatividad** [comment]
They're the various statistics returned by the `stats` command.

But strictly speaking - https://en.wikipedia.org/wiki/Descriptive_statistics.

**Comment by derekmahar** [comment]
I understand now how the two issues are related.

**Comment by jqnatividad** [comment]
@derekmahar ,
qsv and qsv-dateparser have now been upgraded to recognize timestamps with fractional seconds to nanosecond precision.

`stats`, `sniff`, `apply datefmt`, and `schema` - which all use qsv-dateparser, should now infer unix timestamps as dates.

Please let me know how it works for you.

**Comment by derekmahar** [comment]
Thank you for implementing this enhancement.  Before I can verify this change, I will need to wait until Nix releases rustc 1.66.0 because when attempting to build qsv using rustc 1.65.0, despite having changed `rust-version` to 1.65.0 in the qsv `Cargo.toml`, Cargo complains that package qsv-stats  0.5.1 requires rustc 1.66 or newer.

```
  Downloaded 1 crate (7.9 KB) in 0.13s
error: package `qsv-stats v0.5.1` cannot be built because it requires rustc 1.66 or newer, while the currently active rustc version is 1.65.0
Either upgrade to rustc 1.66 or newer, or use
cargo update -p qsv-stats@0.5.1 --precise ver
where `ver` is the latest version of `qsv-stats` supporting rustc 1.65.0
```

**Comment by ondohotola** [comment]
What system is this on? On the Mac Homebrew has 1.66 and I have successfully compile qsv on my M1, for the x86 I can just do the -u (or now also -U) as that version has luau built in.

And, in any case the warning clearly says what to do to get it to compile with 1.65.

el

**Comment by derekmahar** [comment]
I'm compiling on a Raspberry Pi 4 running Ubuntu Server 22.04 and the Nix package manager.  I could install rustic 1.66 using rustup, but that may or may not take priority other the version that Nix has installed.  I don't know why rustc in Nix is a little delayed, but 1.66 should be available there soon.

The warning says, "cargo update -p qsv-stats@0.5.1 --precise ver where `ver` is the latest version of `qsv-stats` supporting rustc 1.65.0", but how do we know that this particular commit of qsv will build and work correctly with version `ver` of qsv-stats?  If I interpret the warning correctly, this Cargo command would replace qsv-stats 0.5.1 with version `ver` just so that it will compile with rustc 1.65.

**Comment by jqnatividad** [comment]
Hi @derekmahar , with 0.81.0 now out, perhaps you can try the prebuilt?

Anyway, I changed the MSRV of qsv-stats 5.2 to 1.65 as well should you still want to compile from source to optimize for the Raspberry Pi 4.

**Comment by derekmahar** [comment]
After pulling the latest qsv changes including qsv-stats 0.5.2 and rebuilding qsv using rustc 1.65.0, I verified that `qsv apply datefmt` correctly interprets a UNIX epoch timestamp having fractional seconds and converts it to an ISO 8601 date and time:

```
$ printf "timestamp\n1671673426.123456789\n" | target/release/qsv apply datefmt timestamp
timestamp
2022-12-22T01:43:46.123456768+00:00
```

**Comment by ondohotola** [comment]
So you have a number of factors which have nothing to do with qsv.

And no patience.

**Comment by derekmahar** [comment]
> So you have a number of factors which have nothing to do with qsv.

Incorrect.

> And no patience.

False.
