### ISSUE TITLE
currencytonum/numtocurrency still returns wrong results

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#689]
I**Describe the bug**
[#660](https://github.com/jqnatividad/qsv/issues/660) still has a corner case :-)-O

**To Reproduce**
```
cat  > test.csv<<EOF
CUR,RATE
EUR,1
GBP,1.14088829562698
NAD,18.3529
EOF
```

```
qsv table test.csv
```
returns

```
CUR  RATE
EUR  1
GBP  1.14088829562698
NAD  18.3529
````

```
qsv apply operations currencytonum RATE test.csv | qsv table
```

returns

```
CUR  RATE
EUR  1.00
GBP  319.79
NAD  18.35
```
as does 

```
qsv apply operations numtocurrency RATE test.csv | qsv table
``` 

by the way

**Expected behavior**

The result should be something like

```
CUR  RATE
EUR  1
GBP  1.14
NAD  18.35
```

**Screenshots/Backtrace/Sample Data**
N/A

**Desktop (please complete the following information):**
macOS 13.1
qsv 0.80.0-standard-apply;fetch;foreach;generate;luau;to;self_update-8-8 (x86_64-apple-darwin compiled with Rust 1.66) prebuilt

**Additional context**

This behavior starts when there are more than 11 decimals :-)-O

**Comment by jqnatividad** [comment]
Thanks @ondohotola for the report.

The currency-rs crate we forked and optimized for qsv (qsv-currency) has some limitations because of the core assumption that there are 100 coins to 1 currency unit, so it is optimized to work with two decimal places.

We worked around the three decimal places as you saw, as one can argue that calculations with currency to 3 decimal places occurs IRL, and we added rounding to the nearest coin.

However, currency having more than 3 decimal places, never mind 11, does not really make sense in the real world, so I think we can accept the current limitation.

WDYT?

**Comment by ondohotola** [comment]
Joel,

I don’t think one can accept this limitation.

Just for the fun of a RL example, the last exchange rate from the ECB gives `0.8803 GBP` for `1 EUR`.

So when calculating the (reverse) exchange rate, ie 1 GBP (to EUR using only 2 decimals) I'd expect something like `1/0.88 = 1.136363636363636` , which of course would round to `1.14`.

In a pipeline:

```
wget -q http://www.ecb.europa.eu/stats/eurofxref/eurofxref.zip -O - \
	| funzip \
	| qsv input --trim-headers --trim-fields \
        | qsv apply datefmt Date \
	| qsv select Date,GBP \
        | qsv luau map EUR "1/tonumber(GBP)" \
	| qsv luau map EURrounded "string.format('%.2f',1/tonumber(GBP))" \
	| qsv apply operations copy EUR -c EURnumtocurrency \
	| qsv apply operations numtocurrency EURnumtocurrency \
        | csview
```
this comes out as

```
┌────────────┬─────────┬────────────────────┬────────────┬──────────────────┐
│    Date    │   GBP   │        EUR         │ EURrounded │ EURnumtocurrency │
├────────────┼─────────┼────────────────────┼────────────┼──────────────────┤
│ 2022-12-23 │ 0.88030 │ 1.1359763716914688 │ 1.14       │ 410,919.79       │
└────────────┴─────────┴────────────────────┴────────────┴──────────────────┘
```

I am personally more in favour of fixing this. So that the error can not occur, but that is easy for me (an elderly Gynecologist sitting on the fence :-)-O) to say. 

I am not squealing about 11 decimals, but when you use a division it is bound to occur and in a pipeline it is enormously difficult to notice. If you load from a spreadsheet, even if it is formatted as `$` (ie 2 decimals), it comes with whatever precision the spreadsheet stores the result, which makes it even  more insidious.

If you then were to upload via the `to` method to `PostgreSQL` for example, you can get yourself into real trouble.

At the moment I must add a LUAU call `string.format()` for **each** column, then SELECT and RENAME, whereas `numtocurrency/currencytonum` both support **multiple** columns.

What about a flag `--precision #`? And then something like

1. If no flag, set precision to 3 (or 4), and round to that precision.
2. If the flag value is between 0 and 10, round to that precision.
3. if the flag value is larger than 10, bomb with an error message

including a line in the documentation.

**Comment by ondohotola** [comment]
Given the file `testdata.csv` with the content of:

```
Date,Text,Float
2022-01-01,a,3.234567890234567890
2022-02-01,b,6.555555555
2007-07-07,"C",8.999999999
```
the command `qsv apply operations numtocurrency "Date,Text,Float" testdata.csv` returns the surprising result (to stdout):

```
"2007-07-07"
"2022-01-01"
"2022-02-01"
Date,Text,Float
2022-01-01,0.00,"17,251,770.12"
2022-02-01,0.00,6.56
2007-07-07,0.00,9.00
```

currencytonum does not fare better

**Comment by jqnatividad** [comment]
Thanks for the detailed followup @ondohotola .

currencytonum started out as a convenience feature as we often encountered currency units in data pipelines which we had to convert to numbers and currency crate suited the original purpose.

Perhaps, I should look again for an alternate currency parsing crate that can handle these kind of conversions.

[currency_rs](https://crates.io/crates/currency_rs), [moneta](https://crates.io/crates/moneta) and [rusty-money](https://crates.io/crates/rusty-money) all look promising...

Perhaps, as a qsv power-user 😄 , you can help me help identify the crate that we can leverage?

**Comment by ondohotola** [comment]
Joel,

thank you.

While I can cobble together simple bash, Perl and SQL statements, (and have been doing so for may years for my day-job workflow) I have absolutely no clue whatsoever about crates (or even rust itself) other than that they seem to be libraries (like CPAN Perl modules). 

But since exchange rates are usually quoted with 4 or at the most 6 decimal points, maybe rounding down to at the most 6 decimal points before passing it off for formatting would work around the issue (until you switch to rusty-money :-)-O)

**Comment by jqnatividad** [comment]
@ondohotola , just wanted to let you know that I'm scheduling to do this in the backlog. 

For now, I'll just add a note about currencytonum/numtocurrency's limitations whilst working on the rusty-money powered replacement.

**Comment by ondohotola** [comment]
Thank you very much.

**Comment by jqnatividad** [comment]
Hi @ondohotola ,
I'm currently looking at [smartcalc](https://github.com/erhanbaris/smartcalc), to not only power currencytonum and numtocurrency, but also to replace [cpc](https://github.com/probablykasper/cpc), which qsv uses for `apply calcconv`.

I'm thinking of using smartcalc, as it has integrated some functionality we can leverage to get the current exchange rates.

Since you've been pushing the envelope on qsv's currency support, would like to get your opinion before doing so...

**Comment by ondohotola** [comment]
Joel,

it looks **very** sexy :-)-O and their web app does the rounding correctly.

So this makes a lot of sense to me.
