### ISSUE TITLE
Maintainership status of qsv

### ISSUE THREAD

**Issue by vi** [jqnatividad/qsv#7]
Is qsv fork considered to be actively maintained or is it in "glacier" state as well as xsv? For example, there is already an [additional feature pull reqeust](https://github.com/BurntSushi/xsv/pull/273) to xsv.

Shall new feature requests be submitted to xsv or to qsv repository?

**Comment by jqnatividad** [comment]
Sorry @vi as I had to back-burner qsv, as I got tied down with other stuff.

But I'll pick it up again in August and will be sure to pull in quartiles PR as well.

**Comment by jqnatividad** [comment]
Hi @vi , I just released qsv 0.14.0.

https://github.com/jqnatividad/qsv/releases/tag/0.14.0

If you have any new feature requests for qsv, feel free to submit them in this repo.

**Comment by jqnatividad** [comment]
Closing this now that qsv 0.14.x has been released.
