### ISSUE TITLE
`tojsonl` crash when converting UTF-8 csv data

### ISSUE THREAD

**Issue by thanhbinh01234** [jqnatividad/qsv#705]
**Describe the bug**
When converting csv contains UTF-8 characters, qsv crash with error byte index is not a char boundary:
```bash
echo 'a\n" Chung Nguyễn\n Nguyễn"' | qsv tojsonl

thread 'main' panicked at 'byte index 13 is not a char boundary; it is inside 'ễ' (bytes 11..14) of ` Chung Nguyễn
 Nguyễn`', src/cmd/tojsonl.rs:187:38
```

**Comment by jqnatividad** [comment]
Thanks for the report @thanhbinh01234 .

#707 uses the built-in escape_default() fn instead, allowing me to eliminate my own hand-rolled escape.

It now works as follows:
```
echo 'a\n" Chung Nguyễn\n Nguyễn"' | target/debug/qsv tojsonl
{"a":" Chung Nguy\u{1ec5}n\n Nguy\u{1ec5}n"}
```
