### ISSUE TITLE
`tojsonl` crash when convert csv contains both boolean and null

### ISSUE THREAD

**Issue by binhunstatic** [jqnatividad/qsv#708]
**To Reproduce**
```bash
echo "a,b\nfalse,1\n,2" | qsv tojsonl
```
crash with error
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/cmd/tojsonl.rs:124:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ondohotola** [comment]
On bash on an Intel Monterrey Mac echo needs to be replaced by printf but It bombs with same error message.

As workaround one can use

printf "a,b\nfalse,1\n,2" | mlr --c2j cat

**Comment by jqnatividad** [comment]
Thanks for the report @binhunstatic and for the workaround @ondohotola

And here's the fix... please let me know if it works for you...

**Comment by jqnatividad** [comment]
Closing this now that 0.82.0 is out.

```
$ qsv --version
qsv 0.82.0-standard-apply;fetch;foreach;generate;self_update-8-8 (aarch64-apple-darwin compiled with Rust 1.66) prebuilt
$ echo "a,b\nfalse,1\n,2" | qsv tojsonl
{"a":"false","b":1}
{"a":"","b":2}
```

Note that it is treated as a string. However, I decided to make null "falsy", so it's treated as boolean below:

```
$ echo "a,b\ntrue,1\n,2" | qsv tojsonl
{"a":true,"b":1}
{"a":false,"b":2}
```
