### ISSUE TITLE
BUG: `qsv tojsonl` emits invalid escape sequences when the source text includes a "'"

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [jqnatividad/qsv#744]
**Describe the bug**
*A clear and concise description of what the bug is.*

When given certain input, `qsv tojsonl` emits escape sequences inside JSON strings that aren't valid. One example is below.

**To Reproduce**
Example CSV file which results in invalid JSON output:

```
"this isn't a valid property"
"this isn't a valid value"
```

Results of running `qsv tojsonl`:

```
❯ qsv tojsonl test.csv
{"this isn't a valid property":"this isn\'t a valid value"}
```

Common JSON parsers complain about the unnecessary `\` in the value:

```
❯ qsv tojsonl test.csv |jq
parse error: Invalid escape at line 1, column 58

❯ node
Welcome to Node.js v19.4.0.
Type ".help" for more information.
> JSON.parse(`{"this isn't a valid property":"this isn\\'t a valid value"}`)
Uncaught SyntaxError: Bad escaped character in JSON at position 41
```

**Expected behavior**
*A clear and concise description of what you expected to happen.*

I expected the `'` character not to be escaped, in line with [the JSON standard](https://www.json.org/json-en.html), which recognizes only certain escape sequences:
* One of `"`, `\`, `/`, `b`, `f`, `n`, `r`, or `t`
* `uXXXX` where `XXXX` is 4 hex digits

**Screenshots/Backtrace/Sample Data**
*If applicable, add screenshots/backtraces/sample data to help explain your problem.*

**Desktop (please complete the following information):**
 - OS: Mac; installed qsv thru Homebrew
 - qsv Version: `qsv 0.85.0-mimalloc-apply;-8-8 (x86_64-apple-darwin compiled with Rust 1.66.1) compiled`

**Additional context**
*Add any other context about the problem here.*

I'm a bit concerned about the fact that the escaping used for the property name string is different from the value string. That suggests to me that there might be different escaping problems with property names. And sure enough:

```
"\this isn't a valid property"
"this isn't a valid value"
```

produces:

```
❯ qsv tojsonl test.csv
{"\this isn't a valid property":"this isn\'t a valid value"}
```

`    his isn't a valid property` is clearly not the same name as `\this isn't a valid property`. I'm not sure if this is the same bug or a different bug, however.

**Comment by jqnatividad** [comment]
Thanks for the detailed report @joshua-berry-ntnx 

This is indeed a bug as `tojsonl` builds the jsonl incrementally using string operations.

I'll reimplement it "properly" using serde_json so it always produces valid JSON.
https://stackoverflow.com/questions/59047280/how-to-build-json-arrays-or-objects-dynamically-with-serde-json

**Comment by joshua-berry-ntnx** [comment]
Thank you @jqnatividad, much appreciated! And thanks for creating this tool!

**Comment by jqnatividad** [comment]
Hi @joshua-berry-ntnx ,
Just fixed this, while still retaining the streaming nature of tojsonl so it can produce valid jsonl files from arbitrarily large CSV files.

Let me know how it works for you...

**Comment by joshua-berry-ntnx** [comment]
Looks good, thanks again!
