### ISSUE TITLE
Option to silence dedup count

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#766]
Since #272 `qsv dedup` has sent a dupe_count to STDERR.

It would be nice if there was a flag that would turn this off, rather than needing to disable/redirect STDERR.

**Comment by jqnatividad** [comment]
Hi @tmtmtmtm , went ahead and added a `-Q, --quiet` option not only to `dedup`, but to `extdedup`, `search`, `searchset` and `replace` commands as well for consistency.

BTW, as you're using `dedup`, you may want to check out `extdedup`. Though not as flexible as `dedup`, it can deduplicate arbitrarily large CSV and text files without changing the input sort order by using an on-disk hash table.

**Comment by tmtmtmtm** [comment]
@jqnatividad that's excellent, thank you. I can certainly think of times when dedup without re-sorting could be useful, so I'll definitely have a look at `extdedup`.

**Comment by ondohotola** [comment]
Can you also quiet some other commands such as `excel`, please?

**Comment by jqnatividad** [comment]
Here you go @ondohotola :smile:

https://github.com/jqnatividad/qsv/commit/99d88499df573f9f46992346f394d9372ceeffcc
