### ISSUE TITLE
qsv exclude failing due to utf8 check

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#778]
Similar to #772, I'm getting the `not UTF-8 encoded. Use the input command to transcode to UTF-8` error when trying to use `qsv exclude`.

`qsv input` makes no changes to the files in question. I'm happy to produce a set of example files if this isn't just a trivial fix for an oversight.

**Comment by jqnatividad** [comment]
Hi @tmtmtmtm , thanks for exercising qsv 😄 

And yeah, the fix should be straightforward (don't do utf8 check for `exclude`), but it'd be great if you can produce example files so I can include it in `exclude`'s test suite to prevent future regressions.

FYI, the entire utf-8 pre-screening check is because of my attempt to squeeze as much performance as possible from `stats`, as that's a core function I'm using in another project.  Doing so however has introduced this unfortunate regressions with other commands.

**Comment by tmtmtmtm** [comment]
Given the two CSVs at https://gist.github.com/tmtmtmtm/6a3bc24d5def746e09794e516b5f6367, running either `qsv exclude position aliases.csv position positions.csv` or `qsv exclude position positions.csv position aliases.csv`[^1] gives the errror:

```
"aliases.csv" is not UTF-8 encoded. Use the input command to transcode to UTF-8.
```

Unfortunately the example aliases file here is much larger than I would like. I can't work out what specifically is triggering the error well enough to be able to trim it down much further. Removing any line I've tried from this version makes it start working, though I'm sure there must be a much smaller version that would still exhibit the problem.

And sorry for the deluge of reports! I probably should have kept up with releases better rather than jumping a gazillion versions at once, and hitting all the issues in one go. But there are too many nice new features to want to go back to the earlier version now 😸 Thanks for all your work on this, and for being so incredibly responsive.



[^1]: BTW, it might be worth tweaking the docs for `exclude` a bit to make it a bit clearer about which direction the subtraction happens in. I keep getting it the wrong way around, presumably because my brain thinks of it as being "exclude X from Y", and the current docs reinforce that slightly by phrasing it as "Removes a set of CSV data from another set". I can't think of a good way to rewrite the first sentence to turn that around, so perhaps the best approach is to add a sentence spelling this out? Or maybe there are more descriptive names for `<input1>` and `<input2>` that would convey it better? I'm a bit bit too frazzled to come up with a good suggestion right now, but happy to come back to it tomorrow if needed.

**Comment by tmtmtmtm** [comment]
@jqnatividad any idea when there might be a release including this? Trying to decide whether to work around it in the meantime, or wait for a new version…
