### ISSUE TITLE
qsv cat rows --select

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#787]
I regularly deal with groups of CSVs which contain a set of common columns I care about, but may otherwise have slightly different columns to each other.

Currently `qsv cat rows` requires them to all have exactly the same columns, which means I essentially need to loop over them with something like:

```sh
TEMPDIR=$(mktemp -d)
for input in *.csv
do
  qsv select wanted,columns $input > $TEMPDIR/$input
done

qsv cat rows $TEMPDIR/*.csv
```

It would be nice I could do something like `qsv cat rows -s wanted,columns *.csv` instead.

(NB: there was a previous request (#527) along these lines, but that was for a more magical solution that would work out the subset of common columns itself. This suggestion is for a presumably simpler and more explicit version using the ` --select` syntax that is common to other commands.)

**Comment by jqnatividad** [comment]
Actually @tmtmtmtm , the "magical" solution in #527 is easier to implement. I was hoping the author would make a PR, but I'll just go ahead and do it in a similar fashion.

**Comment by tmtmtmtm** [comment]
Oh, interesting. That's a little unexpected, but sounds good!
