### ISSUE TITLE
`luau`: combine prologue, body and epilogue into a single script

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#788]
@jqnatividad, I think `qsv luau` is just as easy to use as Miller's DSL, but more extensible because it can use Lua's packages.  However, would it not be possible to combine the prologue, body, and epilogue into a single script, similiar to BEGIN and END in Awk?

_Originally posted by @derekmahar in https://github.com/jqnatividad/qsv/discussions/725#discussioncomment-5019080_

**Comment by jqnatividad** [comment]
Hi @derekmahar, this sounds sensible.

Your Awk comparison to BEGIN and END is most interesting.

I was thinking:

- get rid of the explicit `--prologue` and `epilogue` options.
- if a `prologue` section exists in the `main-script`, that is used as the prologue
- if an `epilogue` section exists in the `main-script`, that is used as an epilogue

WDYT?

**Comment by derekmahar** [comment]
Yes, this is what I had in mind.  However, while we both know what prologue and epilogue mean, I think more people are familiar with begin and end, particularly those whose first language isn't English.

**Comment by derekmahar** [comment]
Or, you could support both pairs of words!

**Comment by derekmahar** [comment]
You might also want to keep the prologue and epilogue command-line options at least for the next several releases in order to maintain backward compatibility and give users a chance to migrate their scripts to the new syntax.

**Comment by jqnatividad** [comment]
Hi @derekmahar ,

Check it out!
https://github.com/jqnatividad/qsv/blob/f7af92d9e40d3b9381723e1b38f2f647fdaa6879/tests/test_luau.rs#L208-L270

I decided to just replace --prologue and --epilogue outright, as I don't think there are that many users using prologue/epilogue anyway, and it's just not worth having backward compatibility code for it.

**Comment by derekmahar** [comment]
Are `BEGIN` and `END` blocks special qsv syntax that is separate from Lua syntax?

**Comment by jqnatividad** [comment]
Yes, they are just special syntax to delimit the BEGIN/END blocks and separate from Lua syntax.

That's why I used the ")!" block terminator as just using "}" is not possible as "}" is used in Lua as well.
