### ISSUE TITLE
`joinp`: polars-powered join

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#789]
The current `join` command is quite powerful.  However, the resulting output does not coalesce columns, and the user will need to `--select` columns after joining.

This new command will leverage polars as an engine, and use its join capabilities.

We will keep the existing `join` command for backwards compatibility, but once there is full feature parity (i.e. accept input from stdin, case-insensitive joins), the existing `join` command will be removed and `joinp` will be renamed to `join`.

cc @peterjc

**Comment by peterjc** [comment]
This sounds very promising, thanks!

**Comment by jqnatividad** [comment]
Will expose all [polars join strategies](https://pola-rs.github.io/polars-book/user-guide/howcani/combining_data/joining.html), including `asof` joins.

**Comment by jqnatividad** [comment]
The first basic attempt at using Polars for joins has been merged.

Will keep iterating on it to improve it further (including adding `asof` joins).

There are no tests yet, so manual tests (aka bug reports) are welcome and appreciated! :)

cc @baggiponte @ondohotola @derekmahar
