### ISSUE TITLE
BUG frequency missing items

### ISSUE THREAD

**Issue by wgoetz** [jqnatividad/qsv#821]
**Describe the bug**
running qsv frequency on a simple list has missing items

**To Reproduce**

1. download the provided nr.csv

2. short check:
qsv frequency n.csv|awk -F, '{n+=$3}END{print n}'        
49
sort n.csv|grep -v nr|uniq -c| awk '{n+=$1}END{print n}'
54

3 long output:

qsv frequency nr.csv
field,value,count
nr,661229,30
nr,661106,5
nr,661272,3
nr,661263,2
nr,661277,2
nr,661067,2
nr,665233,2
nr,661696,1
nr,660567,1
nr,662218,1

sort n.csv|grep -v nr|uniq -c                           
      1 660182
      1 660567
      1 660569
      1 660839
      2 661067
      1 661069
      5 661106
     30 661229
      2 661263
      3 661272
      2 661277
      1 661334
      1 661696
      1 662218
      2 665233

**Expected behavior**
the total sum should be the same as for sort/uniq 

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 22.04
 - qsv Version
qsv 0.90.1-mimalloc-apply;fetch;foreach;generate;Luau 0.561;python-3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0];to;self_update-12-12;5.51 GiB-2.00 GiB-4.89 GiB-15.57 GiB (Unknown_target compiled with Rust 1.67.1) installed

**Additional context**

[nr.csv](https://github.com/jqnatividad/qsv/files/10865333/nr.csv)

**Comment by jqnatividad** [comment]
@wgoetz , by default `frequency` only compiles the first 10 most commons items. You need to set `--limit` to 0 to compile all frequency values.

``` bash
qsv frequency nr.csv --limit 0|awk -F, '{n+=$3}END{print n}'
54
```
