### ISSUE TITLE
luau map multiple columns

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#825]
In order to `map` multiple new columns with `luau` (but probably also with `python` one needs to tun a pipe currently, ie something like `qsv luau map b 'a + 1' | qsv luau map map c 'b + 1'`

I would really like do do something like `qsv luau map b 'a + 1' map c 'b + 1'` 

Is something like this feasible?

**Comment by jqnatividad** [comment]
I'll have to explore it a bit more @ondohotola , but I think this is feasible by taking advantage of [Luau Tables](https://www.lua.org/pil/2.5.html).

The syntax would be something like:
`qsv luau map a,b,c  -x  ' tbl = {}; tbl[1] = a + 1; tbl[2] = b +  1; tbl[3] = c + 1; return tbl;' data.csv`
