### ISSUE TITLE
Gui qsv

### ISSUE THREAD

**Issue by AFgh24** [jqnatividad/qsv#871]
Hello
I think it would be great if you add a graphical interface for Windows and Linux
The speed of working with the program will increase

**Comment by jqnatividad** [comment]
Thanks @AFgh24 for the suggestion.

This has been on the backlog for a while with https://github.com/jqnatividad/qsv/issues/190.  As qsv matures, I hope to make time to finally build it...

**Comment by jqnatividad** [comment]
This will be done as a nushell plugin - #1006

**Comment by jqnatividad** [comment]
This is done with qsv pro - qsvpro.dathere.com
