### ISSUE TITLE
cargo test failed

### ISSUE THREAD

**Issue by vidhyasasi** [jqnatividad/qsv#892]
**Describe the bug**
I installed the qsvlite 0.95.1-mimalloc--2-2 from source and ran cargo test, then I am getting this error;
error[E0599]: no method named `qsv_bin` found for reference `&Workdir` in the current scope
   --> tests/workdir.rs:110:50
    |
110 |         let mut cmd = process::Command::new(self.qsv_bin());
    |                                                  ^^^^^^^ method not found in `&Workdir`

**To Reproduce**
run cargo test on the workdirectory

**Screenshots/Backtrace/Sample Data**
error[E0599]: no method named `qsv_bin` found for reference `&Workdir` in the current scope
   --> tests/workdir.rs:110:50
    |
110 |         let mut cmd = process::Command::new(self.qsv_bin());
    |                                                  ^^^^^^^ method not found in `&Workdir`

**Desktop (please complete the following information):**
 - OS:  Debain
 - qsvlite 0.95.1-mimalloc--2-2;2.79 GiB-0B-3.48 GiB-3.84 GiB (x86_64-unknown-linux-gnu compiled with Rust 1.68.1) compiled

**Comment by jqnatividad** [comment]
Hi @vidhyasasi ,
You have to specify the qsv binary variant you're testing, as the binary name is different for each one.

https://github.com/jqnatividad/qsv#testing

**Comment by vidhyasasi** [comment]
Hi @jqnatividad 

Thank you for your reply.  Testing is successful with specifying the binary variant. But there is a typo on the documentation,
https://github.com/jqnatividad/qsv#testing 
The flag should be "features" instead of "feature"
