### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect .BUG

### ISSUE THREAD

**Issue by AFgh24** [jqnatividad/qsv#912]
Hello

At the same time, I want to search for a text in several files with the following commands, but it does not work

index  and search

qsv index  *.csv
and 
qsv index  C:\Users\test\Desktop\1\2\*.csv

The filename, directory name, or volume label syntax is incorrect. (os error 123)

**Comment by jqnatividad** [comment]
@AFgh24, qsv does not support [glob](https://en.wikipedia.org/wiki/Glob_(programming)) operations.

You'll need to use your operating system's (Windows it appears) to loop through the files and call qsv for each file.

I'm not that familiar with Windows PowerShell, but this should point you in the right direction - https://stackoverflow.com/questions/18847145/loop-through-files-in-a-directory-using-powershell
