### ISSUE TITLE
Library option for qsv

### ISSUE THREAD

**Issue by armanm** [jqnatividad/qsv#926]
**Is your feature request related to a problem? Please describe.**
Can QSV support being a library in order to link to it by other libraries or executables.

**Describe the solution you'd like**
Define a library target for this project

**Describe alternatives you've considered**
At the moment the only way for one program to make use of qsv is to issue shell commands which isn't ideal. Being able to use qsv as a library in your own projects will be very convenient

**Comment by jqnatividad** [comment]
Hi @armanm ,
That is my intent when we reach 1.0 as I mentioned in #627.

TBH, we're at 0.99.0 already, and I was thinking of going to 1.0 for the next release, as I need it for another project I'm working on.

However, there are still some big items in the [backlog](https://github.com/jqnatividad/qsv/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) that I'd like to take care of that will greatly impact the API, so I'll wait until it stabilizes a bit, and then create a library option - most probably sometime mid-year.

**Comment by jqnatividad** [comment]
Now that we're well past 0.100.0, it's likely that a library option won't be available for a while as we concentrate on expanding qsv's functionality and keep the almost weekly release tempo.

When we do reach 1.0, only then will we start looking into a library option.

TBH, given how aggressively I update dependencies and MSRV, I doubt 1.0 will happen anytime soon.

If it does happen, it will be most probably a Rest API interface once qsv gets a daemon variant. In this way, we can keep iterating aggressively, while maintaining a stable API.

The daemon variant will run as a service and will be used to talk to Excel and other desktop/server tools that require data-wrangling services.

**Comment by jqnatividad** [comment]
After further contemplation, qsv will NOT have a traditional Rust library option for all the reasons cited above.

It will, however, gain a REST API when a daemon variant is created (#1248 ) as its needed to create #1181 .

Other systems that wish to avail of qsv data-wrangling services can use the REST API.

**Comment by dafeder** [comment]
@jqnatividad I'm trying to follow the issues here, is a REST API interface still on the table?

**Comment by jqnatividad** [comment]
We have an initial installment of it in qsv pro @dafeder, but that's targeted to desktop data-wrangling use-cases and interaction with an upcoming Excel template.

For the server, its still on the backlog, but I'm thinking of doing it for Datapusher+ 2.0, so it just talks to the qsv daemon, instead of repeatedly calling the binary from python - eliminating the need for `qsvdp`.

In all likelihood, that won't happen until next year though...

**Comment by dafeder** [comment]
Thanks for the update, understand its not at the top of the backlog but glad to hear its still there. Being able to just stand up QSV as a web service could be very powerful, allow integrations with all kinds of other tools on the web.
