### ISSUE TITLE
QSV sniff giving inconsistent results

### ISSUE THREAD

**Issue by Zharktas** [jqnatividad/qsv#956]
**Describe the bug**

I'm migrating [ckanext-qa](https://github.com/ckan/ckanext-qa) away from messytables and there are some CSV files in tests that aren't handled by sniffer.

https://github.com/ckan/ckanext-qa/blob/master/ckanext/qa/tests/data/spendover25kdownloadSep.csv
results in `CSV read error: CSV error: record 1 (line: 1, byte: 108): found record with 2 fields, but the previous record has 1 fields`

https://github.com/ckan/ckanext-qa/blob/master/ckanext/qa/tests/data/311011.csv
results in 
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/qsv-sniffer-0.8.2/src/sniffer.rs:315:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/ckan/ckanext-qa/blob/master/ckanext/qa/tests/data/FCOServices_TransparencySpend_May2011.csv
results in
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/qsv-sniffer-0.8.2/src/sniffer.rs:315:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/ckan/ckanext-qa/blob/master/ckanext/qa/tests/data/iwfg09_Phos_river_200911.csv
results in `Sniffing failed: unable to find valid delimiter`

https://github.com/ckan/ckanext-qa/blob/master/ckanext/qa/tests/data/Inpatients_MHA_Machine_readable_dataset_1011.csv
results in CSV read error: `CSV error: record 328 (line: 329, byte: 88591): found record with 1 fields, but the previous record has 2 fields`

**To Reproduce**
Run `qsv sniff` on the given files.

**Expected behavior**
Sniff information would be given to the user.

**Screenshots/Backtrace/Sample Data**
Sample data above.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - qsv Version: 0.101.0

**Comment by jqnatividad** [comment]
Thanks for the report @Zharktas .

I'm actually thinking of replacing the engine that powers the sniff command as its proven a bit unreliable despite my efforts with the qsv-sniffer fork.

I'm thinking of just porting over Python's sniffer which has a more understandable regex-based algorithm instead of qsv-sniffer's Viterbi algorithm.

Can you tell me what your requirements are?

In the meantime, you can get some of the functionality of sniff by combining some commands:

`qsv stats --typesonly sample.csv | qsv tojsonl > sample.jsonl`

**Comment by Zharktas** [comment]
ckanext-qa is trying to more or less reliably sniff what kind of files the uploaded resources are, since ckan itself has its limits on identifying them. Originally I tried using `stats`, which seems to work fine with csv files, but ckanext-qa tries to identify also other kinds of files which then give weird results while using `stats`.  For example this https://github.com/ckan/ckanext-qa/blob/master/ckanext/qa/tests/data/ukk1202-36000.rdf rdf-file is a csv according to `stats`:
```
ckan@e572769298f2:~/qsvbin$ ./qsv stats ../ukk1202-36000.rdf 
field,type,sum,min,max,range,min_length,max_length,mean,stddev,variance,nullcount,sparsity
<rdf:RDF,String,,"                <skos:prefLabel xml:lang=""en"">Higher</skos:prefLabel>",</rdf:RDF>,,10,172,,,,0,0
```

`sniff` would give me a result that would tell me that this is not an csv.
```
ckan@e572769298f2:~/qsvbin$ ./qsv sniff ../ukk1202-36000.rdf 
Sniffing failed: unable to find valid delimiter
```

**Comment by jqnatividad** [comment]
Got it... `stats` presumes the input is a valid CSV, so it wouldn't be good for that.

I didn't particularly optimize `sniff` to see if the file is not a CSV, but I'll take that into account when I rewire `sniff` to use the same regex-based logic as Python's csv sniffer.

It's designed more to `sniff` a CSV "dialect" by sampling the first N lines.

BTW, you may want to check how I try to make DP+ a bit more tolerant of "data quality" issues in its initial analysis process - 
https://github.com/dathere/datapusher-plus/blob/3a3c69687f16973cbdfa9f52a4d6db11ac48f908/datapusher/jobs.py#L557

1. Check if the file is a spreadsheet. If it is, convert it to CSV.
2. If it can't convert the spreadsheet to a CSV, use `file` to get more actionable info for the user before aborting.
3. Run qsv validate against the converted CSV to see if it's a "valid" CSV file. If its not valid, abort with an actionable info message.
4. I then "normalize" the CSV to a standard CSV format with "qsv input" for more analysis/processing downstream. By this point - there's very high confidence that the incoming file is valid tabular data that I can do more qsv analysis with (screen for dupes, PII, derive summary statistics, infer types, etc.) and ultimately push to the Datastore.

**Comment by jqnatividad** [comment]
Here you go @Zharktas .

"Fixing" qsv-sniffer was a bit easier than I thought... it was mostly about error-handling.
https://github.com/jqnatividad/qsv-sniffer/releases/tag/0.8.3

I also went ahead and added the files you tested in the sniff test suite.

Let me know how it works for you...
