### ISSUE TITLE
Add `--no-headers` option to `rename`

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#97]
### Discussed in https://github.com/jqnatividad/qsv/discussions/81

<div type='discussions-op-text'>

_Originally posted by @tmtmtmtm in https://github.com/jqnatividad/qsv/discussions/81#discussioncomment-1599027_

**Comment by jqnatividad** [comment]
Done. Check it out @tmtmtmtm.
It'll be in next week's release as I'm doing weekly releases going forward.

**Comment by tmtmtmtm** [comment]
That's superb! Thanks a bunch for implementing it.
