### ISSUE TITLE
Investigate using Hyperfine in benchmark scripts

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#98]
The current benchmark script has been improved, but it still lacks the rigor of a proper benchmark.

Investigate using [hyperfine](https://github.com/sharkdp/hyperfine), and perhaps, we can even automate the benchmarks as part of the release process.

**Comment by udsamani** [comment]
@jqnatividad  Let me know if this is being worked upon ? Or I can pick this up !

**Comment by jqnatividad** [comment]
It'd be great if we can parameterize the data to use for the benchmark @udsamani .

NYC's 311 data is a very interesting dataset, and I'd like to keep it as the reference benchmark data, but it'd be great if folks can change the data to use for the benchmark, so its more representative of their data pipelines.

https://github.com/jqnatividad/qsv/blob/master/docs/PERFORMANCE.md#benchmarking-for-performance

**Comment by jqnatividad** [comment]
Hi @udsamani , just checking to see if you have any questions about the old benchmark script...

**Comment by jqnatividad** [comment]
With #542, we'll stick with the benchmark script, just making sure it runs the latest version of qsv, and just run the benchmark manually on release.

Will revisit using hyperfine in the future when we attempt to integrate automating benchmark generation as part of the release process, and adding `wontfix` tag for now...

**Comment by jqnatividad** [comment]
reopening and removing `wontfix` as we add this back to the backlog

**Comment by jqnatividad** [comment]
Finally implemented by @minhajuddin2510 in #1237
