### ISSUE TITLE
Add `QSV_DELIMITER` environment variable

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#99]
Creating a new issue for QSV_DELIMITER implementation, as #47 was too generalized and not discretely actionable.

**Comment by peterjc** [comment]
I would suggest the documentation added in def36e0cbe0f8ea43b3b780bf3e34fdf1cd53fea be a little more explicit in that this _also_ changes the default output (making ``qsv fmt -t "\t"`` redundant).
